// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module vertex_map_streaming_adder_Pipeline_VITIS_LOOP_138_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        adder_in_feed_1_dout,
        adder_in_feed_1_num_data_valid,
        adder_in_feed_1_fifo_cap,
        adder_in_feed_1_empty_n,
        adder_in_feed_1_read,
        v_size,
        accumulators_load_out,
        accumulators_load_out_ap_vld,
        accumulators_1_load_out,
        accumulators_1_load_out_ap_vld,
        accumulators_2_load_out,
        accumulators_2_load_out_ap_vld,
        accumulators_3_load_out,
        accumulators_3_load_out_ap_vld,
        accumulators_4_load_out,
        accumulators_4_load_out_ap_vld,
        accumulators_5_load_out,
        accumulators_5_load_out_ap_vld,
        accumulators_6_load_out,
        accumulators_6_load_out_ap_vld,
        accumulators_7_load_out,
        accumulators_7_load_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] adder_in_feed_1_dout;
input  [7:0] adder_in_feed_1_num_data_valid;
input  [7:0] adder_in_feed_1_fifo_cap;
input   adder_in_feed_1_empty_n;
output   adder_in_feed_1_read;
input  [31:0] v_size;
output  [31:0] accumulators_load_out;
output   accumulators_load_out_ap_vld;
output  [31:0] accumulators_1_load_out;
output   accumulators_1_load_out_ap_vld;
output  [31:0] accumulators_2_load_out;
output   accumulators_2_load_out_ap_vld;
output  [31:0] accumulators_3_load_out;
output   accumulators_3_load_out_ap_vld;
output  [31:0] accumulators_4_load_out;
output   accumulators_4_load_out_ap_vld;
output  [31:0] accumulators_5_load_out;
output   accumulators_5_load_out_ap_vld;
output  [31:0] accumulators_6_load_out;
output   accumulators_6_load_out_ap_vld;
output  [31:0] accumulators_7_load_out;
output   accumulators_7_load_out_ap_vld;

reg ap_idle;
reg accumulators_load_out_ap_vld;
reg accumulators_1_load_out_ap_vld;
reg accumulators_2_load_out_ap_vld;
reg accumulators_3_load_out_ap_vld;
reg accumulators_4_load_out_ap_vld;
reg accumulators_5_load_out_ap_vld;
reg accumulators_6_load_out_ap_vld;
reg accumulators_7_load_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln138_fu_224_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    adder_in_feed_1_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln138_reg_447;
reg   [0:0] icmp_ln138_reg_447_pp0_iter1_reg;
reg   [0:0] icmp_ln138_reg_447_pp0_iter2_reg;
reg   [0:0] icmp_ln138_reg_447_pp0_iter3_reg;
reg   [0:0] icmp_ln138_reg_447_pp0_iter4_reg;
reg   [0:0] icmp_ln138_reg_447_pp0_iter5_reg;
wire   [2:0] trunc_ln138_fu_236_p1;
reg   [2:0] trunc_ln138_reg_451;
reg   [2:0] trunc_ln138_reg_451_pp0_iter1_reg;
reg   [2:0] trunc_ln138_reg_451_pp0_iter2_reg;
reg   [2:0] trunc_ln138_reg_451_pp0_iter3_reg;
reg   [2:0] trunc_ln138_reg_451_pp0_iter4_reg;
reg   [2:0] trunc_ln138_reg_451_pp0_iter5_reg;
reg   [2:0] trunc_ln138_reg_451_pp0_iter6_reg;
reg   [31:0] adder_in_feed_1_read_reg_456;
wire   [31:0] tmp_fu_269_p19;
reg   [31:0] tmp_reg_461;
wire   [31:0] grp_fu_172_p2;
reg   [31:0] accumulators_8_reg_471;
reg   [31:0] i_fu_68;
wire   [31:0] i_1_fu_230_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_i_2;
reg   [31:0] accumulators_7_fu_72;
reg   [31:0] ap_sig_allocacmp_accumulators_7_load_1;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [31:0] accumulators_6_fu_76;
reg   [31:0] ap_sig_allocacmp_accumulators_6_load_1;
reg   [31:0] accumulators_5_fu_80;
reg   [31:0] ap_sig_allocacmp_accumulators_5_load_1;
reg   [31:0] accumulators_4_fu_84;
reg   [31:0] ap_sig_allocacmp_accumulators_4_load_1;
reg   [31:0] accumulators_3_fu_88;
reg   [31:0] ap_sig_allocacmp_accumulators_3_load_1;
reg   [31:0] accumulators_2_fu_92;
reg   [31:0] ap_sig_allocacmp_accumulators_2_load_1;
reg   [31:0] accumulators_1_fu_96;
reg   [31:0] ap_sig_allocacmp_accumulators_1_load_1;
reg   [31:0] accumulators_fu_100;
reg   [31:0] ap_sig_allocacmp_accumulators_load_1;
reg    adder_in_feed_1_read_local;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] grp_fu_172_p1;
wire   [31:0] tmp_fu_269_p17;
reg    grp_fu_172_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_fu_269_p1;
wire   [2:0] tmp_fu_269_p3;
wire   [2:0] tmp_fu_269_p5;
wire   [2:0] tmp_fu_269_p7;
wire  signed [2:0] tmp_fu_269_p9;
wire  signed [2:0] tmp_fu_269_p11;
wire  signed [2:0] tmp_fu_269_p13;
wire  signed [2:0] tmp_fu_269_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 i_fu_68 = 32'd0;
#0 accumulators_7_fu_72 = 32'd0;
#0 accumulators_6_fu_76 = 32'd0;
#0 accumulators_5_fu_80 = 32'd0;
#0 accumulators_4_fu_84 = 32'd0;
#0 accumulators_3_fu_88 = 32'd0;
#0 accumulators_2_fu_92 = 32'd0;
#0 accumulators_1_fu_96 = 32'd0;
#0 accumulators_fu_100 = 32'd0;
#0 ap_done_reg = 1'b0;
end

vertex_map_fadd_32ns_32ns_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_no_dsp_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_reg_461),
    .din1(grp_fu_172_p1),
    .ce(grp_fu_172_ce),
    .dout(grp_fu_172_p2)
);

(* dissolve_hierarchy = "yes" *) vertex_map_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U32(
    .din0(ap_sig_allocacmp_accumulators_load_1),
    .din1(ap_sig_allocacmp_accumulators_1_load_1),
    .din2(ap_sig_allocacmp_accumulators_2_load_1),
    .din3(ap_sig_allocacmp_accumulators_3_load_1),
    .din4(ap_sig_allocacmp_accumulators_4_load_1),
    .din5(ap_sig_allocacmp_accumulators_5_load_1),
    .din6(ap_sig_allocacmp_accumulators_6_load_1),
    .din7(ap_sig_allocacmp_accumulators_7_load_1),
    .def(tmp_fu_269_p17),
    .sel(trunc_ln138_reg_451),
    .dout(tmp_fu_269_p19)
);

vertex_map_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            accumulators_1_fu_96 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd1))) begin
            accumulators_1_fu_96 <= accumulators_8_reg_471;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            accumulators_2_fu_92 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd2))) begin
            accumulators_2_fu_92 <= accumulators_8_reg_471;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            accumulators_3_fu_88 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd3))) begin
            accumulators_3_fu_88 <= accumulators_8_reg_471;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            accumulators_4_fu_84 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd4))) begin
            accumulators_4_fu_84 <= accumulators_8_reg_471;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            accumulators_5_fu_80 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd5))) begin
            accumulators_5_fu_80 <= accumulators_8_reg_471;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            accumulators_6_fu_76 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd6))) begin
            accumulators_6_fu_76 <= accumulators_8_reg_471;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            accumulators_7_fu_72 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd7))) begin
            accumulators_7_fu_72 <= accumulators_8_reg_471;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            accumulators_fu_100 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd0))) begin
            accumulators_fu_100 <= accumulators_8_reg_471;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln138_fu_224_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_68 <= i_1_fu_230_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_68 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        accumulators_8_reg_471 <= grp_fu_172_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        icmp_ln138_reg_447_pp0_iter2_reg <= icmp_ln138_reg_447_pp0_iter1_reg;
        icmp_ln138_reg_447_pp0_iter3_reg <= icmp_ln138_reg_447_pp0_iter2_reg;
        icmp_ln138_reg_447_pp0_iter4_reg <= icmp_ln138_reg_447_pp0_iter3_reg;
        icmp_ln138_reg_447_pp0_iter5_reg <= icmp_ln138_reg_447_pp0_iter4_reg;
        trunc_ln138_reg_451_pp0_iter2_reg <= trunc_ln138_reg_451_pp0_iter1_reg;
        trunc_ln138_reg_451_pp0_iter3_reg <= trunc_ln138_reg_451_pp0_iter2_reg;
        trunc_ln138_reg_451_pp0_iter4_reg <= trunc_ln138_reg_451_pp0_iter3_reg;
        trunc_ln138_reg_451_pp0_iter5_reg <= trunc_ln138_reg_451_pp0_iter4_reg;
        trunc_ln138_reg_451_pp0_iter6_reg <= trunc_ln138_reg_451_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        adder_in_feed_1_read_reg_456 <= adder_in_feed_1_dout;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln138_reg_447 <= icmp_ln138_fu_224_p2;
        icmp_ln138_reg_447_pp0_iter1_reg <= icmp_ln138_reg_447;
        tmp_reg_461 <= tmp_fu_269_p19;
        trunc_ln138_reg_451 <= trunc_ln138_fu_236_p1;
        trunc_ln138_reg_451_pp0_iter1_reg <= trunc_ln138_reg_451;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln138_reg_447_pp0_iter5_reg == 1'd1))) begin
        accumulators_1_load_out_ap_vld = 1'b1;
    end else begin
        accumulators_1_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln138_reg_447_pp0_iter5_reg == 1'd1))) begin
        accumulators_2_load_out_ap_vld = 1'b1;
    end else begin
        accumulators_2_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln138_reg_447_pp0_iter5_reg == 1'd1))) begin
        accumulators_3_load_out_ap_vld = 1'b1;
    end else begin
        accumulators_3_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln138_reg_447_pp0_iter5_reg == 1'd1))) begin
        accumulators_4_load_out_ap_vld = 1'b1;
    end else begin
        accumulators_4_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln138_reg_447_pp0_iter5_reg == 1'd1))) begin
        accumulators_5_load_out_ap_vld = 1'b1;
    end else begin
        accumulators_5_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln138_reg_447_pp0_iter5_reg == 1'd1))) begin
        accumulators_6_load_out_ap_vld = 1'b1;
    end else begin
        accumulators_6_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln138_reg_447_pp0_iter5_reg == 1'd1))) begin
        accumulators_7_load_out_ap_vld = 1'b1;
    end else begin
        accumulators_7_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln138_reg_447_pp0_iter5_reg == 1'd1))) begin
        accumulators_load_out_ap_vld = 1'b1;
    end else begin
        accumulators_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        adder_in_feed_1_blk_n = adder_in_feed_1_empty_n;
    end else begin
        adder_in_feed_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        adder_in_feed_1_read_local = 1'b1;
    end else begin
        adder_in_feed_1_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln138_fu_224_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd1))) begin
        ap_sig_allocacmp_accumulators_1_load_1 = accumulators_8_reg_471;
    end else begin
        ap_sig_allocacmp_accumulators_1_load_1 = accumulators_1_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd2))) begin
        ap_sig_allocacmp_accumulators_2_load_1 = accumulators_8_reg_471;
    end else begin
        ap_sig_allocacmp_accumulators_2_load_1 = accumulators_2_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd3))) begin
        ap_sig_allocacmp_accumulators_3_load_1 = accumulators_8_reg_471;
    end else begin
        ap_sig_allocacmp_accumulators_3_load_1 = accumulators_3_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd4))) begin
        ap_sig_allocacmp_accumulators_4_load_1 = accumulators_8_reg_471;
    end else begin
        ap_sig_allocacmp_accumulators_4_load_1 = accumulators_4_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd5))) begin
        ap_sig_allocacmp_accumulators_5_load_1 = accumulators_8_reg_471;
    end else begin
        ap_sig_allocacmp_accumulators_5_load_1 = accumulators_5_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd6))) begin
        ap_sig_allocacmp_accumulators_6_load_1 = accumulators_8_reg_471;
    end else begin
        ap_sig_allocacmp_accumulators_6_load_1 = accumulators_6_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd7))) begin
        ap_sig_allocacmp_accumulators_7_load_1 = accumulators_8_reg_471;
    end else begin
        ap_sig_allocacmp_accumulators_7_load_1 = accumulators_7_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln138_reg_451_pp0_iter6_reg == 3'd0))) begin
        ap_sig_allocacmp_accumulators_load_1 = accumulators_8_reg_471;
    end else begin
        ap_sig_allocacmp_accumulators_load_1 = accumulators_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_172_ce = 1'b1;
    end else begin
        grp_fu_172_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accumulators_1_load_out = accumulators_1_fu_96;

assign accumulators_2_load_out = accumulators_2_fu_92;

assign accumulators_3_load_out = accumulators_3_fu_88;

assign accumulators_4_load_out = accumulators_4_fu_84;

assign accumulators_5_load_out = accumulators_5_fu_80;

assign accumulators_6_load_out = accumulators_6_fu_76;

assign accumulators_7_load_out = accumulators_7_fu_72;

assign accumulators_load_out = accumulators_fu_100;

assign adder_in_feed_1_read = adder_in_feed_1_read_local;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (1'b0 == adder_in_feed_1_empty_n);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_172_p1 = adder_in_feed_1_read_reg_456;

assign i_1_fu_230_p2 = (ap_sig_allocacmp_i_2 + 32'd1);

assign icmp_ln138_fu_224_p2 = ((ap_sig_allocacmp_i_2 == v_size) ? 1'b1 : 1'b0);

assign tmp_fu_269_p17 = 'bx;

assign trunc_ln138_fu_236_p1 = ap_sig_allocacmp_i_2[2:0];

endmodule //vertex_map_streaming_adder_Pipeline_VITIS_LOOP_138_2
