// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module vertex_map_readMemU (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        elements_u_fifo_din,
        elements_u_fifo_num_data_valid,
        elements_u_fifo_fifo_cap,
        elements_u_fifo_full_n,
        elements_u_fifo_write,
        m_axi_gmem_CHN_5_AWVALID,
        m_axi_gmem_CHN_5_AWREADY,
        m_axi_gmem_CHN_5_AWADDR,
        m_axi_gmem_CHN_5_AWID,
        m_axi_gmem_CHN_5_AWLEN,
        m_axi_gmem_CHN_5_AWSIZE,
        m_axi_gmem_CHN_5_AWBURST,
        m_axi_gmem_CHN_5_AWLOCK,
        m_axi_gmem_CHN_5_AWCACHE,
        m_axi_gmem_CHN_5_AWPROT,
        m_axi_gmem_CHN_5_AWQOS,
        m_axi_gmem_CHN_5_AWREGION,
        m_axi_gmem_CHN_5_AWUSER,
        m_axi_gmem_CHN_5_WVALID,
        m_axi_gmem_CHN_5_WREADY,
        m_axi_gmem_CHN_5_WDATA,
        m_axi_gmem_CHN_5_WSTRB,
        m_axi_gmem_CHN_5_WLAST,
        m_axi_gmem_CHN_5_WID,
        m_axi_gmem_CHN_5_WUSER,
        m_axi_gmem_CHN_5_ARVALID,
        m_axi_gmem_CHN_5_ARREADY,
        m_axi_gmem_CHN_5_ARADDR,
        m_axi_gmem_CHN_5_ARID,
        m_axi_gmem_CHN_5_ARLEN,
        m_axi_gmem_CHN_5_ARSIZE,
        m_axi_gmem_CHN_5_ARBURST,
        m_axi_gmem_CHN_5_ARLOCK,
        m_axi_gmem_CHN_5_ARCACHE,
        m_axi_gmem_CHN_5_ARPROT,
        m_axi_gmem_CHN_5_ARQOS,
        m_axi_gmem_CHN_5_ARREGION,
        m_axi_gmem_CHN_5_ARUSER,
        m_axi_gmem_CHN_5_RVALID,
        m_axi_gmem_CHN_5_RREADY,
        m_axi_gmem_CHN_5_RDATA,
        m_axi_gmem_CHN_5_RLAST,
        m_axi_gmem_CHN_5_RID,
        m_axi_gmem_CHN_5_RFIFONUM,
        m_axi_gmem_CHN_5_RUSER,
        m_axi_gmem_CHN_5_RRESP,
        m_axi_gmem_CHN_5_BVALID,
        m_axi_gmem_CHN_5_BREADY,
        m_axi_gmem_CHN_5_BRESP,
        m_axi_gmem_CHN_5_BID,
        m_axi_gmem_CHN_5_BUSER,
        mem_u,
        sizes_1_dout,
        sizes_1_num_data_valid,
        sizes_1_fifo_cap,
        sizes_1_empty_n,
        sizes_1_read,
        u_neighbors_fifo_dout,
        u_neighbors_fifo_num_data_valid,
        u_neighbors_fifo_fifo_cap,
        u_neighbors_fifo_empty_n,
        u_neighbors_fifo_read,
        u_size_fifo_readMemU_dout,
        u_size_fifo_readMemU_num_data_valid,
        u_size_fifo_readMemU_fifo_cap,
        u_size_fifo_readMemU_empty_n,
        u_size_fifo_readMemU_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [31:0] elements_u_fifo_din;
input  [7:0] elements_u_fifo_num_data_valid;
input  [7:0] elements_u_fifo_fifo_cap;
input   elements_u_fifo_full_n;
output   elements_u_fifo_write;
output   m_axi_gmem_CHN_5_AWVALID;
input   m_axi_gmem_CHN_5_AWREADY;
output  [63:0] m_axi_gmem_CHN_5_AWADDR;
output  [0:0] m_axi_gmem_CHN_5_AWID;
output  [31:0] m_axi_gmem_CHN_5_AWLEN;
output  [2:0] m_axi_gmem_CHN_5_AWSIZE;
output  [1:0] m_axi_gmem_CHN_5_AWBURST;
output  [1:0] m_axi_gmem_CHN_5_AWLOCK;
output  [3:0] m_axi_gmem_CHN_5_AWCACHE;
output  [2:0] m_axi_gmem_CHN_5_AWPROT;
output  [3:0] m_axi_gmem_CHN_5_AWQOS;
output  [3:0] m_axi_gmem_CHN_5_AWREGION;
output  [0:0] m_axi_gmem_CHN_5_AWUSER;
output   m_axi_gmem_CHN_5_WVALID;
input   m_axi_gmem_CHN_5_WREADY;
output  [63:0] m_axi_gmem_CHN_5_WDATA;
output  [7:0] m_axi_gmem_CHN_5_WSTRB;
output   m_axi_gmem_CHN_5_WLAST;
output  [0:0] m_axi_gmem_CHN_5_WID;
output  [0:0] m_axi_gmem_CHN_5_WUSER;
output   m_axi_gmem_CHN_5_ARVALID;
input   m_axi_gmem_CHN_5_ARREADY;
output  [63:0] m_axi_gmem_CHN_5_ARADDR;
output  [0:0] m_axi_gmem_CHN_5_ARID;
output  [31:0] m_axi_gmem_CHN_5_ARLEN;
output  [2:0] m_axi_gmem_CHN_5_ARSIZE;
output  [1:0] m_axi_gmem_CHN_5_ARBURST;
output  [1:0] m_axi_gmem_CHN_5_ARLOCK;
output  [3:0] m_axi_gmem_CHN_5_ARCACHE;
output  [2:0] m_axi_gmem_CHN_5_ARPROT;
output  [3:0] m_axi_gmem_CHN_5_ARQOS;
output  [3:0] m_axi_gmem_CHN_5_ARREGION;
output  [0:0] m_axi_gmem_CHN_5_ARUSER;
input   m_axi_gmem_CHN_5_RVALID;
output   m_axi_gmem_CHN_5_RREADY;
input  [63:0] m_axi_gmem_CHN_5_RDATA;
input   m_axi_gmem_CHN_5_RLAST;
input  [0:0] m_axi_gmem_CHN_5_RID;
input  [10:0] m_axi_gmem_CHN_5_RFIFONUM;
input  [0:0] m_axi_gmem_CHN_5_RUSER;
input  [1:0] m_axi_gmem_CHN_5_RRESP;
input   m_axi_gmem_CHN_5_BVALID;
output   m_axi_gmem_CHN_5_BREADY;
input  [1:0] m_axi_gmem_CHN_5_BRESP;
input  [0:0] m_axi_gmem_CHN_5_BID;
input  [0:0] m_axi_gmem_CHN_5_BUSER;
input  [63:0] mem_u;
input  [31:0] sizes_1_dout;
input  [4:0] sizes_1_num_data_valid;
input  [4:0] sizes_1_fifo_cap;
input   sizes_1_empty_n;
output   sizes_1_read;
input  [63:0] u_neighbors_fifo_dout;
input  [5:0] u_neighbors_fifo_num_data_valid;
input  [5:0] u_neighbors_fifo_fifo_cap;
input   u_neighbors_fifo_empty_n;
output   u_neighbors_fifo_read;
input  [31:0] u_size_fifo_readMemU_dout;
input  [4:0] u_size_fifo_readMemU_num_data_valid;
input  [4:0] u_size_fifo_readMemU_fifo_cap;
input   u_size_fifo_readMemU_empty_n;
output   u_size_fifo_readMemU_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg elements_u_fifo_write;
reg m_axi_gmem_CHN_5_ARVALID;
reg m_axi_gmem_CHN_5_RREADY;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    sizes_1_blk_n;
reg    u_neighbors_fifo_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln74_fu_109_p2;
reg    u_size_fifo_readMemU_blk_n;
reg    ap_block_state1;
reg   [31:0] v_size_reg_137;
reg   [31:0] u_size_reg_145;
reg    ap_block_state2;
reg   [63:0] u_neighbors_reg_150;
wire    grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_start;
wire    grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_done;
wire    grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_idle;
wire    grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_ready;
wire    grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWVALID;
wire   [63:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWADDR;
wire   [0:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWID;
wire   [31:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWLEN;
wire   [2:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWSIZE;
wire   [1:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWBURST;
wire   [1:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWLOCK;
wire   [3:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWCACHE;
wire   [2:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWPROT;
wire   [3:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWQOS;
wire   [3:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWREGION;
wire   [0:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWUSER;
wire    grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_WVALID;
wire   [63:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_WDATA;
wire   [7:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_WSTRB;
wire    grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_WLAST;
wire   [0:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_WID;
wire   [0:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_WUSER;
wire    grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARVALID;
wire   [63:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARADDR;
wire   [0:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARID;
wire   [31:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARLEN;
wire   [2:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARSIZE;
wire   [1:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARBURST;
wire   [1:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARLOCK;
wire   [3:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARCACHE;
wire   [2:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARPROT;
wire   [3:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARQOS;
wire   [3:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARREGION;
wire   [0:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARUSER;
wire    grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_RREADY;
wire    grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_BREADY;
wire   [31:0] grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_elements_u_fifo_din;
wire    grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_elements_u_fifo_write;
reg    grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [31:0] j_fu_62;
wire   [31:0] j_4_fu_114_p2;
reg    sizes_1_read_local;
reg    u_size_fifo_readMemU_read_local;
reg    u_neighbors_fifo_read_local;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_start_reg = 1'b0;
#0 j_fu_62 = 32'd0;
end

vertex_map_readMemU_Pipeline_VITIS_LOOP_79_2 grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_start),
    .ap_done(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_done),
    .ap_idle(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_idle),
    .ap_ready(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_ready),
    .m_axi_gmem_CHN_5_AWVALID(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWVALID),
    .m_axi_gmem_CHN_5_AWREADY(1'b0),
    .m_axi_gmem_CHN_5_AWADDR(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWADDR),
    .m_axi_gmem_CHN_5_AWID(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWID),
    .m_axi_gmem_CHN_5_AWLEN(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWLEN),
    .m_axi_gmem_CHN_5_AWSIZE(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWSIZE),
    .m_axi_gmem_CHN_5_AWBURST(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWBURST),
    .m_axi_gmem_CHN_5_AWLOCK(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWLOCK),
    .m_axi_gmem_CHN_5_AWCACHE(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWCACHE),
    .m_axi_gmem_CHN_5_AWPROT(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWPROT),
    .m_axi_gmem_CHN_5_AWQOS(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWQOS),
    .m_axi_gmem_CHN_5_AWREGION(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWREGION),
    .m_axi_gmem_CHN_5_AWUSER(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_AWUSER),
    .m_axi_gmem_CHN_5_WVALID(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_WVALID),
    .m_axi_gmem_CHN_5_WREADY(1'b0),
    .m_axi_gmem_CHN_5_WDATA(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_WDATA),
    .m_axi_gmem_CHN_5_WSTRB(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_WSTRB),
    .m_axi_gmem_CHN_5_WLAST(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_WLAST),
    .m_axi_gmem_CHN_5_WID(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_WID),
    .m_axi_gmem_CHN_5_WUSER(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_WUSER),
    .m_axi_gmem_CHN_5_ARVALID(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARVALID),
    .m_axi_gmem_CHN_5_ARREADY(m_axi_gmem_CHN_5_ARREADY),
    .m_axi_gmem_CHN_5_ARADDR(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARADDR),
    .m_axi_gmem_CHN_5_ARID(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARID),
    .m_axi_gmem_CHN_5_ARLEN(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARLEN),
    .m_axi_gmem_CHN_5_ARSIZE(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARSIZE),
    .m_axi_gmem_CHN_5_ARBURST(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARBURST),
    .m_axi_gmem_CHN_5_ARLOCK(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARLOCK),
    .m_axi_gmem_CHN_5_ARCACHE(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARCACHE),
    .m_axi_gmem_CHN_5_ARPROT(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARPROT),
    .m_axi_gmem_CHN_5_ARQOS(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARQOS),
    .m_axi_gmem_CHN_5_ARREGION(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARREGION),
    .m_axi_gmem_CHN_5_ARUSER(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARUSER),
    .m_axi_gmem_CHN_5_RVALID(m_axi_gmem_CHN_5_RVALID),
    .m_axi_gmem_CHN_5_RREADY(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_RREADY),
    .m_axi_gmem_CHN_5_RDATA(m_axi_gmem_CHN_5_RDATA),
    .m_axi_gmem_CHN_5_RLAST(m_axi_gmem_CHN_5_RLAST),
    .m_axi_gmem_CHN_5_RID(m_axi_gmem_CHN_5_RID),
    .m_axi_gmem_CHN_5_RFIFONUM(m_axi_gmem_CHN_5_RFIFONUM),
    .m_axi_gmem_CHN_5_RUSER(m_axi_gmem_CHN_5_RUSER),
    .m_axi_gmem_CHN_5_RRESP(m_axi_gmem_CHN_5_RRESP),
    .m_axi_gmem_CHN_5_BVALID(1'b0),
    .m_axi_gmem_CHN_5_BREADY(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_BREADY),
    .m_axi_gmem_CHN_5_BRESP(2'd0),
    .m_axi_gmem_CHN_5_BID(1'd0),
    .m_axi_gmem_CHN_5_BUSER(1'd0),
    .elements_u_fifo_din(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_elements_u_fifo_din),
    .elements_u_fifo_num_data_valid(8'd0),
    .elements_u_fifo_fifo_cap(8'd0),
    .elements_u_fifo_full_n(elements_u_fifo_full_n),
    .elements_u_fifo_write(grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_elements_u_fifo_write),
    .u_size(u_size_reg_145),
    .mem_u(mem_u),
    .u_neighbors(u_neighbors_reg_150)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln74_fu_109_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_start_reg <= 1'b1;
        end else if ((grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_ready == 1'b1)) begin
            grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        j_fu_62 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln74_fu_109_p2 == 1'd0))) begin
        j_fu_62 <= j_4_fu_114_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        u_neighbors_reg_150 <= u_neighbors_fifo_dout;
        u_size_reg_145 <= u_size_fifo_readMemU_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        v_size_reg_137 <= sizes_1_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln74_fu_109_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln74_fu_109_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        elements_u_fifo_write = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_elements_u_fifo_write;
    end else begin
        elements_u_fifo_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_CHN_5_ARVALID = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARVALID;
    end else begin
        m_axi_gmem_CHN_5_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_CHN_5_RREADY = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_RREADY;
    end else begin
        m_axi_gmem_CHN_5_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sizes_1_blk_n = sizes_1_empty_n;
    end else begin
        sizes_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        sizes_1_read_local = 1'b1;
    end else begin
        sizes_1_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln74_fu_109_p2 == 1'd0))) begin
        u_neighbors_fifo_blk_n = u_neighbors_fifo_empty_n;
    end else begin
        u_neighbors_fifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln74_fu_109_p2 == 1'd0))) begin
        u_neighbors_fifo_read_local = 1'b1;
    end else begin
        u_neighbors_fifo_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln74_fu_109_p2 == 1'd0))) begin
        u_size_fifo_readMemU_blk_n = u_size_fifo_readMemU_empty_n;
    end else begin
        u_size_fifo_readMemU_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln74_fu_109_p2 == 1'd0))) begin
        u_size_fifo_readMemU_read_local = 1'b1;
    end else begin
        u_size_fifo_readMemU_read_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln74_fu_109_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2) & (icmp_ln74_fu_109_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (sizes_1_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = (((icmp_ln74_fu_109_p2 == 1'd0) & (u_neighbors_fifo_empty_n == 1'b0)) | ((icmp_ln74_fu_109_p2 == 1'd0) & (u_size_fifo_readMemU_empty_n == 1'b0)));
end

assign elements_u_fifo_din = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_elements_u_fifo_din;

assign grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_start = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_ap_start_reg;

assign icmp_ln74_fu_109_p2 = ((j_fu_62 == v_size_reg_137) ? 1'b1 : 1'b0);

assign j_4_fu_114_p2 = (j_fu_62 + 32'd1);

assign m_axi_gmem_CHN_5_ARADDR = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARADDR;

assign m_axi_gmem_CHN_5_ARBURST = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARBURST;

assign m_axi_gmem_CHN_5_ARCACHE = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARCACHE;

assign m_axi_gmem_CHN_5_ARID = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARID;

assign m_axi_gmem_CHN_5_ARLEN = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARLEN;

assign m_axi_gmem_CHN_5_ARLOCK = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARLOCK;

assign m_axi_gmem_CHN_5_ARPROT = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARPROT;

assign m_axi_gmem_CHN_5_ARQOS = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARQOS;

assign m_axi_gmem_CHN_5_ARREGION = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARREGION;

assign m_axi_gmem_CHN_5_ARSIZE = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARSIZE;

assign m_axi_gmem_CHN_5_ARUSER = grp_readMemU_Pipeline_VITIS_LOOP_79_2_fu_90_m_axi_gmem_CHN_5_ARUSER;

assign m_axi_gmem_CHN_5_AWADDR = 64'd0;

assign m_axi_gmem_CHN_5_AWBURST = 2'd0;

assign m_axi_gmem_CHN_5_AWCACHE = 4'd0;

assign m_axi_gmem_CHN_5_AWID = 1'd0;

assign m_axi_gmem_CHN_5_AWLEN = 32'd0;

assign m_axi_gmem_CHN_5_AWLOCK = 2'd0;

assign m_axi_gmem_CHN_5_AWPROT = 3'd0;

assign m_axi_gmem_CHN_5_AWQOS = 4'd0;

assign m_axi_gmem_CHN_5_AWREGION = 4'd0;

assign m_axi_gmem_CHN_5_AWSIZE = 3'd0;

assign m_axi_gmem_CHN_5_AWUSER = 1'd0;

assign m_axi_gmem_CHN_5_AWVALID = 1'b0;

assign m_axi_gmem_CHN_5_BREADY = 1'b0;

assign m_axi_gmem_CHN_5_WDATA = 64'd0;

assign m_axi_gmem_CHN_5_WID = 1'd0;

assign m_axi_gmem_CHN_5_WLAST = 1'b0;

assign m_axi_gmem_CHN_5_WSTRB = 8'd0;

assign m_axi_gmem_CHN_5_WUSER = 1'd0;

assign m_axi_gmem_CHN_5_WVALID = 1'b0;

assign sizes_1_read = sizes_1_read_local;

assign u_neighbors_fifo_read = u_neighbors_fifo_read_local;

assign u_size_fifo_readMemU_read = u_size_fifo_readMemU_read_local;

endmodule //vertex_map_readMemU
