// Generated by CIRCT firtool-1.62.0
module AddressTransform(	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  output         s_axi_ar_ready,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input          s_axi_ar_valid,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input  [5:0]   s_axi_ar_bits_id,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input  [37:0]  s_axi_ar_bits_addr,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input  [3:0]   s_axi_ar_bits_len,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input  [2:0]   s_axi_ar_bits_size,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input  [1:0]   s_axi_ar_bits_burst,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input          s_axi_r_ready,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  output         s_axi_r_valid,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  output [5:0]   s_axi_r_bits_id,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  output [255:0] s_axi_r_bits_data,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  output [1:0]   s_axi_r_bits_resp,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  output         s_axi_r_bits_last,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
                 s_axi_aw_ready,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input          s_axi_aw_valid,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input  [5:0]   s_axi_aw_bits_id,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input  [37:0]  s_axi_aw_bits_addr,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input  [3:0]   s_axi_aw_bits_len,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input  [2:0]   s_axi_aw_bits_size,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input  [1:0]   s_axi_aw_bits_burst,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  output         s_axi_w_ready,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input          s_axi_w_valid,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input  [255:0] s_axi_w_bits_data,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input  [31:0]  s_axi_w_bits_strb,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input          s_axi_w_bits_last,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
                 s_axi_b_ready,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  output         s_axi_b_valid,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  output [5:0]   s_axi_b_bits_id,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  output [1:0]   s_axi_b_bits_resp,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:26:17
  input          m_axi_ar_ready,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output         m_axi_ar_valid,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output [5:0]   m_axi_ar_bits_id,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output [37:0]  m_axi_ar_bits_addr,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output [3:0]   m_axi_ar_bits_len,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output [2:0]   m_axi_ar_bits_size,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output [1:0]   m_axi_ar_bits_burst,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output         m_axi_r_ready,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  input          m_axi_r_valid,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  input  [5:0]   m_axi_r_bits_id,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  input  [255:0] m_axi_r_bits_data,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  input  [1:0]   m_axi_r_bits_resp,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  input          m_axi_r_bits_last,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
                 m_axi_aw_ready,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output         m_axi_aw_valid,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output [5:0]   m_axi_aw_bits_id,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output [37:0]  m_axi_aw_bits_addr,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output [3:0]   m_axi_aw_bits_len,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output [2:0]   m_axi_aw_bits_size,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output [1:0]   m_axi_aw_bits_burst,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  input          m_axi_w_ready,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output         m_axi_w_valid,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output [255:0] m_axi_w_bits_data,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output [31:0]  m_axi_w_bits_strb,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  output         m_axi_w_bits_last,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
                 m_axi_b_ready,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  input          m_axi_b_valid,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  input  [5:0]   m_axi_b_bits_id,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
  input  [1:0]   m_axi_b_bits_resp	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:27:17
);

  assign s_axi_ar_ready = m_axi_ar_ready;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign s_axi_r_valid = m_axi_r_valid;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign s_axi_r_bits_id = m_axi_r_bits_id;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign s_axi_r_bits_data = m_axi_r_bits_data;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign s_axi_r_bits_resp = m_axi_r_bits_resp;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign s_axi_r_bits_last = m_axi_r_bits_last;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign s_axi_aw_ready = m_axi_aw_ready;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign s_axi_w_ready = m_axi_w_ready;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign s_axi_b_valid = m_axi_b_valid;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign s_axi_b_bits_id = m_axi_b_bits_id;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign s_axi_b_bits_resp = m_axi_b_bits_resp;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_ar_valid = s_axi_ar_valid;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_ar_bits_id = s_axi_ar_bits_id;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_ar_bits_addr =
    {s_axi_ar_bits_addr[37:33],
     s_axi_ar_bits_addr[17:14],
     s_axi_ar_bits_addr[28:18],
     s_axi_ar_bits_addr[32:29],
     s_axi_ar_bits_addr[13:0]};	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7, src/main/scala/chext/util/BitOps.scala:107:14
  assign m_axi_ar_bits_len = s_axi_ar_bits_len;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_ar_bits_size = s_axi_ar_bits_size;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_ar_bits_burst = s_axi_ar_bits_burst;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_r_ready = s_axi_r_ready;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_aw_valid = s_axi_aw_valid;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_aw_bits_id = s_axi_aw_bits_id;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_aw_bits_addr =
    {s_axi_aw_bits_addr[37:33],
     s_axi_aw_bits_addr[17:14],
     s_axi_aw_bits_addr[28:18],
     s_axi_aw_bits_addr[32:29],
     s_axi_aw_bits_addr[13:0]};	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7, src/main/scala/chext/util/BitOps.scala:107:14
  assign m_axi_aw_bits_len = s_axi_aw_bits_len;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_aw_bits_size = s_axi_aw_bits_size;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_aw_bits_burst = s_axi_aw_bits_burst;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_w_valid = s_axi_w_valid;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_w_bits_data = s_axi_w_bits_data;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_w_bits_strb = s_axi_w_bits_strb;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_w_bits_last = s_axi_w_bits_last;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
  assign m_axi_b_ready = s_axi_b_ready;	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/AddressTransform.scala:23:7
endmodule

module AddressTransformHardcilk(	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:325:7
  input          clock,	// <stdin>:271:11
                 reset,	// <stdin>:272:11
  output         S_AXI_ARREADY,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input          S_AXI_ARVALID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input  [5:0]   S_AXI_ARID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input  [37:0]  S_AXI_ARADDR,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input  [3:0]   S_AXI_ARLEN,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input  [2:0]   S_AXI_ARSIZE,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input  [1:0]   S_AXI_ARBURST,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input          S_AXI_RREADY,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  output         S_AXI_RVALID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  output [5:0]   S_AXI_RID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  output [255:0] S_AXI_RDATA,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  output [1:0]   S_AXI_RRESP,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  output         S_AXI_RLAST,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
                 S_AXI_AWREADY,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input          S_AXI_AWVALID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input  [5:0]   S_AXI_AWID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input  [37:0]  S_AXI_AWADDR,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input  [3:0]   S_AXI_AWLEN,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input  [2:0]   S_AXI_AWSIZE,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input  [1:0]   S_AXI_AWBURST,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  output         S_AXI_WREADY,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input          S_AXI_WVALID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input  [255:0] S_AXI_WDATA,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input  [31:0]  S_AXI_WSTRB,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input          S_AXI_WLAST,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
                 S_AXI_BREADY,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  output         S_AXI_BVALID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  output [5:0]   S_AXI_BID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  output [1:0]   S_AXI_BRESP,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:330:17
  input          M_AXI_ARREADY,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output         M_AXI_ARVALID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output [5:0]   M_AXI_ARID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output [37:0]  M_AXI_ARADDR,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output [3:0]   M_AXI_ARLEN,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output [2:0]   M_AXI_ARSIZE,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output [1:0]   M_AXI_ARBURST,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output         M_AXI_RREADY,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  input          M_AXI_RVALID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  input  [5:0]   M_AXI_RID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  input  [255:0] M_AXI_RDATA,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  input  [1:0]   M_AXI_RRESP,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  input          M_AXI_RLAST,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
                 M_AXI_AWREADY,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output         M_AXI_AWVALID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output [5:0]   M_AXI_AWID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output [37:0]  M_AXI_AWADDR,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output [3:0]   M_AXI_AWLEN,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output [2:0]   M_AXI_AWSIZE,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output [1:0]   M_AXI_AWBURST,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  input          M_AXI_WREADY,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output         M_AXI_WVALID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output [255:0] M_AXI_WDATA,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output [31:0]  M_AXI_WSTRB,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  output         M_AXI_WLAST,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
                 M_AXI_BREADY,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  input          M_AXI_BVALID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  input  [5:0]   M_AXI_BID,	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
  input  [1:0]   M_AXI_BRESP	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:331:17
);

  AddressTransform dut (	// janberq/repos/hdlstuff/chext-accel/src/main/scala/triangle_count/PeHardcilk.scala:328:27
    .s_axi_ar_ready      (S_AXI_ARREADY),
    .s_axi_ar_valid      (S_AXI_ARVALID),
    .s_axi_ar_bits_id    (S_AXI_ARID),
    .s_axi_ar_bits_addr  (S_AXI_ARADDR),
    .s_axi_ar_bits_len   (S_AXI_ARLEN),
    .s_axi_ar_bits_size  (S_AXI_ARSIZE),
    .s_axi_ar_bits_burst (S_AXI_ARBURST),
    .s_axi_r_ready       (S_AXI_RREADY),
    .s_axi_r_valid       (S_AXI_RVALID),
    .s_axi_r_bits_id     (S_AXI_RID),
    .s_axi_r_bits_data   (S_AXI_RDATA),
    .s_axi_r_bits_resp   (S_AXI_RRESP),
    .s_axi_r_bits_last   (S_AXI_RLAST),
    .s_axi_aw_ready      (S_AXI_AWREADY),
    .s_axi_aw_valid      (S_AXI_AWVALID),
    .s_axi_aw_bits_id    (S_AXI_AWID),
    .s_axi_aw_bits_addr  (S_AXI_AWADDR),
    .s_axi_aw_bits_len   (S_AXI_AWLEN),
    .s_axi_aw_bits_size  (S_AXI_AWSIZE),
    .s_axi_aw_bits_burst (S_AXI_AWBURST),
    .s_axi_w_ready       (S_AXI_WREADY),
    .s_axi_w_valid       (S_AXI_WVALID),
    .s_axi_w_bits_data   (S_AXI_WDATA),
    .s_axi_w_bits_strb   (S_AXI_WSTRB),
    .s_axi_w_bits_last   (S_AXI_WLAST),
    .s_axi_b_ready       (S_AXI_BREADY),
    .s_axi_b_valid       (S_AXI_BVALID),
    .s_axi_b_bits_id     (S_AXI_BID),
    .s_axi_b_bits_resp   (S_AXI_BRESP),
    .m_axi_ar_ready      (M_AXI_ARREADY),
    .m_axi_ar_valid      (M_AXI_ARVALID),
    .m_axi_ar_bits_id    (M_AXI_ARID),
    .m_axi_ar_bits_addr  (M_AXI_ARADDR),
    .m_axi_ar_bits_len   (M_AXI_ARLEN),
    .m_axi_ar_bits_size  (M_AXI_ARSIZE),
    .m_axi_ar_bits_burst (M_AXI_ARBURST),
    .m_axi_r_ready       (M_AXI_RREADY),
    .m_axi_r_valid       (M_AXI_RVALID),
    .m_axi_r_bits_id     (M_AXI_RID),
    .m_axi_r_bits_data   (M_AXI_RDATA),
    .m_axi_r_bits_resp   (M_AXI_RRESP),
    .m_axi_r_bits_last   (M_AXI_RLAST),
    .m_axi_aw_ready      (M_AXI_AWREADY),
    .m_axi_aw_valid      (M_AXI_AWVALID),
    .m_axi_aw_bits_id    (M_AXI_AWID),
    .m_axi_aw_bits_addr  (M_AXI_AWADDR),
    .m_axi_aw_bits_len   (M_AXI_AWLEN),
    .m_axi_aw_bits_size  (M_AXI_AWSIZE),
    .m_axi_aw_bits_burst (M_AXI_AWBURST),
    .m_axi_w_ready       (M_AXI_WREADY),
    .m_axi_w_valid       (M_AXI_WVALID),
    .m_axi_w_bits_data   (M_AXI_WDATA),
    .m_axi_w_bits_strb   (M_AXI_WSTRB),
    .m_axi_w_bits_last   (M_AXI_WLAST),
    .m_axi_b_ready       (M_AXI_BREADY),
    .m_axi_b_valid       (M_AXI_BVALID),
    .m_axi_b_bits_id     (M_AXI_BID),
    .m_axi_b_bits_resp   (M_AXI_BRESP)
  );
endmodule

