# =============================================================================
# Generated by bombyx-cc — Vitis HLS synthesis script
# Application : memAccess
# Kernel      : whileLoopMain
# Part        : xcu55c-fsvh2892-2L-e
# Clock       : 300 MHz  (3.3333 ns)
#
# Run from the PE work directory:
#   mkdir -p vitis_hls_work/whileLoopMain
#   cd vitis_hls_work/whileLoopMain
#   vitis_hls -f ../../hls_tcl/whileLoopMain.tcl
# =============================================================================

set script_dir [file normalize [file dirname [info script]]]
set src_dir    [file normalize [file join $script_dir ".."]]

# ── Project setup ─────────────────────────────────────────────────────────────
open_project -reset whileLoopMain_proj
set_top whileLoopMain

# ── Source files ──────────────────────────────────────────────────────────────
add_files [file join $src_dir memAccess.cpp]
add_files [file join $src_dir memAccess_defs.h]

# ── Solution configuration ────────────────────────────────────────────────────
open_solution -reset "solution1" -flow_target vitis
set_part {xcu55c-fsvh2892-2L-e}
create_clock -period 3.3333 -name default

# ── Synthesis ─────────────────────────────────────────────────────────────────
csynth_design

# ── Teardown ──────────────────────────────────────────────────────────────────
close_project
exit
