package Util

import chisel3._
import chisel3.util._
import chext.elastic


class AtomicGrantIO(peCount: Int, bitWidth: Int) extends Bundle {
  val lockTags = Vec(peCount, Flipped(DecoupledIO(UInt(bitWidth.W))))
  val unlockTags = Vec(peCount, Flipped(DecoupledIO(UInt(bitWidth.W))))
}

class ElasticShifter(depth : Int, bitWidth : Int) extends Module{
    val io = IO(new Bundle{
        val in = Flipped(Decoupled(UInt(bitWidth.W)))
        val out = Decoupled(UInt(bitWidth.W))
    })
    
    val pending = RegInit(false.B)
    val pendingPrevious = RegNext(pending)

    val shiftReg = RegInit(VecInit(Seq.fill(depth)(0.U(bitWidth.W))))
    val shiftRegValid = RegInit(VecInit(Seq.fill(depth)(false.B)))


    shiftReg(0) := io.in.bits 
    shiftRegValid(0) := io.in.valid && ~pending

    for(i <- 1 until depth){
        shiftReg(i) := shiftReg(i-1)
        shiftRegValid(i) := shiftRegValid(i-1)
    }

    when(io.in.valid){
      pending := true.B
    }.elsewhen(io.in.ready){
      pending := false.B
    }

    val outputBitsReg = RegInit(0.U(bitWidth.W))
    val outputValidReg = RegInit(false.B)
    val takeValid = RegInit(false.B)
    
    when(pending && ~pendingPrevious){
      takeValid := true.B
    }

    when(takeValid && shiftRegValid(depth-1) === true.B){
      outputBitsReg := shiftReg(depth-1)
      outputValidReg := shiftRegValid(depth-1)
      takeValid := false.B
    }

    io.out.bits := outputBitsReg
    io.out.valid := outputValidReg

    when(io.out.ready){
      outputValidReg := false.B
    }


    // in ready is generated by a shift register of out ready of depth depth
    val inReadyShiftReg = RegInit(VecInit(Seq.fill(depth)(false.B)))
    inReadyShiftReg(0) := io.out.ready
    for(i <- 1 until depth){
        inReadyShiftReg(i) := inReadyShiftReg(i-1)
    }
    io.in.ready := inReadyShiftReg(depth-1) 
    
}

class AtomicGrant(peCount: Int, bitWidth: Int, depth: Int) extends Module {
  val io = IO(new AtomicGrantIO(peCount, bitWidth))

  assert(peCount > 0, "AtomicGrant: peCount must be greater than 0")
  assert(bitWidth > 0, "AtomicGrant: bitWidth must be greater than 0")
  assert(depth >= 2, "AtomicGrant: depth must be greater than or equal to 2")

  // Register file to hold lock ownership
  val registerFile = RegInit(VecInit(Seq.fill(1 << bitWidth)(false.B)))

  // Arbitration for lock and unlock requests
  val lockArbiter = Module(new elastic.BasicArbiter(UInt(bitWidth.W), peCount, elastic.Chooser.rr))
  val unlockArbiter = Module(new elastic.BasicArbiter(UInt(bitWidth.W), peCount, elastic.Chooser.rr))

  lockArbiter.io.select.deq();
  unlockArbiter.io.select.deq();

  // Break input and output paths with elastic shifters
  val lockShifters = Seq.fill(peCount)(Module(new ElasticShifter(depth, bitWidth)))
  val unlockShifters = Seq.fill(peCount)(Module(new ElasticShifter(depth, bitWidth)))

  val lockSuccess = RegInit(false.B)
  val unlockSuccess = RegInit(false.B)
  
  // Connect lock and unlock requests to shifterslockShifters
  lockShifters.zip(io.lockTags).foreach { case (shifter, lockTag) =>
    shifter.io.in.valid := lockTag.valid
    shifter.io.in.bits := lockTag.bits
    lockTag.ready := shifter.io.in.ready
  }

  unlockShifters.zip(io.unlockTags).foreach { case (shifter, unlockTag) =>
    shifter.io.in.valid := unlockTag.valid
    shifter.io.in.bits := unlockTag.bits
    unlockTag.ready := shifter.io.in.ready
  } 

  // Connect shifters to arbiter sources

  lockArbiter.io.sources.zipWithIndex.foreach { case (source, index) =>
    source.valid := lockShifters(index).io.out.valid
    source.bits := lockShifters(index).io.out.bits
    lockShifters(index).io.out.ready := (RegNext(RegNext(source.ready)) && source.valid && lockSuccess)
  }

  unlockArbiter.io.sources.zipWithIndex.foreach { case (source, index) =>
    source.valid := unlockShifters(index).io.out.valid
    source.bits := unlockShifters(index).io.out.bits
    unlockShifters(index).io.out.ready := (RegNext(RegNext(source.ready)) && source.valid && unlockSuccess)
  }

  // Default values for the arbiter sink
  elastic.Disposed(unlockArbiter.io.sink)
  elastic.Disposed(lockArbiter.io.sink)

  // Create the logic that reads the arbiter sink and updates the register file accordingly
  when(lockArbiter.io.sink.valid && unlockArbiter.io.sink.valid && lockArbiter.io.sink.bits === unlockArbiter.io.sink.bits) {
    registerFile(lockArbiter.io.sink.bits) := true.B
    lockSuccess := true.B
    unlockSuccess := true.B
    lockArbiter.io.sink.ready := true.B
    unlockArbiter.io.sink.ready := true.B
  }.otherwise{
      when(lockArbiter.io.sink.valid && !registerFile(lockArbiter.io.sink.bits)) {
        registerFile(lockArbiter.io.sink.bits) := true.B
        lockSuccess := true.B
        lockArbiter.io.sink.ready := true.B
      }.otherwise {
        lockSuccess := false.B
        lockArbiter.io.sink.ready := true.B
      }

      when(unlockArbiter.io.sink.valid) {
        registerFile(unlockArbiter.io.sink.bits) := false.B
        unlockSuccess := true.B
        unlockArbiter.io.sink.ready := true.B
      }
  }
}


import _root_.circt.stage.ChiselStage
object AtomicGrantEmitter extends App {
    
    ChiselStage.emitSystemVerilogFile(
      {
        val module = new AtomicGrant(64, 5, 7)
        module
      },
      Array(f"--target-dir=output"),
      Array("--disable-all-randomization")
    )

}