package Util

import Descriptors._
import Util.HardCilkEmitterUtil.writeFile
import java.nio.file.{Files, Paths, StandardCopyOption}

object VitisFlowGenerator {

  def generate(
      descriptor: FullSysGenDescriptor,
      outputDir: String,
      reduceAxi: Int,
      rtlDir: String
  ): Unit = {
    Files.createDirectories(Paths.get(s"$outputDir/scripts"))
    Files.createDirectories(Paths.get(s"$outputDir/src/cfg"))
    Files.createDirectories(Paths.get(s"$outputDir/src/xml"))
    Files.createDirectories(Paths.get(s"$outputDir/src/IP"))

    // Copy all flat files from the RTL output directory into src/IP/
    val rtlPath = Paths.get(rtlDir)
    if (Files.exists(rtlPath)) {
      Files.list(rtlPath)
        .filter(p => Files.isRegularFile(p))
        .forEach(src =>
          Files.copy(src, Paths.get(s"$outputDir/src/IP/${src.getFileName}"),
            StandardCopyOption.REPLACE_EXISTING)
        )
      // Vitis expects active-low reset_n; patch the top-level module in-place
      patchVitisReset(descriptor, outputDir)
    } else {
      println(s"[VitisFlowGenerator] WARNING: RTL directory not found at $rtlDir — src/IP will be empty")
    }

    writeFile(s"$outputDir/Makefile",         makefile(descriptor, reduceAxi))
    writeFile(s"$outputDir/scripts/gen_xo.tcl",          genXoTcl(descriptor))
    writeFile(s"$outputDir/scripts/package_kernel.tcl",  packageKernelTcl(descriptor, reduceAxi))
    writeFile(s"$outputDir/scripts/clear_drc_errors.tcl", clearDrcTcl(descriptor))
    writeFile(s"$outputDir/src/cfg/conn_u55c.cfg",       connCfg(descriptor, reduceAxi))
    writeFile(s"$outputDir/src/cfg/conn_u55c_emu.cfg",   connCfgEmu(descriptor, reduceAxi))
    writeFile(s"$outputDir/src/xml/user_0.xml",          userXml(descriptor, reduceAxi))
  }

  // ─── Makefile ────────────────────────────────────────────────────────────────

  private def makefile(d: FullSysGenDescriptor, reduceAxi: Int): String = {
    val name = d.name
    s"""# ============================================================
# Vitis single-FPGA xclbin build — generated by HardCilk
# ============================================================

MK_PATH  := $$(abspath $$(lastword $$(MAKEFILE_LIST)))
CUR_DIR  := $$(patsubst %/,%,$$(dir $$(MK_PATH)))

TARGET   ?= hw
PLATFORM ?= xilinx_u55c_gen3x16_xdma_3_202210_1
DEVICE   ?= /opt/xilinx/platforms/xilinx_u55c_gen3x16_xdma_3_202210_1/xilinx_u55c_gen3x16_xdma_3_202210_1.xpfm

PLATFORM_NAME := $$(strip $$(patsubst %.xpfm,%,$$(shell basename $$(PLATFORM))))
XPLATFORM     := $$(PLATFORM)

RUN_DIR          := .run
TEMP_DIR         := $$(RUN_DIR)/_x_temp.$$(TARGET).$$(PLATFORM_NAME)
BUILD_DIR        := build_dir.$$(TARGET).$$(PLATFORM_NAME)
BUILD_REPORT_DIR := $$(CUR_DIR)/reports/_build.$$(TARGET).$$(PLATFORM_NAME)

VPP    := v++
VIVADO := $$(XILINX_VIVADO)/bin/vivado

ifeq ($$(TARGET),hw)
SRC_CFG := $$(CUR_DIR)/src/cfg/conn_u55c.cfg
else
SRC_CFG := $$(CUR_DIR)/src/cfg/conn_u55c_emu.cfg
endif
TMP_CFG := $$(RUN_DIR)/conn_u55c.tmp.cfg

VPP_FLAGS   := -t $$(TARGET) --platform $$(XPLATFORM) --save-temps
VPP_LDFLAGS := --optimize 2 -R 2 --config $$(TMP_CFG)

# Vivado synthesis/impl job flags are only valid for hw (not hw_emu/sw_emu)
ifeq ($$(TARGET),hw)
VPP_VIVADO_JOBS := --vivado.synth.jobs 32 --vivado.impl.jobs 16
else
VPP_VIVADO_JOBS :=
endif

ifeq ($$(TARGET),hw_emu)
VPP_FLAGS += -g
endif

# Linkhooks waive combinatorial-loop DRC errors; only valid for hw (not hw_emu/sw_emu)
ifeq ($$(TARGET),hw)
VPP_LINKHOOKS := \\
    --linkhook.do_first vpl.impl.write_bitstream,scripts/clear_drc_errors.tcl \\
    --linkhook.do_last  vpl.impl.opt_design,scripts/clear_drc_errors.tcl
else
VPP_LINKHOOKS :=
endif

XO_DIR      := $$(RUN_DIR)/${name}/xo
KERNEL_OBJS := $$(XO_DIR)/${name}_0.xo
XCLBIN      := $$(BUILD_DIR)/${name}.xclbin

$$(TMP_CFG): $$(SRC_CFG)
\tmkdir -p $$(RUN_DIR)
\tcp $$< $$@

$$(XO_DIR)/${name}_0.xo: \\
\t\t./src/xml/user_0.xml         \\
\t\t./scripts/package_kernel.tcl \\
\t\t./scripts/gen_xo.tcl         \\
\t\t./src/IP/*.v
\tmkdir -p $$(XO_DIR) $$(RUN_DIR)
\t$$(VIVADO) -mode batch -source scripts/gen_xo.tcl \\
\t    -journal $$(RUN_DIR)/vivado_xo.jou -log $$(RUN_DIR)/vivado_xo.log \\
\t    -tclargs $$(XO_DIR)/${name}_0.xo ${name}_0 $$(TARGET) $$(DEVICE) 0

$$(XCLBIN): $$(KERNEL_OBJS) $$(TMP_CFG)
\tmkdir -p $$(BUILD_DIR) $$(BUILD_REPORT_DIR)
\t$$(VPP)                       \\
\t    $$(VPP_VIVADO_JOBS)        \\
\t    -l                        \\
\t    $$(VPP_FLAGS)              \\
\t    $$(VPP_LINKHOOKS)          \\
\t    --temp_dir   $$(TEMP_DIR)                              \\
\t    --report_dir $$(BUILD_REPORT_DIR)/${name}              \\
\t    $$(VPP_LDFLAGS)            \\
\t    -o $$@ $$(KERNEL_OBJS)

.PHONY: all clean cleanall
all: $$(XCLBIN)

clean:
\t-rm -rf build_dir.* .run reports
\t-rm -rf packaged_kernel_* tmp_kernel_pack_*
\t-rm -rf ${name} conn_u55c.tmp.cfg
\t-rm -f *.log *.jou xcd.log
\t-rm -rf .ipcache .Xil

cleanall: clean
"""
  }

  // ─── gen_xo.tcl ──────────────────────────────────────────────────────────────

  private def genXoTcl(d: FullSysGenDescriptor): String =
    s"""# generated by HardCilk — single-FPGA Vitis flow

if { $$::argc != 5 } {
    puts "ERROR: Program \\"$$::argv0\\" requires 5 arguments!"
    puts "Usage: $$::argv0 <xoname> <krnl_name> <target> <device> <index>"
    exit
}

set xoname    [lindex $$::argv 0]
set krnl_name [lindex $$::argv 1]
set target    [lindex $$::argv 2]
set device    [lindex $$::argv 3]
set index     [lindex $$::argv 4]

set suffix "$${krnl_name}_$${target}_$${device}"

source -notrace ./scripts/package_kernel.tcl

if {[file exists "$${xoname}"]} {
    file delete -force "$${xoname}"
}

package_xo -xo_path $${xoname} -kernel_name $${krnl_name} \\
    -ip_directory .run/packaged_kernel_$${suffix} \\
    -kernel_xml ./src/xml/user_$${index}.xml
"""

  // ─── package_kernel.tcl ──────────────────────────────────────────────────────
  // Generates a BD-wrapper around the user kernel that inserts two AXI register-
  // slice stages (rs0/rs1) on every m_axi_* master and one stage on the AXI-Lite
  // management slave.  A floorplan XDC pins rs0/kernel to SLR1 and rs1 to SLR0,
  // helping Vivado meet timing across the SLR boundary to HBM.

  private def packageKernelTcl(d: FullSysGenDescriptor, reduceAxi: Int): String = {
    val rtlTop    = d.name
    val axiAw     = d.widthAXIAddress
    val axiDw     = 256
    val nPorts    = reduceAxi
    val clkFreqHz = d.targetFrequency.toLong * 1_000_000L
    val mFPGA     = d.mFPGASynth || d.mFPGASimulation

    // mFPGA stream ports are wired directly through the BD (no register slice needed).
    val streamBdPorts = if (mFPGA) """
# ── mFPGA AXI-stream ports (direct pass-through, no reg slice) ───────────────
create_bd_intf_port -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 m_axis_mFPGA
create_bd_intf_port -mode Slave  -vlnv xilinx.com:interface:axis_rtl:1.0 s_axis_mFPGA
connect_bd_intf_net [get_bd_intf_pins user_kernel/m_axis_mFPGA] [get_bd_intf_ports m_axis_mFPGA]
connect_bd_intf_net [get_bd_intf_pins user_kernel/s_axis_mFPGA] [get_bd_intf_ports s_axis_mFPGA]
""" else ""

    // Bus-interface clock associations for mFPGA stream ports.
    val streamBusAssoc = if (mFPGA) """
ipx::associate_bus_interfaces -busif m_axis_mFPGA -clock $clk $core
ipx::associate_bus_interfaces -busif s_axis_mFPGA -clock $clk $core""" else ""

    s"""# generated by HardCilk — single-FPGA Vitis flow
# Vivado 2022.1 clean timing-oriented version:
#   user_kernel -> rs0_m_axi_* -> rs1_m_axi_* -> BD AXI boundary
#   rs0 constrained with kernel/SLR1
#   rs1 constrained to SLR0/shell side
#   no fragile LAGUNA coordinates
#   no CONTAIN_ROUTING

set path_to_hdl         "./src/IP"
set path_to_packaged    ".run/packaged_kernel_$${suffix}"
set path_to_tmp_project ".run/tmp_kernel_pack_$${suffix}"

# ── (1) Create project and add RTL sources ───────────────────────────────────
create_project -force kernel_pack $$path_to_tmp_project
add_files -norecurse [glob $$path_to_hdl/*.v $$path_to_hdl/*.sv]
update_compile_order -fileset sources_1
update_compile_order -fileset sim_1

foreach tcl_file [glob -nocomplain $$path_to_hdl/*.tcl] {
    source $$tcl_file
}

# ── (2) Parameters ───────────────────────────────────────────────────────────
set rtl_top      "$rtlTop"
set axi_aw       $axiAw
set axi_dw       $axiDw
set n_ports      $nPorts
set clk_freq_hz  $clkFreqHz

# ── (3) Build BD wrapper ─────────────────────────────────────────────────────
create_bd_design "kernel_wrap"
current_bd_design [get_bd_designs kernel_wrap]

create_bd_cell -type module -reference $$rtl_top user_kernel

set clk_p [create_bd_port -dir I -type clk -freq_hz $$clk_freq_hz clock]
set rst_p [create_bd_port -dir I -type rst reset_n]
set_property CONFIG.POLARITY ACTIVE_LOW $$rst_p

connect_bd_net [get_bd_ports clock]   [get_bd_pins user_kernel/clock]
connect_bd_net [get_bd_ports reset_n] [get_bd_pins user_kernel/reset_n]

set rs_vlnv [lindex [lsort [get_ipdefs xilinx.com:ip:axi_register_slice:*]] end]

proc config_full_axi_slice {cell axi_aw axi_dw} {
    set_property -dict [list \\
        CONFIG.ADDR_WIDTH $$axi_aw \\
        CONFIG.DATA_WIDTH $$axi_dw \\
        CONFIG.REG_AW     {7} \\
        CONFIG.REG_AR     {7} \\
        CONFIG.REG_W      {7} \\
        CONFIG.REG_R      {7} \\
        CONFIG.REG_B      {7} \\
    ] $$cell
}

# ── (3a) HBM AXI master ports ────────────────────────────────────────────────
for {set i 0} {$$i < $$n_ports} {incr i} {
    set pid  [format "%02d" $$i]
    set port "m_axi_$${pid}"

    set rs0 "rs0_$${port}"
    set rs1 "rs1_$${port}"

    create_bd_cell -type ip -vlnv $$rs_vlnv $$rs0
    create_bd_cell -type ip -vlnv $$rs_vlnv $$rs1

    config_full_axi_slice [get_bd_cells $$rs0] $$axi_aw $$axi_dw
    config_full_axi_slice [get_bd_cells $$rs1] $$axi_aw $$axi_dw

    connect_bd_net [get_bd_ports clock]   [get_bd_pins $${rs0}/aclk]
    connect_bd_net [get_bd_ports reset_n] [get_bd_pins $${rs0}/aresetn]
    connect_bd_net [get_bd_ports clock]   [get_bd_pins $${rs1}/aclk]
    connect_bd_net [get_bd_ports reset_n] [get_bd_pins $${rs1}/aresetn]

    connect_bd_intf_net \\
        [get_bd_intf_pins user_kernel/$${port}] \\
        [get_bd_intf_pins $${rs0}/S_AXI]

    connect_bd_intf_net \\
        [get_bd_intf_pins $${rs0}/M_AXI] \\
        [get_bd_intf_pins $${rs1}/S_AXI]

    create_bd_intf_port -mode Master \\
        -vlnv xilinx.com:interface:aximm_rtl:1.0 $${port}

    set_property -dict [list \\
        CONFIG.PROTOCOL   {AXI4} \\
        CONFIG.DATA_WIDTH $$axi_dw \\
        CONFIG.ADDR_WIDTH $$axi_aw \\
    ] [get_bd_intf_ports $${port}]

    connect_bd_intf_net \\
        [get_bd_intf_pins $${rs1}/M_AXI] \\
        [get_bd_intf_ports $${port}]
}

# ── (3b) AXI-Lite management slave with reg slice ────────────────────────────
create_bd_intf_port -mode Slave \\
    -vlnv xilinx.com:interface:aximm_rtl:1.0 s_axil_mgmt_hardcilk

set_property -dict [list \\
    CONFIG.PROTOCOL   {AXI4LITE} \\
    CONFIG.ADDR_WIDTH {12} \\
    CONFIG.DATA_WIDTH {32} \\
] [get_bd_intf_ports s_axil_mgmt_hardcilk]

create_bd_cell -type ip -vlnv $$rs_vlnv rs_s_axil_mgmt

set_property -dict [list \\
    CONFIG.PROTOCOL   {AXI4LITE} \\
    CONFIG.ADDR_WIDTH {12} \\
    CONFIG.DATA_WIDTH {32} \\
    CONFIG.REG_AW     {7} \\
    CONFIG.REG_AR     {7} \\
    CONFIG.REG_W      {7} \\
    CONFIG.REG_R      {7} \\
    CONFIG.REG_B      {7} \\
] [get_bd_cells rs_s_axil_mgmt]

connect_bd_net [get_bd_ports clock]   [get_bd_pins rs_s_axil_mgmt/aclk]
connect_bd_net [get_bd_ports reset_n] [get_bd_pins rs_s_axil_mgmt/aresetn]

connect_bd_intf_net \\
    [get_bd_intf_ports s_axil_mgmt_hardcilk] \\
    [get_bd_intf_pins rs_s_axil_mgmt/S_AXI]

connect_bd_intf_net \\
    [get_bd_intf_pins rs_s_axil_mgmt/M_AXI] \\
    [get_bd_intf_pins user_kernel/s_axil_mgmt_hardcilk]
$streamBdPorts
assign_bd_address
validate_bd_design
save_bd_design

# ── (4) Wrapper ──────────────────────────────────────────────────────────────
make_wrapper -files [get_files kernel_wrap.bd] -top -import
set_property top kernel_wrap_wrapper [current_fileset]
update_compile_order -fileset sources_1

# ── (5) Floorplan XDC ────────────────────────────────────────────────────────
set xdc_file "$${path_to_tmp_project}/timing_floorplan.xdc"
set fh [open $$xdc_file w]

puts $$fh {
# User kernel: prefer SLR1, but allow escape if timing needs it.
create_pblock pblock_user_kernel
resize_pblock [get_pblocks pblock_user_kernel] -add SLR1
add_cells_to_pblock \\
    [get_pblocks pblock_user_kernel] \\
    [get_cells -hierarchical -filter {NAME =~ */kernel_wrap_i/user_kernel/*}]
set_property IS_SOFT TRUE [get_pblocks pblock_user_kernel]

# First AXI slice: near user kernel side (same SLR).
create_pblock pblock_axi_rs0
resize_pblock [get_pblocks pblock_axi_rs0] -add SLR1
add_cells_to_pblock \\
    [get_pblocks pblock_axi_rs0] \\
    [get_cells -hierarchical -filter {NAME =~ */kernel_wrap_i/rs0_m_axi_*}]
set_property IS_SOFT FALSE [get_pblocks pblock_axi_rs0]

# Second AXI slice: near shell/HBM side.
create_pblock pblock_axi_rs1
resize_pblock [get_pblocks pblock_axi_rs1] -add SLR0
add_cells_to_pblock \\
    [get_pblocks pblock_axi_rs1] \\
    [get_cells -hierarchical -filter {NAME =~ */kernel_wrap_i/rs1_m_axi_*}]
set_property IS_SOFT FALSE [get_pblocks pblock_axi_rs1]

# AXI-Lite slice: flexible, but stay close to shell/control side.
create_pblock pblock_axilite_slice
resize_pblock [get_pblocks pblock_axilite_slice] -add SLR1
add_cells_to_pblock \\
    [get_pblocks pblock_axilite_slice] \\
    [get_cells -hierarchical -filter {NAME =~ */kernel_wrap_i/rs_s_axil_mgmt*}]
set_property IS_SOFT TRUE [get_pblocks pblock_axilite_slice]
}

close $$fh

add_files -fileset constrs_1 -norecurse $$xdc_file
set_property USED_IN          {implementation} [get_files $$xdc_file]
set_property PROCESSING_ORDER LATE             [get_files $$xdc_file]

# ── (6) Package IP ───────────────────────────────────────────────────────────
ipx::package_project -root_dir $$path_to_packaged -vendor xilinx.com -library RTLKernel \\
    -taxonomy /KernelIP -import_files -set_current false

ipx::unload_core $$path_to_packaged/component.xml

ipx::edit_ip_in_project -upgrade true -name tmp_edit_project \\
    -directory $$path_to_packaged $$path_to_packaged/component.xml

set_property core_revision 2 [ipx::current_core]

foreach up [ipx::get_user_parameters] {
    ipx::remove_user_parameter [get_property NAME $$up] [ipx::current_core]
}

set_property sdx_kernel      true [ipx::current_core]
set_property sdx_kernel_type rtl  [ipx::current_core]
ipx::create_xgui_files [ipx::current_core]

set core [ipx::current_core]
set clk  clock

foreach busif [ipx::get_bus_interfaces -of_objects $$core] {
    set ifname [get_property NAME $$busif]

    if {[string match "m_axi_*" $$ifname]} {
        ipx::associate_bus_interfaces -busif $$ifname -clock $$clk $$core
    }

    if {$$ifname eq "s_axil_mgmt_hardcilk"} {
        ipx::associate_bus_interfaces -busif $$ifname -clock $$clk $$core
    }
}
$streamBusAssoc
ipx::associate_bus_interfaces -clock clock -reset reset_n [ipx::current_core]

set_property xpm_libraries {XPM_CDC XPM_MEMORY XPM_FIFO} [ipx::current_core]
set_property supported_families {} [ipx::current_core]
set_property auto_family_support_level level_2 [ipx::current_core]

ipx::update_checksums [ipx::current_core]
ipx::save_core [ipx::current_core]

close_project -delete
"""
  }

  // ─── clear_drc_errors.tcl ────────────────────────────────────────────────────

  private def clearDrcTcl(d: FullSysGenDescriptor): String = {
    val totalPEs = d.taskDescriptors.map(_.numProcessingElements).sum
    s"""# generated by HardCilk — waive combinatorial-loop DRC for PE AXI masters

proc safe_set_property {property value net_pattern} {
    set nets [get_nets -quiet $$net_pattern]
    if {[llength $$nets] == 0} {
        puts "WARNING: net not found, skipping: $$net_pattern"
    } else {
        set_property $$property $$value $$nets
    }
}

set base    "level0_i/ulp/${d.name}_0/inst"
set pe_path "pe/gmem_m_axi_U/bus_read/rreq_burst_conv/burst_interleave/req_buffer"

set nets_to_waive {
    could_multi_bursts.rem_req_valid_reg
    DI[0]
}

for {set i 0} {$$i < $totalPEs} {incr i} {
    foreach net $$nets_to_waive {
        safe_set_property ALLOW_COMBINATORIAL_LOOPS TRUE \\
            "$${base}/peMap_1_2_$${i}/$${pe_path}/$${net}"
    }
}
"""
  }

  // ─── conn_u55c.cfg ───────────────────────────────────────────────────────────

  private def connCfg(d: FullSysGenDescriptor, reduceAxi: Int): String = {
    val name   = d.name
    val freqHz = d.targetFrequency.toLong * 1_000_000L
    val spLines = (0 until reduceAxi)
      .map(i => f"sp=${name}_0.m_axi_$i%02d:HBM[0:31]")
      .mkString("\n")

    s"""[connectivity]
nk=${name}_0:1:${name}_0

$spLines

[clock]
freqHz=${freqHz}:${name}_0.clock

[vivado]
prop=run.impl_1.STEPS.PLACE_DESIGN.ARGS.DIRECTIVE=ExtraNetDelay_high
prop=run.impl_1.STEPS.PHYS_OPT_DESIGN.IS_ENABLED=true
prop=run.impl_1.STEPS.PHYS_OPT_DESIGN.ARGS.DIRECTIVE=AggressiveExplore
prop=run.impl_1.STEPS.ROUTE_DESIGN.ARGS.DIRECTIVE=AggressiveExplore
prop=run.impl_1.STEPS.POST_ROUTE_PHYS_OPT_DESIGN.IS_ENABLED=true
prop=run.impl_1.STEPS.POST_ROUTE_PHYS_OPT_DESIGN.ARGS.DIRECTIVE=AggressiveExplore

[advanced]
param=compiler.worstNegativeSlack=-1


"""
  }

  // ─── conn_u55c_emu.cfg ───────────────────────────────────────────────────────
  // Emulation config: no [clock] or [vivado] sections — v++ ignores them in
  // hw_emu/sw_emu and they can cause errors in some Vitis versions.

  private def connCfgEmu(d: FullSysGenDescriptor, reduceAxi: Int): String = {
    val name   = d.name
    val spLines = (0 until reduceAxi)
      .map(i => f"sp=${name}_0.m_axi_$i%02d:HBM[0:31]")
      .mkString("\n")

    s"""[connectivity]
nk=${name}_0:1:${name}_0

$spLines
"""
  }

  // ─── user_0.xml ──────────────────────────────────────────────────────────────

  private def userXml(d: FullSysGenDescriptor, reduceAxi: Int): String = {
    val name    = d.name
    val range   = f"0x${(1L << d.widthAXIAddress) - 1}%X"
    val mFPGA   = d.mFPGASynth || d.mFPGASimulation

    val sb = new StringBuilder
    sb.append("""<?xml version="1.0" encoding="UTF-8"?>""").append("\n")
    sb.append(s"""<root versionMajor="1" versionMinor="9">\n""")
    sb.append(s"""  <kernel name="${name}_0" language="ip" type="user_managed" """)
    sb.append(s"""vlnv="epfl.ch:hardcilk:${name}:1.0" attributes="" """)
    sb.append(s"""preferredWorkGroupSizeMultiple="0" workGroupSize="1" hwControlProtocol="user_managed">\n""")

    // ── ports ──
    sb.append("    <ports>\n")
    for (i <- 0 until reduceAxi) {
      sb.append(f"""      <port name="m_axi_$i%02d" mode="master" range="$range" dataWidth="256" portType="addressable" base="0x0"/>\n""")
    }
    sb.append("""      <port name="s_axil_mgmt_hardcilk" mode="slave" range="0x1000" dataWidth="32" portType="addressable" base="0x0"/>""").append("\n")
    if (mFPGA) {
      sb.append("""      <port name="m_axis_mFPGA" mode="write_only" dataWidth="512" portType="stream"/>""").append("\n")
      sb.append("""      <port name="s_axis_mFPGA" mode="read_only"  dataWidth="512" portType="stream"/>""").append("\n")
    }
    sb.append("    </ports>\n")

    // ── args ──
    sb.append("    <args>\n")
    var id = 0

    def axilArg(argName: String, offset: Long): Unit = {
      sb.append(f"""      <arg name="$argName" addressQualifier="0" id="$id" port="s_axil_mgmt_hardcilk" size="0x8" offset="0x$offset%X" hostOffset="0x0" hostSize="0x8" type="ap_uint&lt;64>"/>\n""")
      id += 1
    }

    val schedulerRegs   = Seq("rPause", "rAddr", "maxLen", "fifoTailReg", "fifoHeadReg", "procInterrupt", "currLen")
    val allocatorRegs   = Seq("rPause", "rAddr", "availableSize")

    for (task <- d.taskDescriptors) {
      val tName = task.name

      for ((base, idx) <- task.mgmtBaseAddresses.schedulerServersBaseAddresses.zipWithIndex) {
        for ((reg, off) <- schedulerRegs.zipWithIndex)
          axilArg(s"${tName}_sched_${idx}_$reg", base.toLong + off * 8)
      }

      for ((base, idx) <- task.mgmtBaseAddresses.allocationServersBaseAddresses.zipWithIndex) {
        for ((reg, off) <- allocatorRegs.zipWithIndex)
          axilArg(s"${tName}_alloc_${idx}_$reg", base.toLong + off * 8)
      }

      for ((base, idx) <- task.mgmtBaseAddresses.memoryAllocatorServersBaseAddresses.zipWithIndex) {
        for ((reg, off) <- schedulerRegs.zipWithIndex)
          axilArg(s"${tName}_memAlloc_${idx}_$reg", base.toLong + off * 8)
      }
    }

    // mFPGA management block
    if (mFPGA) {
      val mfpgaBase = d.getMfpgaBaseAddress().toLong
      val mfpgaRegs = Seq("fpgaIndex", "fpgaCount", "tasksToMove") ++
        (0 to 13).map(i => s"dummy$i")
      for ((reg, off) <- mfpgaRegs.zipWithIndex)
        axilArg(reg, mfpgaBase + off * 8)
    }

    // memory pointer args — start at first 0x100-aligned address ≥ max(0x200, mFPGA base)
    val rawBase     = d.getMfpgaBaseAddress().toLong
    val mfpgaEnd    = if (mFPGA) rawBase + 17 * 8 else rawBase
    val memPtrBase  = math.max(0x200L, (mfpgaEnd + 0xFF) & ~0xFFL)

    for (i <- 0 until reduceAxi) {
      val offset = memPtrBase + i * 8
      sb.append(f"""      <arg name="mem_$i" addressQualifier="1" id="$id" port="m_axi_$i%02d" size="0x8" offset="0x$offset%X" hostOffset="0x0" hostSize="0x8" type="void*"/>\n""")
      id += 1
    }

    if (mFPGA) {
      sb.append(s"""      <arg name="m_axis_mFPGA" addressQualifier="4" id="$id" port="m_axis_mFPGA" size="0x0" offset="0x0" hostOffset="0x0" hostSize="0x0" memSize="0" type="stream&lt;ap_axiu&lt;512,0,0,4>>&amp;"/>\n""")
      id += 1
      sb.append(s"""      <arg name="s_axis_mFPGA" addressQualifier="4" id="$id" port="s_axis_mFPGA" size="0x0" offset="0x0" hostOffset="0x0" hostSize="0x0" memSize="0" type="stream&lt;ap_axiu&lt;512,0,0,4>>&amp;"/>\n""")
      id += 1
    }

    sb.append("    </args>\n")
    sb.append("  </kernel>\n")
    sb.append("</root>\n")
    sb.toString()
  }

  // ─── Vitis reset patch ───────────────────────────────────────────────────────
  // Chisel emits active-high 'reset'; Vitis requires active-low 'reset_n'.
  // Operates only on the last (top-level) module declaration in the file.

  private def patchVitisReset(d: FullSysGenDescriptor, outputDir: String): Unit = {
    val vFile = Paths.get(s"$outputDir/src/IP/${d.name}.v")
    if (!Files.exists(vFile)) return
    var content = new String(Files.readAllBytes(vFile), "UTF-8")
    val modIdx = content.lastIndexOf(s"module ${d.name} (")
    if (modIdx < 0) return
    val before = content.substring(0, modIdx)
    var after  = content.substring(modIdx)
    // 1. Rename 'reset' in the port-name list (old-style Verilog-95 header)
    after = after.replaceFirst("\treset,", "\treset_n,")
    after = after.replaceFirst("\treset\n", "\treset_n\n") // last port, no comma
    // 2. Rename port type declaration and insert inversion wire immediately after
    after = after.replaceFirst(
      "\tinput reset;",
      "\tinput reset_n;\n\twire reset = ~reset_n;"
    )
    Files.write(vFile, (before + after).getBytes("UTF-8"))
    println(s"[VitisFlowGenerator] Patched reset→reset_n in src/IP/${d.name}.v")
  }
}
