-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity memReader is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0);
    taskIn_TDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    argOut_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    argDataOut_TDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    taskIn_TVALID : IN STD_LOGIC;
    taskIn_TREADY : OUT STD_LOGIC;
    argDataOut_TVALID : OUT STD_LOGIC;
    argDataOut_TREADY : IN STD_LOGIC;
    argOut_TVALID : OUT STD_LOGIC;
    argOut_TREADY : IN STD_LOGIC );
end;


architecture behav of memReader is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "memReader_memReader,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu55c-fsvh2892-2L-e,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.433090,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=1817,HLS_SYN_LUT=2335,HLS_VERSION=2024_1}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal mem : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_AWREADY : STD_LOGIC;
    signal gmem_WREADY : STD_LOGIC;
    signal gmem_ARREADY : STD_LOGIC;
    signal gmem_RVALID : STD_LOGIC;
    signal gmem_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_RLAST : STD_LOGIC;
    signal gmem_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_RFIFONUM : STD_LOGIC_VECTOR (9 downto 0);
    signal gmem_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_BVALID : STD_LOGIC;
    signal memReaderLoad_U0_ap_start : STD_LOGIC;
    signal memReaderLoad_U0_start_full_n : STD_LOGIC;
    signal memReaderLoad_U0_ap_done : STD_LOGIC;
    signal memReaderLoad_U0_ap_continue : STD_LOGIC;
    signal memReaderLoad_U0_ap_idle : STD_LOGIC;
    signal memReaderLoad_U0_ap_ready : STD_LOGIC;
    signal memReaderLoad_U0_start_out : STD_LOGIC;
    signal memReaderLoad_U0_start_write : STD_LOGIC;
    signal memReaderLoad_U0_m_axi_gmem_AWVALID : STD_LOGIC;
    signal memReaderLoad_U0_m_axi_gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_WVALID : STD_LOGIC;
    signal memReaderLoad_U0_m_axi_gmem_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_WLAST : STD_LOGIC;
    signal memReaderLoad_U0_m_axi_gmem_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_ARVALID : STD_LOGIC;
    signal memReaderLoad_U0_m_axi_gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal memReaderLoad_U0_m_axi_gmem_RREADY : STD_LOGIC;
    signal memReaderLoad_U0_m_axi_gmem_BREADY : STD_LOGIC;
    signal memReaderLoad_U0_taskIn_TREADY : STD_LOGIC;
    signal memReaderLoad_U0_allowTokens_din : STD_LOGIC_VECTOR (63 downto 0);
    signal memReaderLoad_U0_allowTokens_write : STD_LOGIC;
    signal memReaderLoad_U0_writePackages_din : STD_LOGIC_VECTOR (255 downto 0);
    signal memReaderLoad_U0_writePackages_write : STD_LOGIC;
    signal memReaderForwardPackage_U0_ap_start : STD_LOGIC;
    signal memReaderForwardPackage_U0_ap_done : STD_LOGIC;
    signal memReaderForwardPackage_U0_ap_continue : STD_LOGIC;
    signal memReaderForwardPackage_U0_ap_idle : STD_LOGIC;
    signal memReaderForwardPackage_U0_ap_ready : STD_LOGIC;
    signal memReaderForwardPackage_U0_writePackages_read : STD_LOGIC;
    signal memReaderForwardPackage_U0_argDataOut_TDATA : STD_LOGIC_VECTOR (255 downto 0);
    signal memReaderForwardPackage_U0_argDataOut_TVALID : STD_LOGIC;
    signal memReaderForwardPackage_U0_pkgDone_din : STD_LOGIC_VECTOR (0 downto 0);
    signal memReaderForwardPackage_U0_pkgDone_write : STD_LOGIC;
    signal memReaderForwardAllow_U0_ap_start : STD_LOGIC;
    signal memReaderForwardAllow_U0_ap_done : STD_LOGIC;
    signal memReaderForwardAllow_U0_ap_continue : STD_LOGIC;
    signal memReaderForwardAllow_U0_ap_idle : STD_LOGIC;
    signal memReaderForwardAllow_U0_ap_ready : STD_LOGIC;
    signal memReaderForwardAllow_U0_allowTokens_read : STD_LOGIC;
    signal memReaderForwardAllow_U0_pkgDone_read : STD_LOGIC;
    signal memReaderForwardAllow_U0_argOut_TDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal memReaderForwardAllow_U0_argOut_TVALID : STD_LOGIC;
    signal allowTokens_full_n : STD_LOGIC;
    signal allowTokens_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal allowTokens_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal allowTokens_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal allowTokens_empty_n : STD_LOGIC;
    signal writePackages_full_n : STD_LOGIC;
    signal writePackages_dout : STD_LOGIC_VECTOR (255 downto 0);
    signal writePackages_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal writePackages_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal writePackages_empty_n : STD_LOGIC;
    signal pkgDone_full_n : STD_LOGIC;
    signal pkgDone_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal pkgDone_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal pkgDone_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal pkgDone_empty_n : STD_LOGIC;
    signal start_for_memReaderForwardPackage_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_memReaderForwardPackage_U0_full_n : STD_LOGIC;
    signal start_for_memReaderForwardPackage_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_memReaderForwardPackage_U0_empty_n : STD_LOGIC;
    signal start_for_memReaderForwardAllow_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_memReaderForwardAllow_U0_full_n : STD_LOGIC;
    signal start_for_memReaderForwardAllow_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_memReaderForwardAllow_U0_empty_n : STD_LOGIC;

    component memReader_memReaderLoad IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        m_axi_gmem_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_AWREADY : IN STD_LOGIC;
        m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WVALID : OUT STD_LOGIC;
        m_axi_gmem_WREADY : IN STD_LOGIC;
        m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_WLAST : OUT STD_LOGIC;
        m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_ARREADY : IN STD_LOGIC;
        m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RVALID : IN STD_LOGIC;
        m_axi_gmem_RREADY : OUT STD_LOGIC;
        m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_RLAST : IN STD_LOGIC;
        m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
        m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BVALID : IN STD_LOGIC;
        m_axi_gmem_BREADY : OUT STD_LOGIC;
        m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        mem : IN STD_LOGIC_VECTOR (63 downto 0);
        taskIn_TDATA : IN STD_LOGIC_VECTOR (255 downto 0);
        taskIn_TVALID : IN STD_LOGIC;
        taskIn_TREADY : OUT STD_LOGIC;
        allowTokens_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        allowTokens_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        allowTokens_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        allowTokens_full_n : IN STD_LOGIC;
        allowTokens_write : OUT STD_LOGIC;
        writePackages_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        writePackages_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        writePackages_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        writePackages_full_n : IN STD_LOGIC;
        writePackages_write : OUT STD_LOGIC );
    end component;


    component memReader_memReaderForwardPackage IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        writePackages_dout : IN STD_LOGIC_VECTOR (255 downto 0);
        writePackages_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        writePackages_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        writePackages_empty_n : IN STD_LOGIC;
        writePackages_read : OUT STD_LOGIC;
        argDataOut_TDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
        argDataOut_TVALID : OUT STD_LOGIC;
        argDataOut_TREADY : IN STD_LOGIC;
        pkgDone_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        pkgDone_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        pkgDone_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        pkgDone_full_n : IN STD_LOGIC;
        pkgDone_write : OUT STD_LOGIC );
    end component;


    component memReader_memReaderForwardAllow IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        allowTokens_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        allowTokens_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        allowTokens_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        allowTokens_empty_n : IN STD_LOGIC;
        allowTokens_read : OUT STD_LOGIC;
        pkgDone_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        pkgDone_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        pkgDone_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        pkgDone_empty_n : IN STD_LOGIC;
        pkgDone_read : OUT STD_LOGIC;
        argOut_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        argOut_TVALID : OUT STD_LOGIC;
        argOut_TREADY : IN STD_LOGIC );
    end component;


    component memReader_fifo_w64_d16_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component memReader_fifo_w256_d16_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (255 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (255 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component memReader_fifo_w1_d16_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component memReader_start_for_memReaderForwardPackage_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component memReader_start_for_memReaderForwardAllow_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component memReader_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        mem : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component memReader_gmem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (9 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component memReader_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        mem => mem);

    gmem_m_axi_U : component memReader_gmem_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 70,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 10,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 32,
        NUM_WRITE_OUTSTANDING => 0)
    port map (
        AWVALID => m_axi_gmem_AWVALID,
        AWREADY => m_axi_gmem_AWREADY,
        AWADDR => m_axi_gmem_AWADDR,
        AWID => m_axi_gmem_AWID,
        AWLEN => m_axi_gmem_AWLEN,
        AWSIZE => m_axi_gmem_AWSIZE,
        AWBURST => m_axi_gmem_AWBURST,
        AWLOCK => m_axi_gmem_AWLOCK,
        AWCACHE => m_axi_gmem_AWCACHE,
        AWPROT => m_axi_gmem_AWPROT,
        AWQOS => m_axi_gmem_AWQOS,
        AWREGION => m_axi_gmem_AWREGION,
        AWUSER => m_axi_gmem_AWUSER,
        WVALID => m_axi_gmem_WVALID,
        WREADY => m_axi_gmem_WREADY,
        WDATA => m_axi_gmem_WDATA,
        WSTRB => m_axi_gmem_WSTRB,
        WLAST => m_axi_gmem_WLAST,
        WID => m_axi_gmem_WID,
        WUSER => m_axi_gmem_WUSER,
        ARVALID => m_axi_gmem_ARVALID,
        ARREADY => m_axi_gmem_ARREADY,
        ARADDR => m_axi_gmem_ARADDR,
        ARID => m_axi_gmem_ARID,
        ARLEN => m_axi_gmem_ARLEN,
        ARSIZE => m_axi_gmem_ARSIZE,
        ARBURST => m_axi_gmem_ARBURST,
        ARLOCK => m_axi_gmem_ARLOCK,
        ARCACHE => m_axi_gmem_ARCACHE,
        ARPROT => m_axi_gmem_ARPROT,
        ARQOS => m_axi_gmem_ARQOS,
        ARREGION => m_axi_gmem_ARREGION,
        ARUSER => m_axi_gmem_ARUSER,
        RVALID => m_axi_gmem_RVALID,
        RREADY => m_axi_gmem_RREADY,
        RDATA => m_axi_gmem_RDATA,
        RLAST => m_axi_gmem_RLAST,
        RID => m_axi_gmem_RID,
        RUSER => m_axi_gmem_RUSER,
        RRESP => m_axi_gmem_RRESP,
        BVALID => m_axi_gmem_BVALID,
        BREADY => m_axi_gmem_BREADY,
        BRESP => m_axi_gmem_BRESP,
        BID => m_axi_gmem_BID,
        BUSER => m_axi_gmem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => memReaderLoad_U0_m_axi_gmem_ARVALID,
        I_CH0_ARREADY => gmem_ARREADY,
        I_CH0_ARADDR => memReaderLoad_U0_m_axi_gmem_ARADDR,
        I_CH0_ARLEN => memReaderLoad_U0_m_axi_gmem_ARLEN,
        I_CH0_RVALID => gmem_RVALID,
        I_CH0_RREADY => memReaderLoad_U0_m_axi_gmem_RREADY,
        I_CH0_RDATA => gmem_RDATA,
        I_CH0_RFIFONUM => gmem_RFIFONUM,
        I_CH0_AWVALID => ap_const_logic_0,
        I_CH0_AWREADY => gmem_AWREADY,
        I_CH0_AWADDR => ap_const_lv64_0,
        I_CH0_AWLEN => ap_const_lv32_0,
        I_CH0_WVALID => ap_const_logic_0,
        I_CH0_WREADY => gmem_WREADY,
        I_CH0_WDATA => ap_const_lv32_0,
        I_CH0_WSTRB => ap_const_lv4_0,
        I_CH0_BVALID => gmem_BVALID,
        I_CH0_BREADY => ap_const_logic_0);

    memReaderLoad_U0 : component memReader_memReaderLoad
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => memReaderLoad_U0_ap_start,
        start_full_n => memReaderLoad_U0_start_full_n,
        ap_done => memReaderLoad_U0_ap_done,
        ap_continue => memReaderLoad_U0_ap_continue,
        ap_idle => memReaderLoad_U0_ap_idle,
        ap_ready => memReaderLoad_U0_ap_ready,
        start_out => memReaderLoad_U0_start_out,
        start_write => memReaderLoad_U0_start_write,
        m_axi_gmem_AWVALID => memReaderLoad_U0_m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY => ap_const_logic_0,
        m_axi_gmem_AWADDR => memReaderLoad_U0_m_axi_gmem_AWADDR,
        m_axi_gmem_AWID => memReaderLoad_U0_m_axi_gmem_AWID,
        m_axi_gmem_AWLEN => memReaderLoad_U0_m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE => memReaderLoad_U0_m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST => memReaderLoad_U0_m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK => memReaderLoad_U0_m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE => memReaderLoad_U0_m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT => memReaderLoad_U0_m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS => memReaderLoad_U0_m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION => memReaderLoad_U0_m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER => memReaderLoad_U0_m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID => memReaderLoad_U0_m_axi_gmem_WVALID,
        m_axi_gmem_WREADY => ap_const_logic_0,
        m_axi_gmem_WDATA => memReaderLoad_U0_m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB => memReaderLoad_U0_m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST => memReaderLoad_U0_m_axi_gmem_WLAST,
        m_axi_gmem_WID => memReaderLoad_U0_m_axi_gmem_WID,
        m_axi_gmem_WUSER => memReaderLoad_U0_m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID => memReaderLoad_U0_m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY => gmem_ARREADY,
        m_axi_gmem_ARADDR => memReaderLoad_U0_m_axi_gmem_ARADDR,
        m_axi_gmem_ARID => memReaderLoad_U0_m_axi_gmem_ARID,
        m_axi_gmem_ARLEN => memReaderLoad_U0_m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE => memReaderLoad_U0_m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST => memReaderLoad_U0_m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK => memReaderLoad_U0_m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE => memReaderLoad_U0_m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT => memReaderLoad_U0_m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS => memReaderLoad_U0_m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION => memReaderLoad_U0_m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER => memReaderLoad_U0_m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID => gmem_RVALID,
        m_axi_gmem_RREADY => memReaderLoad_U0_m_axi_gmem_RREADY,
        m_axi_gmem_RDATA => gmem_RDATA,
        m_axi_gmem_RLAST => gmem_RLAST,
        m_axi_gmem_RID => gmem_RID,
        m_axi_gmem_RFIFONUM => gmem_RFIFONUM,
        m_axi_gmem_RUSER => gmem_RUSER,
        m_axi_gmem_RRESP => gmem_RRESP,
        m_axi_gmem_BVALID => ap_const_logic_0,
        m_axi_gmem_BREADY => memReaderLoad_U0_m_axi_gmem_BREADY,
        m_axi_gmem_BRESP => ap_const_lv2_0,
        m_axi_gmem_BID => ap_const_lv1_0,
        m_axi_gmem_BUSER => ap_const_lv1_0,
        mem => mem,
        taskIn_TDATA => taskIn_TDATA,
        taskIn_TVALID => taskIn_TVALID,
        taskIn_TREADY => memReaderLoad_U0_taskIn_TREADY,
        allowTokens_din => memReaderLoad_U0_allowTokens_din,
        allowTokens_num_data_valid => allowTokens_num_data_valid,
        allowTokens_fifo_cap => allowTokens_fifo_cap,
        allowTokens_full_n => allowTokens_full_n,
        allowTokens_write => memReaderLoad_U0_allowTokens_write,
        writePackages_din => memReaderLoad_U0_writePackages_din,
        writePackages_num_data_valid => writePackages_num_data_valid,
        writePackages_fifo_cap => writePackages_fifo_cap,
        writePackages_full_n => writePackages_full_n,
        writePackages_write => memReaderLoad_U0_writePackages_write);

    memReaderForwardPackage_U0 : component memReader_memReaderForwardPackage
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => memReaderForwardPackage_U0_ap_start,
        ap_done => memReaderForwardPackage_U0_ap_done,
        ap_continue => memReaderForwardPackage_U0_ap_continue,
        ap_idle => memReaderForwardPackage_U0_ap_idle,
        ap_ready => memReaderForwardPackage_U0_ap_ready,
        writePackages_dout => writePackages_dout,
        writePackages_num_data_valid => writePackages_num_data_valid,
        writePackages_fifo_cap => writePackages_fifo_cap,
        writePackages_empty_n => writePackages_empty_n,
        writePackages_read => memReaderForwardPackage_U0_writePackages_read,
        argDataOut_TDATA => memReaderForwardPackage_U0_argDataOut_TDATA,
        argDataOut_TVALID => memReaderForwardPackage_U0_argDataOut_TVALID,
        argDataOut_TREADY => argDataOut_TREADY,
        pkgDone_din => memReaderForwardPackage_U0_pkgDone_din,
        pkgDone_num_data_valid => pkgDone_num_data_valid,
        pkgDone_fifo_cap => pkgDone_fifo_cap,
        pkgDone_full_n => pkgDone_full_n,
        pkgDone_write => memReaderForwardPackage_U0_pkgDone_write);

    memReaderForwardAllow_U0 : component memReader_memReaderForwardAllow
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => memReaderForwardAllow_U0_ap_start,
        ap_done => memReaderForwardAllow_U0_ap_done,
        ap_continue => memReaderForwardAllow_U0_ap_continue,
        ap_idle => memReaderForwardAllow_U0_ap_idle,
        ap_ready => memReaderForwardAllow_U0_ap_ready,
        allowTokens_dout => allowTokens_dout,
        allowTokens_num_data_valid => allowTokens_num_data_valid,
        allowTokens_fifo_cap => allowTokens_fifo_cap,
        allowTokens_empty_n => allowTokens_empty_n,
        allowTokens_read => memReaderForwardAllow_U0_allowTokens_read,
        pkgDone_dout => pkgDone_dout,
        pkgDone_num_data_valid => pkgDone_num_data_valid,
        pkgDone_fifo_cap => pkgDone_fifo_cap,
        pkgDone_empty_n => pkgDone_empty_n,
        pkgDone_read => memReaderForwardAllow_U0_pkgDone_read,
        argOut_TDATA => memReaderForwardAllow_U0_argOut_TDATA,
        argOut_TVALID => memReaderForwardAllow_U0_argOut_TVALID,
        argOut_TREADY => argOut_TREADY);

    allowTokens_U : component memReader_fifo_w64_d16_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => memReaderLoad_U0_allowTokens_din,
        if_full_n => allowTokens_full_n,
        if_write => memReaderLoad_U0_allowTokens_write,
        if_dout => allowTokens_dout,
        if_num_data_valid => allowTokens_num_data_valid,
        if_fifo_cap => allowTokens_fifo_cap,
        if_empty_n => allowTokens_empty_n,
        if_read => memReaderForwardAllow_U0_allowTokens_read);

    writePackages_U : component memReader_fifo_w256_d16_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => memReaderLoad_U0_writePackages_din,
        if_full_n => writePackages_full_n,
        if_write => memReaderLoad_U0_writePackages_write,
        if_dout => writePackages_dout,
        if_num_data_valid => writePackages_num_data_valid,
        if_fifo_cap => writePackages_fifo_cap,
        if_empty_n => writePackages_empty_n,
        if_read => memReaderForwardPackage_U0_writePackages_read);

    pkgDone_U : component memReader_fifo_w1_d16_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => memReaderForwardPackage_U0_pkgDone_din,
        if_full_n => pkgDone_full_n,
        if_write => memReaderForwardPackage_U0_pkgDone_write,
        if_dout => pkgDone_dout,
        if_num_data_valid => pkgDone_num_data_valid,
        if_fifo_cap => pkgDone_fifo_cap,
        if_empty_n => pkgDone_empty_n,
        if_read => memReaderForwardAllow_U0_pkgDone_read);

    start_for_memReaderForwardPackage_U0_U : component memReader_start_for_memReaderForwardPackage_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_memReaderForwardPackage_U0_din,
        if_full_n => start_for_memReaderForwardPackage_U0_full_n,
        if_write => memReaderLoad_U0_start_write,
        if_dout => start_for_memReaderForwardPackage_U0_dout,
        if_empty_n => start_for_memReaderForwardPackage_U0_empty_n,
        if_read => memReaderForwardPackage_U0_ap_ready);

    start_for_memReaderForwardAllow_U0_U : component memReader_start_for_memReaderForwardAllow_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_memReaderForwardAllow_U0_din,
        if_full_n => start_for_memReaderForwardAllow_U0_full_n,
        if_write => memReaderLoad_U0_start_write,
        if_dout => start_for_memReaderForwardAllow_U0_dout,
        if_empty_n => start_for_memReaderForwardAllow_U0_empty_n,
        if_read => memReaderForwardAllow_U0_ap_ready);





    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;
    argDataOut_TDATA <= memReaderForwardPackage_U0_argDataOut_TDATA;
    argDataOut_TVALID <= memReaderForwardPackage_U0_argDataOut_TVALID;
    argOut_TDATA <= memReaderForwardAllow_U0_argOut_TDATA;
    argOut_TVALID <= memReaderForwardAllow_U0_argOut_TVALID;
    gmem_RID <= ap_const_lv1_0;
    gmem_RLAST <= ap_const_logic_0;
    gmem_RRESP <= ap_const_lv2_0;
    gmem_RUSER <= ap_const_lv1_0;
    memReaderForwardAllow_U0_ap_continue <= ap_const_logic_1;
    memReaderForwardAllow_U0_ap_start <= start_for_memReaderForwardAllow_U0_empty_n;
    memReaderForwardPackage_U0_ap_continue <= ap_const_logic_1;
    memReaderForwardPackage_U0_ap_start <= start_for_memReaderForwardPackage_U0_empty_n;
    memReaderLoad_U0_ap_continue <= ap_const_logic_1;
    memReaderLoad_U0_ap_start <= ap_const_logic_1;
    memReaderLoad_U0_start_full_n <= (start_for_memReaderForwardPackage_U0_full_n and start_for_memReaderForwardAllow_U0_full_n);
    start_for_memReaderForwardAllow_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_memReaderForwardPackage_U0_din <= (0=>ap_const_logic_1, others=>'-');
    taskIn_TREADY <= memReaderLoad_U0_taskIn_TREADY;
end behav;
