// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module vertex_map_readVertex_Pipeline_VITIS_LOOP_64_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_CHN_1_AWVALID,
        m_axi_gmem_CHN_1_AWREADY,
        m_axi_gmem_CHN_1_AWADDR,
        m_axi_gmem_CHN_1_AWID,
        m_axi_gmem_CHN_1_AWLEN,
        m_axi_gmem_CHN_1_AWSIZE,
        m_axi_gmem_CHN_1_AWBURST,
        m_axi_gmem_CHN_1_AWLOCK,
        m_axi_gmem_CHN_1_AWCACHE,
        m_axi_gmem_CHN_1_AWPROT,
        m_axi_gmem_CHN_1_AWQOS,
        m_axi_gmem_CHN_1_AWREGION,
        m_axi_gmem_CHN_1_AWUSER,
        m_axi_gmem_CHN_1_WVALID,
        m_axi_gmem_CHN_1_WREADY,
        m_axi_gmem_CHN_1_WDATA,
        m_axi_gmem_CHN_1_WSTRB,
        m_axi_gmem_CHN_1_WLAST,
        m_axi_gmem_CHN_1_WID,
        m_axi_gmem_CHN_1_WUSER,
        m_axi_gmem_CHN_1_ARVALID,
        m_axi_gmem_CHN_1_ARREADY,
        m_axi_gmem_CHN_1_ARADDR,
        m_axi_gmem_CHN_1_ARID,
        m_axi_gmem_CHN_1_ARLEN,
        m_axi_gmem_CHN_1_ARSIZE,
        m_axi_gmem_CHN_1_ARBURST,
        m_axi_gmem_CHN_1_ARLOCK,
        m_axi_gmem_CHN_1_ARCACHE,
        m_axi_gmem_CHN_1_ARPROT,
        m_axi_gmem_CHN_1_ARQOS,
        m_axi_gmem_CHN_1_ARREGION,
        m_axi_gmem_CHN_1_ARUSER,
        m_axi_gmem_CHN_1_RVALID,
        m_axi_gmem_CHN_1_RREADY,
        m_axi_gmem_CHN_1_RDATA,
        m_axi_gmem_CHN_1_RLAST,
        m_axi_gmem_CHN_1_RID,
        m_axi_gmem_CHN_1_RFIFONUM,
        m_axi_gmem_CHN_1_RUSER,
        m_axi_gmem_CHN_1_RRESP,
        m_axi_gmem_CHN_1_BVALID,
        m_axi_gmem_CHN_1_BREADY,
        m_axi_gmem_CHN_1_BRESP,
        m_axi_gmem_CHN_1_BID,
        m_axi_gmem_CHN_1_BUSER,
        m_axi_gmem_CHN_2_AWVALID,
        m_axi_gmem_CHN_2_AWREADY,
        m_axi_gmem_CHN_2_AWADDR,
        m_axi_gmem_CHN_2_AWID,
        m_axi_gmem_CHN_2_AWLEN,
        m_axi_gmem_CHN_2_AWSIZE,
        m_axi_gmem_CHN_2_AWBURST,
        m_axi_gmem_CHN_2_AWLOCK,
        m_axi_gmem_CHN_2_AWCACHE,
        m_axi_gmem_CHN_2_AWPROT,
        m_axi_gmem_CHN_2_AWQOS,
        m_axi_gmem_CHN_2_AWREGION,
        m_axi_gmem_CHN_2_AWUSER,
        m_axi_gmem_CHN_2_WVALID,
        m_axi_gmem_CHN_2_WREADY,
        m_axi_gmem_CHN_2_WDATA,
        m_axi_gmem_CHN_2_WSTRB,
        m_axi_gmem_CHN_2_WLAST,
        m_axi_gmem_CHN_2_WID,
        m_axi_gmem_CHN_2_WUSER,
        m_axi_gmem_CHN_2_ARVALID,
        m_axi_gmem_CHN_2_ARREADY,
        m_axi_gmem_CHN_2_ARADDR,
        m_axi_gmem_CHN_2_ARID,
        m_axi_gmem_CHN_2_ARLEN,
        m_axi_gmem_CHN_2_ARSIZE,
        m_axi_gmem_CHN_2_ARBURST,
        m_axi_gmem_CHN_2_ARLOCK,
        m_axi_gmem_CHN_2_ARCACHE,
        m_axi_gmem_CHN_2_ARPROT,
        m_axi_gmem_CHN_2_ARQOS,
        m_axi_gmem_CHN_2_ARREGION,
        m_axi_gmem_CHN_2_ARUSER,
        m_axi_gmem_CHN_2_RVALID,
        m_axi_gmem_CHN_2_RREADY,
        m_axi_gmem_CHN_2_RDATA,
        m_axi_gmem_CHN_2_RLAST,
        m_axi_gmem_CHN_2_RID,
        m_axi_gmem_CHN_2_RFIFONUM,
        m_axi_gmem_CHN_2_RUSER,
        m_axi_gmem_CHN_2_RRESP,
        m_axi_gmem_CHN_2_BVALID,
        m_axi_gmem_CHN_2_BREADY,
        m_axi_gmem_CHN_2_BRESP,
        m_axi_gmem_CHN_2_BID,
        m_axi_gmem_CHN_2_BUSER,
        v_size,
        mem0,
        v_neighbours,
        mem1,
        Pcurr,
        inv_deg_address_1,
        adder_in_feed_1_din,
        adder_in_feed_1_num_data_valid,
        adder_in_feed_1_fifo_cap,
        adder_in_feed_1_full_n,
        adder_in_feed_1_write
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_CHN_1_AWVALID;
input   m_axi_gmem_CHN_1_AWREADY;
output  [63:0] m_axi_gmem_CHN_1_AWADDR;
output  [0:0] m_axi_gmem_CHN_1_AWID;
output  [31:0] m_axi_gmem_CHN_1_AWLEN;
output  [2:0] m_axi_gmem_CHN_1_AWSIZE;
output  [1:0] m_axi_gmem_CHN_1_AWBURST;
output  [1:0] m_axi_gmem_CHN_1_AWLOCK;
output  [3:0] m_axi_gmem_CHN_1_AWCACHE;
output  [2:0] m_axi_gmem_CHN_1_AWPROT;
output  [3:0] m_axi_gmem_CHN_1_AWQOS;
output  [3:0] m_axi_gmem_CHN_1_AWREGION;
output  [0:0] m_axi_gmem_CHN_1_AWUSER;
output   m_axi_gmem_CHN_1_WVALID;
input   m_axi_gmem_CHN_1_WREADY;
output  [63:0] m_axi_gmem_CHN_1_WDATA;
output  [7:0] m_axi_gmem_CHN_1_WSTRB;
output   m_axi_gmem_CHN_1_WLAST;
output  [0:0] m_axi_gmem_CHN_1_WID;
output  [0:0] m_axi_gmem_CHN_1_WUSER;
output   m_axi_gmem_CHN_1_ARVALID;
input   m_axi_gmem_CHN_1_ARREADY;
output  [63:0] m_axi_gmem_CHN_1_ARADDR;
output  [0:0] m_axi_gmem_CHN_1_ARID;
output  [31:0] m_axi_gmem_CHN_1_ARLEN;
output  [2:0] m_axi_gmem_CHN_1_ARSIZE;
output  [1:0] m_axi_gmem_CHN_1_ARBURST;
output  [1:0] m_axi_gmem_CHN_1_ARLOCK;
output  [3:0] m_axi_gmem_CHN_1_ARCACHE;
output  [2:0] m_axi_gmem_CHN_1_ARPROT;
output  [3:0] m_axi_gmem_CHN_1_ARQOS;
output  [3:0] m_axi_gmem_CHN_1_ARREGION;
output  [0:0] m_axi_gmem_CHN_1_ARUSER;
input   m_axi_gmem_CHN_1_RVALID;
output   m_axi_gmem_CHN_1_RREADY;
input  [63:0] m_axi_gmem_CHN_1_RDATA;
input   m_axi_gmem_CHN_1_RLAST;
input  [0:0] m_axi_gmem_CHN_1_RID;
input  [10:0] m_axi_gmem_CHN_1_RFIFONUM;
input  [0:0] m_axi_gmem_CHN_1_RUSER;
input  [1:0] m_axi_gmem_CHN_1_RRESP;
input   m_axi_gmem_CHN_1_BVALID;
output   m_axi_gmem_CHN_1_BREADY;
input  [1:0] m_axi_gmem_CHN_1_BRESP;
input  [0:0] m_axi_gmem_CHN_1_BID;
input  [0:0] m_axi_gmem_CHN_1_BUSER;
output   m_axi_gmem_CHN_2_AWVALID;
input   m_axi_gmem_CHN_2_AWREADY;
output  [63:0] m_axi_gmem_CHN_2_AWADDR;
output  [0:0] m_axi_gmem_CHN_2_AWID;
output  [31:0] m_axi_gmem_CHN_2_AWLEN;
output  [2:0] m_axi_gmem_CHN_2_AWSIZE;
output  [1:0] m_axi_gmem_CHN_2_AWBURST;
output  [1:0] m_axi_gmem_CHN_2_AWLOCK;
output  [3:0] m_axi_gmem_CHN_2_AWCACHE;
output  [2:0] m_axi_gmem_CHN_2_AWPROT;
output  [3:0] m_axi_gmem_CHN_2_AWQOS;
output  [3:0] m_axi_gmem_CHN_2_AWREGION;
output  [0:0] m_axi_gmem_CHN_2_AWUSER;
output   m_axi_gmem_CHN_2_WVALID;
input   m_axi_gmem_CHN_2_WREADY;
output  [63:0] m_axi_gmem_CHN_2_WDATA;
output  [7:0] m_axi_gmem_CHN_2_WSTRB;
output   m_axi_gmem_CHN_2_WLAST;
output  [0:0] m_axi_gmem_CHN_2_WID;
output  [0:0] m_axi_gmem_CHN_2_WUSER;
output   m_axi_gmem_CHN_2_ARVALID;
input   m_axi_gmem_CHN_2_ARREADY;
output  [63:0] m_axi_gmem_CHN_2_ARADDR;
output  [0:0] m_axi_gmem_CHN_2_ARID;
output  [31:0] m_axi_gmem_CHN_2_ARLEN;
output  [2:0] m_axi_gmem_CHN_2_ARSIZE;
output  [1:0] m_axi_gmem_CHN_2_ARBURST;
output  [1:0] m_axi_gmem_CHN_2_ARLOCK;
output  [3:0] m_axi_gmem_CHN_2_ARCACHE;
output  [2:0] m_axi_gmem_CHN_2_ARPROT;
output  [3:0] m_axi_gmem_CHN_2_ARQOS;
output  [3:0] m_axi_gmem_CHN_2_ARREGION;
output  [0:0] m_axi_gmem_CHN_2_ARUSER;
input   m_axi_gmem_CHN_2_RVALID;
output   m_axi_gmem_CHN_2_RREADY;
input  [63:0] m_axi_gmem_CHN_2_RDATA;
input   m_axi_gmem_CHN_2_RLAST;
input  [0:0] m_axi_gmem_CHN_2_RID;
input  [10:0] m_axi_gmem_CHN_2_RFIFONUM;
input  [0:0] m_axi_gmem_CHN_2_RUSER;
input  [1:0] m_axi_gmem_CHN_2_RRESP;
input   m_axi_gmem_CHN_2_BVALID;
output   m_axi_gmem_CHN_2_BREADY;
input  [1:0] m_axi_gmem_CHN_2_BRESP;
input  [0:0] m_axi_gmem_CHN_2_BID;
input  [0:0] m_axi_gmem_CHN_2_BUSER;
input  [31:0] v_size;
input  [63:0] mem0;
input  [63:0] v_neighbours;
input  [63:0] mem1;
input  [63:0] Pcurr;
input  [63:0] inv_deg_address_1;
output  [31:0] adder_in_feed_1_din;
input  [7:0] adder_in_feed_1_num_data_valid;
input  [7:0] adder_in_feed_1_fifo_cap;
input   adder_in_feed_1_full_n;
output   adder_in_feed_1_write;

reg ap_idle;
reg m_axi_gmem_CHN_1_ARVALID;
reg[63:0] m_axi_gmem_CHN_1_ARADDR;
reg m_axi_gmem_CHN_1_RREADY;
reg m_axi_gmem_CHN_2_ARVALID;
reg m_axi_gmem_CHN_2_RREADY;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_enable_reg_pp0_iter40;
reg    ap_enable_reg_pp0_iter41;
reg    ap_enable_reg_pp0_iter42;
reg    ap_enable_reg_pp0_iter43;
reg    ap_enable_reg_pp0_iter44;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln64_reg_423;
reg    ap_block_state2_io;
reg    ap_block_state82_pp0_stage1_iter40;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_CHN_1_blk_n_AR;
wire    ap_block_pp0_stage1;
reg    gmem_CHN_1_blk_n_R;
wire    ap_block_pp0_stage0;
reg    gmem_CHN_2_blk_n_AR;
reg    gmem_CHN_2_blk_n_R;
reg    adder_in_feed_1_blk_n;
reg    ap_block_state41_pp0_stage0_iter20;
reg    ap_block_state43_io;
reg    ap_block_state89_pp0_stage0_iter44;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln64_fu_179_p2;
reg   [0:0] icmp_ln64_reg_423_pp0_iter1_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter2_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter3_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter4_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter5_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter6_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter7_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter8_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter9_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter10_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter11_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter12_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter13_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter14_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter15_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter16_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter17_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter18_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter19_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter20_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter21_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter22_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter23_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter24_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter25_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter26_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter27_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter28_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter29_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter30_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter31_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter32_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter33_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter34_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter35_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter36_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter37_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter38_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter39_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter40_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter41_reg;
reg   [0:0] icmp_ln64_reg_423_pp0_iter42_reg;
reg   [60:0] trunc_ln66_1_reg_427;
wire   [2:0] trunc_ln66_fu_225_p1;
reg   [2:0] trunc_ln66_reg_432;
reg   [2:0] trunc_ln66_reg_432_pp0_iter1_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter2_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter3_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter4_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter5_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter6_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter7_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter8_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter9_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter10_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter11_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter12_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter13_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter14_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter15_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter16_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter17_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter18_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter19_reg;
reg   [2:0] trunc_ln66_reg_432_pp0_iter20_reg;
reg    ap_block_pp0_stage1_11001;
reg   [63:0] gmem_CHN_1_addr_read_reg_443;
reg   [60:0] trunc_ln72_2_reg_448;
wire   [2:0] trunc_ln72_1_fu_296_p1;
reg   [2:0] trunc_ln72_1_reg_453;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter21_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter22_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter23_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter24_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter25_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter26_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter27_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter28_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter29_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter30_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter31_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter32_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter33_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter34_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter35_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter36_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter37_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter38_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter39_reg;
reg   [2:0] trunc_ln72_1_reg_453_pp0_iter40_reg;
reg   [60:0] trunc_ln74_2_reg_458;
wire   [2:0] trunc_ln74_fu_320_p1;
reg   [2:0] trunc_ln74_reg_463;
reg   [2:0] trunc_ln74_reg_463_pp0_iter21_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter22_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter23_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter24_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter25_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter26_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter27_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter28_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter29_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter30_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter31_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter32_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter33_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter34_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter35_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter36_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter37_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter38_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter39_reg;
reg   [2:0] trunc_ln74_reg_463_pp0_iter40_reg;
reg   [63:0] gmem_CHN_2_addr_read_reg_480;
reg   [63:0] gmem_CHN_1_addr_1_read_reg_485;
wire   [31:0] trunc_ln72_3_fu_360_p1;
reg   [31:0] trunc_ln72_3_reg_490;
wire   [31:0] trunc_ln74_1_fu_380_p1;
reg   [31:0] trunc_ln74_1_reg_495;
wire   [31:0] grp_fu_167_p2;
reg   [31:0] contribution_reg_510;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
wire  signed [63:0] sext_ln66_fu_234_p1;
wire  signed [63:0] sext_ln72_fu_324_p1;
wire  signed [63:0] sext_ln74_fu_334_p1;
reg   [31:0] i_fu_84;
wire   [31:0] add_ln64_fu_185_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_i_3;
wire   [31:0] bitcast_ln79_fu_392_p1;
reg    ap_block_pp0_stage0_01001;
reg    adder_in_feed_1_write_local;
wire   [31:0] grp_fu_167_p0;
wire   [31:0] grp_fu_167_p1;
wire   [33:0] shl_ln_fu_191_p3;
wire   [63:0] zext_ln66_fu_199_p1;
wire   [63:0] add_ln66_fu_203_p2;
wire   [63:0] add_ln66_1_fu_209_p2;
wire   [5:0] shl_ln66_1_fu_244_p3;
wire   [63:0] zext_ln66_1_fu_251_p1;
wire   [63:0] lshr_ln66_fu_255_p2;
wire   [31:0] trunc_ln72_fu_260_p1;
wire   [33:0] shl_ln1_fu_264_p3;
wire   [63:0] zext_ln72_fu_272_p1;
wire   [63:0] add_ln72_fu_276_p2;
wire   [63:0] add_ln72_1_fu_281_p2;
wire   [63:0] add_ln74_fu_300_p2;
wire   [63:0] add_ln74_1_fu_305_p2;
wire   [5:0] shl_ln72_1_fu_344_p3;
wire   [63:0] zext_ln72_1_fu_351_p1;
wire   [63:0] lshr_ln72_fu_355_p2;
wire   [5:0] shl_ln2_fu_364_p3;
wire   [63:0] zext_ln74_fu_371_p1;
wire   [63:0] lshr_ln74_fu_375_p2;
reg    grp_fu_167_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter43_stage0;
reg    ap_idle_pp0_0to42;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg    ap_loop_exit_ready_pp0_iter39_reg;
reg    ap_loop_exit_ready_pp0_iter40_reg;
reg    ap_loop_exit_ready_pp0_iter41_reg;
reg    ap_loop_exit_ready_pp0_iter42_reg;
reg    ap_loop_exit_ready_pp0_iter43_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to44;
reg    ap_done_pending_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 ap_enable_reg_pp0_iter40 = 1'b0;
#0 ap_enable_reg_pp0_iter41 = 1'b0;
#0 ap_enable_reg_pp0_iter42 = 1'b0;
#0 ap_enable_reg_pp0_iter43 = 1'b0;
#0 ap_enable_reg_pp0_iter44 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_84 = 32'd0;
#0 ap_done_reg = 1'b0;
end

vertex_map_fmul_32ns_32ns_32_5_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_5_max_dsp_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_167_p0),
    .din1(grp_fu_167_p1),
    .ce(grp_fu_167_ce),
    .dout(grp_fu_167_p2)
);

vertex_map_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter43_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter40 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter40 <= ap_enable_reg_pp0_iter39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter41 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter41 <= ap_enable_reg_pp0_iter40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter42 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter42 <= ap_enable_reg_pp0_iter41;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter43 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter43 <= ap_enable_reg_pp0_iter42;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter44 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter44 == 1'b1))) begin
            ap_enable_reg_pp0_iter44 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter44 <= ap_enable_reg_pp0_iter43;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter17_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter18_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter19_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter20_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter21_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter22_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter23_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter24_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter25_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter26_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter27_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter28_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter29_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter30_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter31_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter32_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter33_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter34_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter35_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter36_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter37_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter38_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter39_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter39_reg <= ap_loop_exit_ready_pp0_iter38_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter40_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter40_reg <= ap_loop_exit_ready_pp0_iter39_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter41_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter41_reg <= ap_loop_exit_ready_pp0_iter40_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter42_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter42_reg <= ap_loop_exit_ready_pp0_iter41_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter43_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter43_reg <= ap_loop_exit_ready_pp0_iter42_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln64_fu_179_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_84 <= add_ln64_fu_185_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_84 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        contribution_reg_510 <= grp_fu_167_p2;
        gmem_CHN_1_addr_1_read_reg_485 <= m_axi_gmem_CHN_1_RDATA;
        gmem_CHN_2_addr_read_reg_480 <= m_axi_gmem_CHN_2_RDATA;
        trunc_ln72_1_reg_453 <= trunc_ln72_1_fu_296_p1;
        trunc_ln72_1_reg_453_pp0_iter21_reg <= trunc_ln72_1_reg_453;
        trunc_ln72_1_reg_453_pp0_iter22_reg <= trunc_ln72_1_reg_453_pp0_iter21_reg;
        trunc_ln72_1_reg_453_pp0_iter23_reg <= trunc_ln72_1_reg_453_pp0_iter22_reg;
        trunc_ln72_1_reg_453_pp0_iter24_reg <= trunc_ln72_1_reg_453_pp0_iter23_reg;
        trunc_ln72_1_reg_453_pp0_iter25_reg <= trunc_ln72_1_reg_453_pp0_iter24_reg;
        trunc_ln72_1_reg_453_pp0_iter26_reg <= trunc_ln72_1_reg_453_pp0_iter25_reg;
        trunc_ln72_1_reg_453_pp0_iter27_reg <= trunc_ln72_1_reg_453_pp0_iter26_reg;
        trunc_ln72_1_reg_453_pp0_iter28_reg <= trunc_ln72_1_reg_453_pp0_iter27_reg;
        trunc_ln72_1_reg_453_pp0_iter29_reg <= trunc_ln72_1_reg_453_pp0_iter28_reg;
        trunc_ln72_1_reg_453_pp0_iter30_reg <= trunc_ln72_1_reg_453_pp0_iter29_reg;
        trunc_ln72_1_reg_453_pp0_iter31_reg <= trunc_ln72_1_reg_453_pp0_iter30_reg;
        trunc_ln72_1_reg_453_pp0_iter32_reg <= trunc_ln72_1_reg_453_pp0_iter31_reg;
        trunc_ln72_1_reg_453_pp0_iter33_reg <= trunc_ln72_1_reg_453_pp0_iter32_reg;
        trunc_ln72_1_reg_453_pp0_iter34_reg <= trunc_ln72_1_reg_453_pp0_iter33_reg;
        trunc_ln72_1_reg_453_pp0_iter35_reg <= trunc_ln72_1_reg_453_pp0_iter34_reg;
        trunc_ln72_1_reg_453_pp0_iter36_reg <= trunc_ln72_1_reg_453_pp0_iter35_reg;
        trunc_ln72_1_reg_453_pp0_iter37_reg <= trunc_ln72_1_reg_453_pp0_iter36_reg;
        trunc_ln72_1_reg_453_pp0_iter38_reg <= trunc_ln72_1_reg_453_pp0_iter37_reg;
        trunc_ln72_1_reg_453_pp0_iter39_reg <= trunc_ln72_1_reg_453_pp0_iter38_reg;
        trunc_ln72_1_reg_453_pp0_iter40_reg <= trunc_ln72_1_reg_453_pp0_iter39_reg;
        trunc_ln72_2_reg_448 <= {{add_ln72_1_fu_281_p2[63:3]}};
        trunc_ln74_2_reg_458 <= {{add_ln74_1_fu_305_p2[63:3]}};
        trunc_ln74_reg_463 <= trunc_ln74_fu_320_p1;
        trunc_ln74_reg_463_pp0_iter21_reg <= trunc_ln74_reg_463;
        trunc_ln74_reg_463_pp0_iter22_reg <= trunc_ln74_reg_463_pp0_iter21_reg;
        trunc_ln74_reg_463_pp0_iter23_reg <= trunc_ln74_reg_463_pp0_iter22_reg;
        trunc_ln74_reg_463_pp0_iter24_reg <= trunc_ln74_reg_463_pp0_iter23_reg;
        trunc_ln74_reg_463_pp0_iter25_reg <= trunc_ln74_reg_463_pp0_iter24_reg;
        trunc_ln74_reg_463_pp0_iter26_reg <= trunc_ln74_reg_463_pp0_iter25_reg;
        trunc_ln74_reg_463_pp0_iter27_reg <= trunc_ln74_reg_463_pp0_iter26_reg;
        trunc_ln74_reg_463_pp0_iter28_reg <= trunc_ln74_reg_463_pp0_iter27_reg;
        trunc_ln74_reg_463_pp0_iter29_reg <= trunc_ln74_reg_463_pp0_iter28_reg;
        trunc_ln74_reg_463_pp0_iter30_reg <= trunc_ln74_reg_463_pp0_iter29_reg;
        trunc_ln74_reg_463_pp0_iter31_reg <= trunc_ln74_reg_463_pp0_iter30_reg;
        trunc_ln74_reg_463_pp0_iter32_reg <= trunc_ln74_reg_463_pp0_iter31_reg;
        trunc_ln74_reg_463_pp0_iter33_reg <= trunc_ln74_reg_463_pp0_iter32_reg;
        trunc_ln74_reg_463_pp0_iter34_reg <= trunc_ln74_reg_463_pp0_iter33_reg;
        trunc_ln74_reg_463_pp0_iter35_reg <= trunc_ln74_reg_463_pp0_iter34_reg;
        trunc_ln74_reg_463_pp0_iter36_reg <= trunc_ln74_reg_463_pp0_iter35_reg;
        trunc_ln74_reg_463_pp0_iter37_reg <= trunc_ln74_reg_463_pp0_iter36_reg;
        trunc_ln74_reg_463_pp0_iter38_reg <= trunc_ln74_reg_463_pp0_iter37_reg;
        trunc_ln74_reg_463_pp0_iter39_reg <= trunc_ln74_reg_463_pp0_iter38_reg;
        trunc_ln74_reg_463_pp0_iter40_reg <= trunc_ln74_reg_463_pp0_iter39_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem_CHN_1_addr_read_reg_443 <= m_axi_gmem_CHN_1_RDATA;
        icmp_ln64_reg_423 <= icmp_ln64_fu_179_p2;
        icmp_ln64_reg_423_pp0_iter10_reg <= icmp_ln64_reg_423_pp0_iter9_reg;
        icmp_ln64_reg_423_pp0_iter11_reg <= icmp_ln64_reg_423_pp0_iter10_reg;
        icmp_ln64_reg_423_pp0_iter12_reg <= icmp_ln64_reg_423_pp0_iter11_reg;
        icmp_ln64_reg_423_pp0_iter13_reg <= icmp_ln64_reg_423_pp0_iter12_reg;
        icmp_ln64_reg_423_pp0_iter14_reg <= icmp_ln64_reg_423_pp0_iter13_reg;
        icmp_ln64_reg_423_pp0_iter15_reg <= icmp_ln64_reg_423_pp0_iter14_reg;
        icmp_ln64_reg_423_pp0_iter16_reg <= icmp_ln64_reg_423_pp0_iter15_reg;
        icmp_ln64_reg_423_pp0_iter17_reg <= icmp_ln64_reg_423_pp0_iter16_reg;
        icmp_ln64_reg_423_pp0_iter18_reg <= icmp_ln64_reg_423_pp0_iter17_reg;
        icmp_ln64_reg_423_pp0_iter19_reg <= icmp_ln64_reg_423_pp0_iter18_reg;
        icmp_ln64_reg_423_pp0_iter1_reg <= icmp_ln64_reg_423;
        icmp_ln64_reg_423_pp0_iter20_reg <= icmp_ln64_reg_423_pp0_iter19_reg;
        icmp_ln64_reg_423_pp0_iter21_reg <= icmp_ln64_reg_423_pp0_iter20_reg;
        icmp_ln64_reg_423_pp0_iter22_reg <= icmp_ln64_reg_423_pp0_iter21_reg;
        icmp_ln64_reg_423_pp0_iter23_reg <= icmp_ln64_reg_423_pp0_iter22_reg;
        icmp_ln64_reg_423_pp0_iter24_reg <= icmp_ln64_reg_423_pp0_iter23_reg;
        icmp_ln64_reg_423_pp0_iter25_reg <= icmp_ln64_reg_423_pp0_iter24_reg;
        icmp_ln64_reg_423_pp0_iter26_reg <= icmp_ln64_reg_423_pp0_iter25_reg;
        icmp_ln64_reg_423_pp0_iter27_reg <= icmp_ln64_reg_423_pp0_iter26_reg;
        icmp_ln64_reg_423_pp0_iter28_reg <= icmp_ln64_reg_423_pp0_iter27_reg;
        icmp_ln64_reg_423_pp0_iter29_reg <= icmp_ln64_reg_423_pp0_iter28_reg;
        icmp_ln64_reg_423_pp0_iter2_reg <= icmp_ln64_reg_423_pp0_iter1_reg;
        icmp_ln64_reg_423_pp0_iter30_reg <= icmp_ln64_reg_423_pp0_iter29_reg;
        icmp_ln64_reg_423_pp0_iter31_reg <= icmp_ln64_reg_423_pp0_iter30_reg;
        icmp_ln64_reg_423_pp0_iter32_reg <= icmp_ln64_reg_423_pp0_iter31_reg;
        icmp_ln64_reg_423_pp0_iter33_reg <= icmp_ln64_reg_423_pp0_iter32_reg;
        icmp_ln64_reg_423_pp0_iter34_reg <= icmp_ln64_reg_423_pp0_iter33_reg;
        icmp_ln64_reg_423_pp0_iter35_reg <= icmp_ln64_reg_423_pp0_iter34_reg;
        icmp_ln64_reg_423_pp0_iter36_reg <= icmp_ln64_reg_423_pp0_iter35_reg;
        icmp_ln64_reg_423_pp0_iter37_reg <= icmp_ln64_reg_423_pp0_iter36_reg;
        icmp_ln64_reg_423_pp0_iter38_reg <= icmp_ln64_reg_423_pp0_iter37_reg;
        icmp_ln64_reg_423_pp0_iter39_reg <= icmp_ln64_reg_423_pp0_iter38_reg;
        icmp_ln64_reg_423_pp0_iter3_reg <= icmp_ln64_reg_423_pp0_iter2_reg;
        icmp_ln64_reg_423_pp0_iter40_reg <= icmp_ln64_reg_423_pp0_iter39_reg;
        icmp_ln64_reg_423_pp0_iter41_reg <= icmp_ln64_reg_423_pp0_iter40_reg;
        icmp_ln64_reg_423_pp0_iter42_reg <= icmp_ln64_reg_423_pp0_iter41_reg;
        icmp_ln64_reg_423_pp0_iter4_reg <= icmp_ln64_reg_423_pp0_iter3_reg;
        icmp_ln64_reg_423_pp0_iter5_reg <= icmp_ln64_reg_423_pp0_iter4_reg;
        icmp_ln64_reg_423_pp0_iter6_reg <= icmp_ln64_reg_423_pp0_iter5_reg;
        icmp_ln64_reg_423_pp0_iter7_reg <= icmp_ln64_reg_423_pp0_iter6_reg;
        icmp_ln64_reg_423_pp0_iter8_reg <= icmp_ln64_reg_423_pp0_iter7_reg;
        icmp_ln64_reg_423_pp0_iter9_reg <= icmp_ln64_reg_423_pp0_iter8_reg;
        trunc_ln66_1_reg_427 <= {{add_ln66_1_fu_209_p2[63:3]}};
        trunc_ln66_reg_432 <= trunc_ln66_fu_225_p1;
        trunc_ln66_reg_432_pp0_iter10_reg <= trunc_ln66_reg_432_pp0_iter9_reg;
        trunc_ln66_reg_432_pp0_iter11_reg <= trunc_ln66_reg_432_pp0_iter10_reg;
        trunc_ln66_reg_432_pp0_iter12_reg <= trunc_ln66_reg_432_pp0_iter11_reg;
        trunc_ln66_reg_432_pp0_iter13_reg <= trunc_ln66_reg_432_pp0_iter12_reg;
        trunc_ln66_reg_432_pp0_iter14_reg <= trunc_ln66_reg_432_pp0_iter13_reg;
        trunc_ln66_reg_432_pp0_iter15_reg <= trunc_ln66_reg_432_pp0_iter14_reg;
        trunc_ln66_reg_432_pp0_iter16_reg <= trunc_ln66_reg_432_pp0_iter15_reg;
        trunc_ln66_reg_432_pp0_iter17_reg <= trunc_ln66_reg_432_pp0_iter16_reg;
        trunc_ln66_reg_432_pp0_iter18_reg <= trunc_ln66_reg_432_pp0_iter17_reg;
        trunc_ln66_reg_432_pp0_iter19_reg <= trunc_ln66_reg_432_pp0_iter18_reg;
        trunc_ln66_reg_432_pp0_iter1_reg <= trunc_ln66_reg_432;
        trunc_ln66_reg_432_pp0_iter20_reg <= trunc_ln66_reg_432_pp0_iter19_reg;
        trunc_ln66_reg_432_pp0_iter2_reg <= trunc_ln66_reg_432_pp0_iter1_reg;
        trunc_ln66_reg_432_pp0_iter3_reg <= trunc_ln66_reg_432_pp0_iter2_reg;
        trunc_ln66_reg_432_pp0_iter4_reg <= trunc_ln66_reg_432_pp0_iter3_reg;
        trunc_ln66_reg_432_pp0_iter5_reg <= trunc_ln66_reg_432_pp0_iter4_reg;
        trunc_ln66_reg_432_pp0_iter6_reg <= trunc_ln66_reg_432_pp0_iter5_reg;
        trunc_ln66_reg_432_pp0_iter7_reg <= trunc_ln66_reg_432_pp0_iter6_reg;
        trunc_ln66_reg_432_pp0_iter8_reg <= trunc_ln66_reg_432_pp0_iter7_reg;
        trunc_ln66_reg_432_pp0_iter9_reg <= trunc_ln66_reg_432_pp0_iter8_reg;
        trunc_ln72_3_reg_490 <= trunc_ln72_3_fu_360_p1;
        trunc_ln74_1_reg_495 <= trunc_ln74_1_fu_380_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter44 == 1'b1))) begin
        adder_in_feed_1_blk_n = adder_in_feed_1_full_n;
    end else begin
        adder_in_feed_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter44 == 1'b1))) begin
        adder_in_feed_1_write_local = 1'b1;
    end else begin
        adder_in_feed_1_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln64_reg_423 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln64_reg_423_pp0_iter42_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter43 == 1'b1))) begin
        ap_condition_exit_pp0_iter43_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter43_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter43_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter43_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter42_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter41_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter40_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter39_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter38_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter37_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter36_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter35_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter34_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter33_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter32_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter31_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter30_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter29_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter28_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter27_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter26_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter25_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter24_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter23_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter22_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter21_reg 
    == 1'b0) & (ap_loop_exit_ready_pp0_iter20_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter19_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter18_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter17_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter16_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter15_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter13_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b0) 
    & (ap_enable_reg_pp0_iter43 == 1'b0) & (ap_enable_reg_pp0_iter42 == 1'b0) & (ap_enable_reg_pp0_iter41 == 1'b0) & (ap_enable_reg_pp0_iter40 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter42 == 1'b0) 
    & (ap_enable_reg_pp0_iter41 == 1'b0) & (ap_enable_reg_pp0_iter40 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0_0to42 = 1'b1;
    end else begin
        ap_idle_pp0_0to42 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b0) & (ap_enable_reg_pp0_iter43 == 1'b0) 
    & (ap_enable_reg_pp0_iter42 == 1'b0) & (ap_enable_reg_pp0_iter41 == 1'b0) & (ap_enable_reg_pp0_iter40 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0_1to44 = 1'b1;
    end else begin
        ap_idle_pp0_1to44 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_3 = 32'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_84;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln64_reg_423 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        gmem_CHN_1_blk_n_AR = m_axi_gmem_CHN_1_ARREADY;
    end else begin
        gmem_CHN_1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter40 == 1'b1)))) begin
        gmem_CHN_1_blk_n_R = m_axi_gmem_CHN_1_RVALID;
    end else begin
        gmem_CHN_1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem_CHN_2_blk_n_AR = m_axi_gmem_CHN_2_ARREADY;
    end else begin
        gmem_CHN_2_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter40 == 1'b1))) begin
        gmem_CHN_2_blk_n_R = m_axi_gmem_CHN_2_RVALID;
    end else begin
        gmem_CHN_2_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_167_ce = 1'b1;
    end else begin
        grp_fu_167_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem_CHN_1_ARADDR = sext_ln74_fu_334_p1;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln64_reg_423 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        m_axi_gmem_CHN_1_ARADDR = sext_ln66_fu_234_p1;
    end else begin
        m_axi_gmem_CHN_1_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln64_reg_423 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        m_axi_gmem_CHN_1_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_CHN_1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter40 == 1'b1)) | ((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        m_axi_gmem_CHN_1_RREADY = 1'b1;
    end else begin
        m_axi_gmem_CHN_1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem_CHN_2_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_CHN_2_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter40 == 1'b1))) begin
        m_axi_gmem_CHN_2_RREADY = 1'b1;
    end else begin
        m_axi_gmem_CHN_2_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to42 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter43_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_idle_pp0_1to44 == 1'b1) & (ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln64_fu_185_p2 = (ap_sig_allocacmp_i_3 + 32'd1);

assign add_ln66_1_fu_209_p2 = (add_ln66_fu_203_p2 + v_neighbours);

assign add_ln66_fu_203_p2 = (zext_ln66_fu_199_p1 + mem0);

assign add_ln72_1_fu_281_p2 = (add_ln72_fu_276_p2 + Pcurr);

assign add_ln72_fu_276_p2 = (zext_ln72_fu_272_p1 + mem1);

assign add_ln74_1_fu_305_p2 = (add_ln74_fu_300_p2 + inv_deg_address_1);

assign add_ln74_fu_300_p2 = (zext_ln72_fu_272_p1 + mem0);

assign adder_in_feed_1_din = bitcast_ln79_fu_392_p1;

assign adder_in_feed_1_write = adder_in_feed_1_write_local;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'b1 == ap_block_state89_pp0_stage0_iter44) & (ap_enable_reg_pp0_iter44 == 1'b1)) | ((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_block_state41_pp0_stage0_iter20)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state89_pp0_stage0_iter44) & (ap_enable_reg_pp0_iter44 == 1'b1)) | ((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b1 == ap_block_state43_io)) | ((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_block_state41_pp0_stage0_iter20)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state89_pp0_stage0_iter44) & (ap_enable_reg_pp0_iter44 == 1'b1)) | ((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b1 == ap_block_state43_io)) | ((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_block_state41_pp0_stage0_iter20)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((1'b1 == ap_block_state82_pp0_stage1_iter40) & (ap_enable_reg_pp0_iter40 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((1'b1 == ap_block_state82_pp0_stage1_iter40) & (ap_enable_reg_pp0_iter40 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_state2_io = ((icmp_ln64_reg_423 == 1'd0) & (m_axi_gmem_CHN_1_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_state41_pp0_stage0_iter20 = (m_axi_gmem_CHN_1_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state43_io = ((m_axi_gmem_CHN_2_ARREADY == 1'b0) | (m_axi_gmem_CHN_1_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_state82_pp0_stage1_iter40 = ((m_axi_gmem_CHN_2_RVALID == 1'b0) | (m_axi_gmem_CHN_1_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state89_pp0_stage0_iter44 = (1'b0 == adder_in_feed_1_full_n);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign bitcast_ln79_fu_392_p1 = contribution_reg_510;

assign grp_fu_167_p0 = trunc_ln72_3_reg_490;

assign grp_fu_167_p1 = trunc_ln74_1_reg_495;

assign icmp_ln64_fu_179_p2 = ((ap_sig_allocacmp_i_3 == v_size) ? 1'b1 : 1'b0);

assign lshr_ln66_fu_255_p2 = gmem_CHN_1_addr_read_reg_443 >> zext_ln66_1_fu_251_p1;

assign lshr_ln72_fu_355_p2 = gmem_CHN_2_addr_read_reg_480 >> zext_ln72_1_fu_351_p1;

assign lshr_ln74_fu_375_p2 = gmem_CHN_1_addr_1_read_reg_485 >> zext_ln74_fu_371_p1;

assign m_axi_gmem_CHN_1_ARBURST = 2'd0;

assign m_axi_gmem_CHN_1_ARCACHE = 4'd0;

assign m_axi_gmem_CHN_1_ARID = 1'd0;

assign m_axi_gmem_CHN_1_ARLEN = 64'd1;

assign m_axi_gmem_CHN_1_ARLOCK = 2'd0;

assign m_axi_gmem_CHN_1_ARPROT = 3'd0;

assign m_axi_gmem_CHN_1_ARQOS = 4'd0;

assign m_axi_gmem_CHN_1_ARREGION = 4'd0;

assign m_axi_gmem_CHN_1_ARSIZE = 3'd0;

assign m_axi_gmem_CHN_1_ARUSER = 1'd0;

assign m_axi_gmem_CHN_1_AWADDR = 64'd0;

assign m_axi_gmem_CHN_1_AWBURST = 2'd0;

assign m_axi_gmem_CHN_1_AWCACHE = 4'd0;

assign m_axi_gmem_CHN_1_AWID = 1'd0;

assign m_axi_gmem_CHN_1_AWLEN = 32'd0;

assign m_axi_gmem_CHN_1_AWLOCK = 2'd0;

assign m_axi_gmem_CHN_1_AWPROT = 3'd0;

assign m_axi_gmem_CHN_1_AWQOS = 4'd0;

assign m_axi_gmem_CHN_1_AWREGION = 4'd0;

assign m_axi_gmem_CHN_1_AWSIZE = 3'd0;

assign m_axi_gmem_CHN_1_AWUSER = 1'd0;

assign m_axi_gmem_CHN_1_AWVALID = 1'b0;

assign m_axi_gmem_CHN_1_BREADY = 1'b0;

assign m_axi_gmem_CHN_1_WDATA = 64'd0;

assign m_axi_gmem_CHN_1_WID = 1'd0;

assign m_axi_gmem_CHN_1_WLAST = 1'b0;

assign m_axi_gmem_CHN_1_WSTRB = 8'd0;

assign m_axi_gmem_CHN_1_WUSER = 1'd0;

assign m_axi_gmem_CHN_1_WVALID = 1'b0;

assign m_axi_gmem_CHN_2_ARADDR = sext_ln72_fu_324_p1;

assign m_axi_gmem_CHN_2_ARBURST = 2'd0;

assign m_axi_gmem_CHN_2_ARCACHE = 4'd0;

assign m_axi_gmem_CHN_2_ARID = 1'd0;

assign m_axi_gmem_CHN_2_ARLEN = 64'd1;

assign m_axi_gmem_CHN_2_ARLOCK = 2'd0;

assign m_axi_gmem_CHN_2_ARPROT = 3'd0;

assign m_axi_gmem_CHN_2_ARQOS = 4'd0;

assign m_axi_gmem_CHN_2_ARREGION = 4'd0;

assign m_axi_gmem_CHN_2_ARSIZE = 3'd0;

assign m_axi_gmem_CHN_2_ARUSER = 1'd0;

assign m_axi_gmem_CHN_2_AWADDR = 64'd0;

assign m_axi_gmem_CHN_2_AWBURST = 2'd0;

assign m_axi_gmem_CHN_2_AWCACHE = 4'd0;

assign m_axi_gmem_CHN_2_AWID = 1'd0;

assign m_axi_gmem_CHN_2_AWLEN = 32'd0;

assign m_axi_gmem_CHN_2_AWLOCK = 2'd0;

assign m_axi_gmem_CHN_2_AWPROT = 3'd0;

assign m_axi_gmem_CHN_2_AWQOS = 4'd0;

assign m_axi_gmem_CHN_2_AWREGION = 4'd0;

assign m_axi_gmem_CHN_2_AWSIZE = 3'd0;

assign m_axi_gmem_CHN_2_AWUSER = 1'd0;

assign m_axi_gmem_CHN_2_AWVALID = 1'b0;

assign m_axi_gmem_CHN_2_BREADY = 1'b0;

assign m_axi_gmem_CHN_2_WDATA = 64'd0;

assign m_axi_gmem_CHN_2_WID = 1'd0;

assign m_axi_gmem_CHN_2_WLAST = 1'b0;

assign m_axi_gmem_CHN_2_WSTRB = 8'd0;

assign m_axi_gmem_CHN_2_WUSER = 1'd0;

assign m_axi_gmem_CHN_2_WVALID = 1'b0;

assign sext_ln66_fu_234_p1 = $signed(trunc_ln66_1_reg_427);

assign sext_ln72_fu_324_p1 = $signed(trunc_ln72_2_reg_448);

assign sext_ln74_fu_334_p1 = $signed(trunc_ln74_2_reg_458);

assign shl_ln1_fu_264_p3 = {{trunc_ln72_fu_260_p1}, {2'd0}};

assign shl_ln2_fu_364_p3 = {{trunc_ln74_reg_463_pp0_iter40_reg}, {3'd0}};

assign shl_ln66_1_fu_244_p3 = {{trunc_ln66_reg_432_pp0_iter20_reg}, {3'd0}};

assign shl_ln72_1_fu_344_p3 = {{trunc_ln72_1_reg_453_pp0_iter40_reg}, {3'd0}};

assign shl_ln_fu_191_p3 = {{ap_sig_allocacmp_i_3}, {2'd0}};

assign trunc_ln66_fu_225_p1 = add_ln66_1_fu_209_p2[2:0];

assign trunc_ln72_1_fu_296_p1 = add_ln72_1_fu_281_p2[2:0];

assign trunc_ln72_3_fu_360_p1 = lshr_ln72_fu_355_p2[31:0];

assign trunc_ln72_fu_260_p1 = lshr_ln66_fu_255_p2[31:0];

assign trunc_ln74_1_fu_380_p1 = lshr_ln74_fu_375_p2[31:0];

assign trunc_ln74_fu_320_p1 = add_ln74_1_fu_305_p2[2:0];

assign zext_ln66_1_fu_251_p1 = shl_ln66_1_fu_244_p3;

assign zext_ln66_fu_199_p1 = shl_ln_fu_191_p3;

assign zext_ln72_1_fu_351_p1 = shl_ln72_1_fu_344_p3;

assign zext_ln72_fu_272_p1 = shl_ln1_fu_264_p3;

assign zext_ln74_fu_371_p1 = shl_ln2_fu_364_p3;

endmodule //vertex_map_readVertex_Pipeline_VITIS_LOOP_64_1
