######################################################################
#
# File name : main_sim_compile.do
# Created on: Wed Nov 27 15:36:19 CET 2024
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vlog -work xil_defaultlib  +define+MODEL_TECH "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_hbm_0_0/hdl/rtl" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/46d1/verif/model" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/3242" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/c783/hdl/verilog" "+incdir+../../../../../project_1.srcs/sources_1/imports/rtl" "+incdir+/alpha/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
"/home/shahawy/Desktop/HardCilk/architecture-generator/output/bfs_2024-11-26_17-51-06/tcl/bfs_vivado_project/project_1.gen/sources_1/bd/design_1/ip/design_1_hbm_0_0/verif/model/hbm_model.sv" \

vlog -64 -incr -mfcu -work xil_defaultlib  +define+NETLIST_SIM "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_hbm_0_0/hdl/rtl" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/46d1/verif/model" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/3242" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/c783/hdl/verilog" "+incdir+../../../../../project_1.srcs/sources_1/imports/rtl" "+incdir+/alpha/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
"main_sim_func_synth.v" \

vlog -64 -incr -mfcu -sv -L smartconnect_v1_0 -L axi_firewall_v1_2_6 -L axi_vip_v1_1_17 -L hbm_v1_0_16 -L xilinx_vip -work xil_defaultlib  "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_hbm_0_0/hdl/rtl" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/46d1/verif/model" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/3242" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/c783/hdl/verilog" "+incdir+../../../../../project_1.srcs/sources_1/imports/rtl" "+incdir+/alpha/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../../project_1.ip_user_files/bd/design_1/ip/design_1_axi_vip_0_0/sim/design_1_axi_vip_0_0_pkg.sv" \
"../../../../../project_1.ip_user_files/bd/design_1/ip/design_1_axi_vip_0_0/sim/design_1_axi_vip_0_0.sv" \
"../../../../../project_1.ip_user_files/bd/design_1/ip/design_1_axi_vip_1_0/sim/design_1_axi_vip_1_0_pkg.sv" \
"../../../../../project_1.ip_user_files/bd/design_1/ip/design_1_axi_vip_1_0/sim/design_1_axi_vip_1_0.sv" \


vlog -64 -incr -mfcu -sv -L smartconnect_v1_0 -L axi_firewall_v1_2_6 -L axi_vip_v1_1_17 -L xilinx_vip -work xil_defaultlib  +define+NETLIST_SIM "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_hbm_0_0/hdl/rtl" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/46d1/verif/model" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/3242" "+incdir+../../../../../project_1.gen/sources_1/bd/design_1/ipshared/c783/hdl/verilog" "+incdir+../../../../../project_1.srcs/sources_1/imports/rtl" "+incdir+/alpha/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../../project_1.srcs/sources_1/imports/questa/main_sim.sv" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

# This is script is to be run after running the compilation script generated by vivado, shall be run in the same directory as the compilation script
# Also take care of the path, this one is only for bfs for now. 

sccom -DMTI_BIND_SC_MEMBER_FUNCTION -DUSE_MTI_CIN -g -incr -work xil_defaultlib \
     -I ../../../../../../../software/projects/bfs/include/ \
     -I ../../../../../../../software/driver/include/ \
     ../../../../../../../software/projects/bfs/src/questa_main.cpp \
     ../../../../../../../software/driver/src/hardCilkDriver.cpp


sccom -incr -work xil_defaultlib -dpilib xil_defaultlib -link -fuse-ld=bfd

vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L axi_infrastructure_v1_1_0 -L axi_firewall_v1_2_6 -L fifo_generator_v13_2_10 -L axi_clock_converter_v2_1_30 -L hbm_v1_0_16 -L xlconstant_v1_1_9 -L util_vector_logic_v2_0_4 -L lib_cdc_v1_0_3 -L proc_sys_reset_v5_0_15 -L smartconnect_v1_0 -L axi_register_slice_v2_1_31 -L axi_vip_v1_1_17 -L generic_baseblocks_v2_1_2 -L axi_data_fifo_v2_1_30 -L axi_protocol_converter_v2_1_31 -L blk_mem_gen_v8_4_8 -L axi_dwidth_converter_v2_1_31 -L axi_lite_ipif_v3_0_4 -L interrupt_control_v3_1_5 -L axi_gpio_v2_0_33 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.glbl xil_defaultlib.TestBench xil_defaultlib.main_sim -ccflags '-link -fuse-ld=bfd'  -o main_sim_opt


vsim -lib xil_defaultlib main_sim_opt

layout load Simulate;

view wave
view structure
view signals


do ./wave.do

radix decimal;

run -all