package HLSHelpers

import chisel3._
import chisel3.util._

import Descriptors._

import hdlinfo.InterfaceRole
import scala.util.matching.Regex
import Util._
import chext.amba.axi4
import chext.amba.axi4.Ops._
import chext.amba.axi4s
import chext.amba.axi4.full.components.ProtocolConverter
import chext.amba.axi4.full.components.ProtocolConverterConfig
import chext.amba.axi4.full.components.MuxConfig
import HLSHelpers.VitisModuleFactory_Emitter.fullSysGenDescriptor
import java.util.regex.Pattern

trait VitisInterface {
  def name: String
  def role: hdlinfo.InterfaceRole

  def chiselType: Data
}

case class Aximm_VitisInterface(
    val name: String,
    val role: hdlinfo.InterfaceRole,
    val config: chext.amba.axi4.Config
) extends VitisInterface {
  assert(role == InterfaceRole.master || role == InterfaceRole.slave)

  def chiselType: Data =
    if (role == InterfaceRole.master)
      chext.amba.axi4.Master(config).suggestName(name)
    else
      chext.amba.axi4.Slave(config).suggestName(name)
}

case class Axis_VitisInterface(
    val name: String,
    val role: hdlinfo.InterfaceRole,
    val config: chext.amba.axi4s.Config
) extends VitisInterface {
  assert(role == InterfaceRole.master || role == InterfaceRole.slave)

  def chiselType: Data =
    if (role == InterfaceRole.master)
      chext.amba.axi4s.Master(config).suggestName(name)
    else
      chext.amba.axi4s.Slave(config).suggestName(name)
}

case class VitisModuleConfig(
    val desiredName: String = "vitisModule",
    val interfaces: Seq[VitisInterface] = Seq.empty,
    val is_ap_start: Boolean = false,
    val is_ap_done: Boolean = false,
    val is_ap_idle: Boolean = false,
    val is_ap_ready: Boolean = false,
    val hasRemoteWriteBuffer: Boolean = false,
    val writeBufferDataWidth: Int = 32,
    val hasArgumentWriteBuffer: Boolean = false
)

class VitisModule(cfg: VitisModuleConfig) extends BlackBox {
  // A class that is a blackbox representing the RTL module generated By Vitis
  override def desiredName: String = cfg.desiredName

  import scala.collection.immutable.SeqMap

  // Report the cfg interfaces
  println(s"[HLS:HELPERS:108] Vitis Module: ${cfg.desiredName}")
  cfg.interfaces.foreach { interface =>
    println(s"[HLS:HELPERS:108] Vitis Module Interface: ${interface.name} - Role: ${interface.role}")
  }
  if(cfg.is_ap_start) {
    println(s"[HLS:HELPERS:109] Vitis Module has ap_start")
  }
  if(cfg.is_ap_done) {
    println(s"[HLS:HELPERS:110] Vitis Module has ap_done")
  }
  if(cfg.is_ap_idle) {
    println(s"[HLS:HELPERS:111] Vitis Module has ap_idle")
  }
  if(cfg.is_ap_ready) {
    println(s"[HLS:HELPERS:112] Vitis Module has ap_ready")
  }

  val io = IO(new chisel3.Record {
    val elements: SeqMap[String, Data] =
      SeqMap.from(cfg.interfaces.map { interface =>
        {
          interface.name -> interface.chiselType
        }
      }) ++
        Seq(
          if (cfg.is_ap_start) Some("ap_start" -> Input(Bool())) else None,
          if (cfg.is_ap_done) Some("ap_done" -> Output(Bool())) else None,
          if (cfg.is_ap_idle) Some("ap_idle" -> Output(Bool())) else None,
          if (cfg.is_ap_ready) Some("ap_ready" -> Output(Bool())) else None,
          Some("ap_clk" -> Input(Clock())),
          Some("ap_rst_n" -> Input(Bool())),
        ).flatten
  })

  def getPort(name: String) = io.elements.getOrElse(
    name,
    throw new RuntimeException(f"IO port not found: ${name}")
  )
}

class VitisWriteBufferModule(
    cfg: VitisModuleConfig,
    fullSysGenDescriptor: FullSysGenDescriptor,
    taskName: String,
    variableSpawn: Boolean = false
) extends Module {
  override def desiredName: String = cfg.desiredName

  import scala.collection.immutable.SeqMap

  private val wSpawnNext = fullSysGenDescriptor.spawnNextList
    .get(taskName)
    .map(
      _.map(m =>
        fullSysGenDescriptor.taskDescriptors.find(_.name == m).map(_.widthTask)
      ).map(_.get)
    )
    .map(_.max)

  private val pe = Module(new VitisModule(cfg))

  println(pe.name)
  pe.io.elements.foreach { case (name, port) =>
    println(s"[HLS:HELPERS:112] PE Port: $name -> ${port.getClass.getSimpleName}")
  }

  val io = IO(new chisel3.Record {
    val elements: SeqMap[String, Data] =
      SeqMap.from(
        cfg.interfaces
          .withFilter(x => x.name != "spawnNext" && x.name != "argDataOut")
          .map { interface =>
            {
              interface.name -> interface.chiselType
            }
          }
      ) ++
        Seq(
          if (cfg.is_ap_start) Some("ap_start" -> Input(Bool())) else None,
          if (cfg.is_ap_done) Some("ap_done" -> Output(Bool())) else None,
          if (cfg.is_ap_idle) Some("ap_idle" -> Output(Bool())) else None,
          if (cfg.is_ap_ready) Some("ap_ready" -> Output(Bool())) else None,
          wSpawnNext.map(w =>
            "m_axi_spawnNext" -> (axi4.Master(
              new axi4.Config(
                wAddr = fullSysGenDescriptor.widthAddress,
                wData = w // width in bits
              )
            ))
          ),
          pe.io.elements
            .get("argDataOut")
            .map(port => {
              "m_axi_argOut" -> (axi4.Master(
                new axi4.Config(
                  wAddr = fullSysGenDescriptor.widthAddress,
                  // Get data width from the task descriptor
                  wData = cfg.writeBufferDataWidth
                )
              ))
            }),
          Some("ap_clk" -> Input(Clock())),
          Some("ap_rst_n" -> Input(Bool())),
          if(cfg.hasRemoteWriteBuffer) Some("fpgaId" -> Input(UInt(4.W))) else None,
          if(cfg.hasRemoteWriteBuffer) Some("memReqToRemote" -> DecoupledIO(new MemReq(64, cfg.writeBufferDataWidth))) else None,
          if(cfg.hasRemoteWriteBuffer) Some("writeRespFromRemote" -> Flipped(DecoupledIO(new WriteResp()))) else None
        ).flatten
  })

  def getPort(name: String) = io.elements.getOrElse(
    name,
    throw new RuntimeException(f"IO port not found: ${name}")
  )

  private val peTaskOut = ("taskOut", pe.io.elements.get("taskOut"))
  private val peTaskOutGlobal = pe.io.elements
    .filter(_._1.startsWith("taskOutGlobal"))
    .map(x => (x._1, Some(x._2)))
  private val taskOuts =
    (Seq(peTaskOut) ++ peTaskOutGlobal.toSeq).filterNot(_._2.isEmpty)

  println(s"[HLS:HELPERS:166] ${pe.io.elements}")

  println(s"[HLS:HELPERS:168] ${peTaskOut}")
  println(s"[HLS:HELPERS:169] ${peTaskOutGlobal}")

  wSpawnNext.foreach(w => {
    val mWriteBuffer = Module(
      new WriteBuffer(
        new WriteBufferConfig(
          wAddr = fullSysGenDescriptor.widthAddress,
          wData = w,
          wAllow = (if (variableSpawn) 0 else 32),
          wAllowData =
            taskOuts.map(x => x._2.get.asInstanceOf[axi4s.Interface].cfg.wData)
        )
      )
    )

    mWriteBuffer.s_pkg <> pe.getPort("spawnNext").asInstanceOf[axi4s.Interface]
    mWriteBuffer.m_axi <> io.elements
      .get("m_axi_spawnNext")
      .get
      .asInstanceOf[axi4.RawInterface]

    var idx = 0
    for (i <- 0 until taskOuts.length) {
      taskOuts(i)._2 match {
        case Some(value) => {
          value.asInstanceOf[axi4s.Interface] <> mWriteBuffer.s_allows(idx)
          mWriteBuffer.m_allows(idx) <> getPort(taskOuts(i)._1)
          idx = idx + 1
        }
        case None => {}
      }
    }
  })

  // If a task has a taskOutGlobal but has no spawnNext, then connect the taskOutGlobal
  // directly to the taskOutGlobal port
  if (wSpawnNext.isEmpty) {
    for (i <- 0 until taskOuts.length) {
      taskOuts(i)._2 match {
        case Some(value) => {
          value.asInstanceOf[axi4s.Interface] <> getPort(taskOuts(i)._1)
        }
        case None => {}
      }
    }
  }

  if (pe.io.elements.get("argDataOut").isDefined) {
    assert(cfg.hasArgumentWriteBuffer, "Found argDataOut in the PE but the task has no write buffer data width specified in the JSON!")
    pe.io.elements
      .get("argDataOut")
      .map(port => {
        val mWriteBuffer = Module(
          new WriteBuffer(
            new WriteBufferConfig(
              wAddr = fullSysGenDescriptor.widthAddress,
              wData = cfg.writeBufferDataWidth,
              wAllow = 32, // HardCoded?
              wAllowData = Seq(fullSysGenDescriptor.widthAddress),
              isRemoteWriteBuffer = cfg.hasRemoteWriteBuffer
            )
          )
        )

        mWriteBuffer.s_pkg <> pe
          .getPort("argDataOut")
          .asInstanceOf[axi4s.Interface]
        mWriteBuffer.m_axi <> io.elements
          .get("m_axi_argOut")
          .get
          .asInstanceOf[axi4.RawInterface]
        pe.getPort("argOut") <> mWriteBuffer.s_allows(0)
        mWriteBuffer.m_allows(0) <> io.elements.get("argOut").get

        if(cfg.hasRemoteWriteBuffer) {
          mWriteBuffer.fpgaId.get := RegNext(io.elements.get("fpgaId").get)
          mWriteBuffer.memReqToRemote.get <> io.elements.get("memReqToRemote").get
          mWriteBuffer.writeRespFromRemote.get <> io.elements.get("writeRespFromRemote").get
        }
      })
  } else {
    pe.io.elements
      .get("argOut")
      .map(port => {
        port <> io.elements.get("argOut").get
      })
  }

  // Connect buffer to outside //

  // Connect rest of the ports
  pe.io.elements
    .withFilter(x =>
      !((Seq("spawnNext", "argDataOut", "argOut") ++ taskOuts.map(_._1))
        .contains(x._1))
    )
    .foreach {
      case (name, port) => {
        port <> io.elements.get(name).get
      }
    }
}

/** An object with a function that when given a task descriptor, returns an
  * array of VitisModules. The task descriptor has the path to the hdl directory
  * and the name of the module. One function passes the path to another function
  * that parses the <module>.v from the hdl directory and returns a
  * vitisModuleConfig.
  */

object VitisModuleFactory {
  def apply(
      taskDescriptor: TaskDescriptor,
      fullSysGenDescriptor: FullSysGenDescriptor
  ): Seq[VitisWriteBufferModule] = {
    // Entry to PE creation
    val hdlPath = taskDescriptor.peHDLPath
    val moduleName = taskDescriptor.name
    val blackBoxCount = taskDescriptor.numProcessingElements

    // Parse the Verilog of the PE to extract the Ports
    val vitisModuleConfig = parseVitisModule(hdlPath, moduleName, taskDescriptor, fullSysGenDescriptor)

  
    // Log blackBoxCount
    println(s"[HLS:HELPERS:323] Generating $blackBoxCount VitisWriteBufferModules for task: $moduleName")

    Seq.fill(blackBoxCount){
      // Remove the Module call if used with the local emitter
      Module( 
        new VitisWriteBufferModule(
          vitisModuleConfig,
          fullSysGenDescriptor,
          taskDescriptor.name,
          taskDescriptor.variableSpawn
        )
      )
    }
  }

  def extractModule(moduleName: String, filePath: String): Option[String] = {
    val fileContent = scala.io.Source.fromFile(filePath).getLines.mkString("\n")

    // Regular expression to find module definition
    val modulePattern = s"(?s)\\bmodule\\s+$moduleName\\b(.*?)\\bendmodule\\b".r

    modulePattern.findFirstMatchIn(fileContent) match {
      case Some(matched) => Some(matched.group(1).trim)
      case None          => None // Module not found
    }
  }

  def extractSignalWidth(signalName: String, moduleContent: String): Int = {
    // 1. Find the signal line
    val signalRegex = s"""\\[([^\\]]+)\\]\\s+$signalName\\b""".r
    val maybeMatch = signalRegex.findFirstMatchIn(moduleContent)

    maybeMatch match {
      case Some(matched) =>
        val range =
          matched.group(1).replaceAll("\\s", "") // e.g., "C_WIDTH-1:0"
        val parts = range.split(":")
        if (parts.length != 2) return 1

        val msbRaw = parts(0)
        val lsbRaw = parts(1)

        val msb = getValueFromParamOrLiteral(msbRaw, moduleContent)
        val lsb = getValueFromParamOrLiteral(lsbRaw, moduleContent)

        (msb - lsb + 1).abs

      case None => 0 // Signal not found
    }
  }

  def getValueFromParamOrLiteral(expr: String, moduleContent: String): Int = {
    // If it's just a number, return it
    if (expr.matches("\\d+")) return expr.toInt

    // If it's something like "PARAM-1", extract "PARAM" and subtract 1
    val paramWithOffset = """(\w+)-(\d+)""".r
    val paramAlone = """(\w+)""".r

    expr match {
      case paramWithOffset(param, offset) =>
        findParameterValue(param, moduleContent) - offset.toInt
      case paramAlone(param) =>
        findParameterValue(param, moduleContent)
      case _ =>
        println(s"Unsupported format in MSB/LSB: '$expr'")
        0
    }
  }

  def findParameterValue(param: String, content: String): Int = {
    val paramRegex = s"""parameter\\s+$param\\s*=\\s*(\\d+)\\s*;""".r
    paramRegex.findFirstMatchIn(content) match {
      case Some(m) => m.group(1).toInt
      case None =>
        println(s"Parameter '$param' not found.")
        0
    }
  }

  def lineContainsOutput(signalName: String, moduleContent: String): Boolean = {
    val pattern = s"""(?i)(output).*\\b$signalName\\b""".r
    pattern.findFirstIn(moduleContent).isDefined
  }

  def parseVitisModule(
      hdlPath: String,
      moduleName: String,
      taskDescriptor: TaskDescriptor,
      fullSysGenDescriptor: FullSysGenDescriptor
  ): VitisModuleConfig = {
    // read the <module>.v file from the hdlPath

    // val moduleContent = extractModule()
    //   scala.io.Source.fromFile(s"${hdlPath}/${moduleName}.v").mkString

    val moduleContent: String =
      extractModule(s"${moduleName}", s"${hdlPath}/${moduleName}.v").getOrElse(
        throw new RuntimeException("Module not found!")
      )

    // search for parameters in the moduleContent with M_AXI_GMEM and create an Aximm_VitisInterface
    val idWidth = extractSignalWidth("m_axi_gmem_ARID", moduleContent)
    val addrWidth = extractSignalWidth("m_axi_gmem_ARADDR", moduleContent)
    val dataWidth = extractSignalWidth("m_axi_gmem_RDATA", moduleContent)
    val awuserWidth = extractSignalWidth("m_axi_gmem_AWUSER", moduleContent)
    val aruserWidth = extractSignalWidth("m_axi_gmem_ARUSER", moduleContent)
    val wuserWidth = extractSignalWidth("m_axi_gmem_WUSER", moduleContent)
    val ruserWidth = extractSignalWidth("m_axi_gmem_RUSER", moduleContent)
    val buserWidth = extractSignalWidth("m_axi_gmem_BUSER", moduleContent)
    val userValue = findParameterValue("C_M_AXI_GMEM_USER_VALUE", moduleContent)
    val protValue = findParameterValue("C_M_AXI_GMEM_PROT_VALUE", moduleContent)
    val cacheValue =
      findParameterValue("C_M_AXI_GMEM_CACHE_VALUE", moduleContent)
    val wstrbWidth = extractSignalWidth("m_axi_gmem_WSTRB", moduleContent)

    val arlen = extractSignalWidth("m_axi_gmem_ARLEN", moduleContent)

    println(s"[HLS:HELPERS:393] ARLEN ${arlen}")
    // var axiWstrbWidth = extractSignalWidth("m_axi_gmem_ARID", moduleContent) // not used

    // Create an Aximm_VitisInterface
    val M_AXI_GMEM_INTERFACE = if (dataWidth > 0) {
      Some(
        Aximm_VitisInterface(
          "m_axi_gmem",
          InterfaceRole.master,
          chext.amba.axi4.Config(
            wId = idWidth,
            wAddr = addrWidth,
            wData = dataWidth,
            wUserAW = awuserWidth,
            wUserAR = aruserWidth,
            wUserW = wuserWidth,
            wUserR = ruserWidth,
            wUserB = buserWidth,
            axi3Compat = arlen <= 4,
            hasQos = false || arlen > 4,
            hasProt = false|| arlen > 4,
            hasCache = false|| arlen > 4,
            hasRegion = false|| arlen > 4,
            hasLock = false|| arlen > 4
          )
        )
      )
    } else {
      None
    }


  
    val control_data_width = 32
    val control_address_width = 4



    // Create an S_AXI_CONTROL interface if dataWidth > 0 otherwise None
    val aximmInterface_s_axi_control = if (false) {  // Skip this export for now.
      Some(
        Aximm_VitisInterface(
          "s_axi_control",
          InterfaceRole.slave,
          chext.amba.axi4.Config(
            wData = control_data_width,
            wAddr = control_address_width,
            lite = true,
            hasProt = false
          )
        )
      )
    } else {
      None
    }

    // In the lines with output or input, find the width of the TDATA and create an Axis_VitisInterface with the name as  {name}_TDATA
    // Only the lines with output or input are considered
    val tdataLines = moduleContent
      .split("\n")
      .filter { line =>
        line.contains("TDATA") && line.matches(
          """.*\[\s*[\w+\-*/]+\s*:\s*\d+\s*\].*"""
        )
      }

    val tdataRegex = raw"""^\s*(input|output)\s+(?:\w+\s+)?\[\d+:\d+\]\s+(\w+)_TDATA\s*;""".r

    val tdataInterfaces = tdataLines.collect {
      case line @ tdataRegex(direction, name) =>
        val tdataWidth = extractSignalWidth(s"${name}_TDATA", moduleContent) 

        Axis_VitisInterface(
          name,
          if (line.toLowerCase.contains("output")) InterfaceRole.master
          else InterfaceRole.slave,
          chext.amba.axi4s.Config(wData = tdataWidth, onlyRV = true)
        )
    }

    // Search for the regex module <moduleName> (.*); and check ap_start, ap_done, ap_idle, ap_ready
    var is_ap_start = false
    var is_ap_done = false
    var is_ap_idle = false
    var is_ap_ready = false

    //val modulePattern: Regex = """module (\w+)\s*\(([\w\s,]+)\);""".r
    //modulePattern.findAllMatchIn(moduleContent).foreach { moduleMatch =>
      // val name = moduleMatch.group(1)
      // val content = moduleMatch.group(2)
      // if (name == moduleName) {


    val ModuleRegex = s"""(?s)module\\s+$moduleName\\s*\\((.*?)\\);""".r

    // apply the regex on the moduleContent
    val moduleDefinitionMatch = ModuleRegex.findFirstMatchIn(moduleContent)
    if (moduleDefinitionMatch.isDefined) {
      println(s"[HLS:HELPERS:480] Found module definition for ${moduleName}")
    }

    // print moduleDefinitionMatch
    println(s"[HLS:HELPERS:483] Module Definition Match: ${moduleDefinitionMatch}")

    is_ap_start = moduleDefinitionMatch.contains("ap_start")
    is_ap_done = moduleDefinitionMatch.contains("ap_done")
    is_ap_idle = moduleDefinitionMatch.contains("ap_idle")
    is_ap_ready = moduleDefinitionMatch.contains("ap_ready")
      // }
    //}

    println(s"[HLS:HELPERS:480] Found module: ${is_ap_start}")

    // Print the names of the interfaces
    tdataInterfaces.foreach { x =>
      println(s"[HLS:HELPERS:495] ${x}")
    }

    val config_seq =
      (Seq(
        M_AXI_GMEM_INTERFACE,
        aximmInterface_s_axi_control
      ).flatten ++ tdataInterfaces).asInstanceOf[Seq[VitisInterface]]

    // Create the config with the interfaces
    val hasArgumentWriteBuffer_ = taskDescriptor.generateArgOutWriteBuffer && (fullSysGenDescriptor.mFPGASimulation || fullSysGenDescriptor.mFPGASynth)
    VitisModuleConfig(
      moduleName,
      config_seq,
      is_ap_start,
      is_ap_done,
      is_ap_idle,
      is_ap_ready,
      hasArgumentWriteBuffer_,
      if(hasArgumentWriteBuffer_) taskDescriptor.argumentSizeList.head else 0,
      taskDescriptor.generateArgOutWriteBuffer
    )
  }
}


object VitisModuleFactory_Emitter extends App {
  import _root_.circt.stage.ChiselStage
  import Descriptors._
  import Descriptors.DescriptorJSON._

  val descriptor_path = "/beta/shahawy/mfpga_ws/benchmarks/heat/heatSystem.json"
  val fullSysGenDescriptor = parseJsonFile[FullSysGenDescriptor](descriptor_path)
  // get the heat task descriptor
  val descriptor = fullSysGenDescriptor.taskDescriptors.find(_.name == "heat").get


  ChiselStage.emitSystemVerilogFile(
    VitisModuleFactory(descriptor, fullSysGenDescriptor).head,
    Array(
      "--target-dir=output/vitisModule/"
    )
  )
}