// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module vertex_map_readTask (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem_CHN_0_AWVALID,
        m_axi_gmem_CHN_0_AWREADY,
        m_axi_gmem_CHN_0_AWADDR,
        m_axi_gmem_CHN_0_AWID,
        m_axi_gmem_CHN_0_AWLEN,
        m_axi_gmem_CHN_0_AWSIZE,
        m_axi_gmem_CHN_0_AWBURST,
        m_axi_gmem_CHN_0_AWLOCK,
        m_axi_gmem_CHN_0_AWCACHE,
        m_axi_gmem_CHN_0_AWPROT,
        m_axi_gmem_CHN_0_AWQOS,
        m_axi_gmem_CHN_0_AWREGION,
        m_axi_gmem_CHN_0_AWUSER,
        m_axi_gmem_CHN_0_WVALID,
        m_axi_gmem_CHN_0_WREADY,
        m_axi_gmem_CHN_0_WDATA,
        m_axi_gmem_CHN_0_WSTRB,
        m_axi_gmem_CHN_0_WLAST,
        m_axi_gmem_CHN_0_WID,
        m_axi_gmem_CHN_0_WUSER,
        m_axi_gmem_CHN_0_ARVALID,
        m_axi_gmem_CHN_0_ARREADY,
        m_axi_gmem_CHN_0_ARADDR,
        m_axi_gmem_CHN_0_ARID,
        m_axi_gmem_CHN_0_ARLEN,
        m_axi_gmem_CHN_0_ARSIZE,
        m_axi_gmem_CHN_0_ARBURST,
        m_axi_gmem_CHN_0_ARLOCK,
        m_axi_gmem_CHN_0_ARCACHE,
        m_axi_gmem_CHN_0_ARPROT,
        m_axi_gmem_CHN_0_ARQOS,
        m_axi_gmem_CHN_0_ARREGION,
        m_axi_gmem_CHN_0_ARUSER,
        m_axi_gmem_CHN_0_RVALID,
        m_axi_gmem_CHN_0_RREADY,
        m_axi_gmem_CHN_0_RDATA,
        m_axi_gmem_CHN_0_RLAST,
        m_axi_gmem_CHN_0_RID,
        m_axi_gmem_CHN_0_RFIFONUM,
        m_axi_gmem_CHN_0_RUSER,
        m_axi_gmem_CHN_0_RRESP,
        m_axi_gmem_CHN_0_BVALID,
        m_axi_gmem_CHN_0_BREADY,
        m_axi_gmem_CHN_0_BRESP,
        m_axi_gmem_CHN_0_BID,
        m_axi_gmem_CHN_0_BUSER,
        mem,
        taskIn_TDATA,
        taskIn_TVALID,
        taskIn_TREADY,
        addresses_neighbours_0_din,
        addresses_neighbours_0_num_data_valid,
        addresses_neighbours_0_fifo_cap,
        addresses_neighbours_0_full_n,
        addresses_neighbours_0_write,
        addresses_neighbours_1_din,
        addresses_neighbours_1_num_data_valid,
        addresses_neighbours_1_fifo_cap,
        addresses_neighbours_1_full_n,
        addresses_neighbours_1_write,
        addresses_adj_lists_din,
        addresses_adj_lists_num_data_valid,
        addresses_adj_lists_fifo_cap,
        addresses_adj_lists_full_n,
        addresses_adj_lists_write,
        sizes_0_din,
        sizes_0_num_data_valid,
        sizes_0_fifo_cap,
        sizes_0_full_n,
        sizes_0_write,
        sizes_1_din,
        sizes_1_num_data_valid,
        sizes_1_fifo_cap,
        sizes_1_full_n,
        sizes_1_write,
        sizes_2_din,
        sizes_2_num_data_valid,
        sizes_2_fifo_cap,
        sizes_2_full_n,
        sizes_2_write,
        sizes_3_din,
        sizes_3_num_data_valid,
        sizes_3_fifo_cap,
        sizes_3_full_n,
        sizes_3_write,
        triangleCountEntries_din,
        triangleCountEntries_num_data_valid,
        triangleCountEntries_fifo_cap,
        triangleCountEntries_full_n,
        triangleCountEntries_write,
        return_address_queue_din,
        return_address_queue_num_data_valid,
        return_address_queue_fifo_cap,
        return_address_queue_full_n,
        return_address_queue_write,
        fastFinishDelievery_din,
        fastFinishDelievery_num_data_valid,
        fastFinishDelievery_fifo_cap,
        fastFinishDelievery_full_n,
        fastFinishDelievery_write
);

parameter    ap_ST_fsm_state1 = 75'd1;
parameter    ap_ST_fsm_state2 = 75'd2;
parameter    ap_ST_fsm_state3 = 75'd4;
parameter    ap_ST_fsm_state4 = 75'd8;
parameter    ap_ST_fsm_state5 = 75'd16;
parameter    ap_ST_fsm_state6 = 75'd32;
parameter    ap_ST_fsm_state7 = 75'd64;
parameter    ap_ST_fsm_state8 = 75'd128;
parameter    ap_ST_fsm_state9 = 75'd256;
parameter    ap_ST_fsm_state10 = 75'd512;
parameter    ap_ST_fsm_state11 = 75'd1024;
parameter    ap_ST_fsm_state12 = 75'd2048;
parameter    ap_ST_fsm_state13 = 75'd4096;
parameter    ap_ST_fsm_state14 = 75'd8192;
parameter    ap_ST_fsm_state15 = 75'd16384;
parameter    ap_ST_fsm_state16 = 75'd32768;
parameter    ap_ST_fsm_state17 = 75'd65536;
parameter    ap_ST_fsm_state18 = 75'd131072;
parameter    ap_ST_fsm_state19 = 75'd262144;
parameter    ap_ST_fsm_state20 = 75'd524288;
parameter    ap_ST_fsm_state21 = 75'd1048576;
parameter    ap_ST_fsm_state22 = 75'd2097152;
parameter    ap_ST_fsm_state23 = 75'd4194304;
parameter    ap_ST_fsm_state24 = 75'd8388608;
parameter    ap_ST_fsm_state25 = 75'd16777216;
parameter    ap_ST_fsm_state26 = 75'd33554432;
parameter    ap_ST_fsm_state27 = 75'd67108864;
parameter    ap_ST_fsm_state28 = 75'd134217728;
parameter    ap_ST_fsm_state29 = 75'd268435456;
parameter    ap_ST_fsm_state30 = 75'd536870912;
parameter    ap_ST_fsm_state31 = 75'd1073741824;
parameter    ap_ST_fsm_state32 = 75'd2147483648;
parameter    ap_ST_fsm_state33 = 75'd4294967296;
parameter    ap_ST_fsm_state34 = 75'd8589934592;
parameter    ap_ST_fsm_state35 = 75'd17179869184;
parameter    ap_ST_fsm_state36 = 75'd34359738368;
parameter    ap_ST_fsm_state37 = 75'd68719476736;
parameter    ap_ST_fsm_state38 = 75'd137438953472;
parameter    ap_ST_fsm_state39 = 75'd274877906944;
parameter    ap_ST_fsm_state40 = 75'd549755813888;
parameter    ap_ST_fsm_state41 = 75'd1099511627776;
parameter    ap_ST_fsm_state42 = 75'd2199023255552;
parameter    ap_ST_fsm_state43 = 75'd4398046511104;
parameter    ap_ST_fsm_state44 = 75'd8796093022208;
parameter    ap_ST_fsm_state45 = 75'd17592186044416;
parameter    ap_ST_fsm_state46 = 75'd35184372088832;
parameter    ap_ST_fsm_state47 = 75'd70368744177664;
parameter    ap_ST_fsm_state48 = 75'd140737488355328;
parameter    ap_ST_fsm_state49 = 75'd281474976710656;
parameter    ap_ST_fsm_state50 = 75'd562949953421312;
parameter    ap_ST_fsm_state51 = 75'd1125899906842624;
parameter    ap_ST_fsm_state52 = 75'd2251799813685248;
parameter    ap_ST_fsm_state53 = 75'd4503599627370496;
parameter    ap_ST_fsm_state54 = 75'd9007199254740992;
parameter    ap_ST_fsm_state55 = 75'd18014398509481984;
parameter    ap_ST_fsm_state56 = 75'd36028797018963968;
parameter    ap_ST_fsm_state57 = 75'd72057594037927936;
parameter    ap_ST_fsm_state58 = 75'd144115188075855872;
parameter    ap_ST_fsm_state59 = 75'd288230376151711744;
parameter    ap_ST_fsm_state60 = 75'd576460752303423488;
parameter    ap_ST_fsm_state61 = 75'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 75'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 75'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 75'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 75'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 75'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 75'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 75'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 75'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 75'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 75'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 75'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 75'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 75'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 75'd18889465931478580854784;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_CHN_0_AWVALID;
input   m_axi_gmem_CHN_0_AWREADY;
output  [63:0] m_axi_gmem_CHN_0_AWADDR;
output  [0:0] m_axi_gmem_CHN_0_AWID;
output  [31:0] m_axi_gmem_CHN_0_AWLEN;
output  [2:0] m_axi_gmem_CHN_0_AWSIZE;
output  [1:0] m_axi_gmem_CHN_0_AWBURST;
output  [1:0] m_axi_gmem_CHN_0_AWLOCK;
output  [3:0] m_axi_gmem_CHN_0_AWCACHE;
output  [2:0] m_axi_gmem_CHN_0_AWPROT;
output  [3:0] m_axi_gmem_CHN_0_AWQOS;
output  [3:0] m_axi_gmem_CHN_0_AWREGION;
output  [0:0] m_axi_gmem_CHN_0_AWUSER;
output   m_axi_gmem_CHN_0_WVALID;
input   m_axi_gmem_CHN_0_WREADY;
output  [63:0] m_axi_gmem_CHN_0_WDATA;
output  [7:0] m_axi_gmem_CHN_0_WSTRB;
output   m_axi_gmem_CHN_0_WLAST;
output  [0:0] m_axi_gmem_CHN_0_WID;
output  [0:0] m_axi_gmem_CHN_0_WUSER;
output   m_axi_gmem_CHN_0_ARVALID;
input   m_axi_gmem_CHN_0_ARREADY;
output  [63:0] m_axi_gmem_CHN_0_ARADDR;
output  [0:0] m_axi_gmem_CHN_0_ARID;
output  [31:0] m_axi_gmem_CHN_0_ARLEN;
output  [2:0] m_axi_gmem_CHN_0_ARSIZE;
output  [1:0] m_axi_gmem_CHN_0_ARBURST;
output  [1:0] m_axi_gmem_CHN_0_ARLOCK;
output  [3:0] m_axi_gmem_CHN_0_ARCACHE;
output  [2:0] m_axi_gmem_CHN_0_ARPROT;
output  [3:0] m_axi_gmem_CHN_0_ARQOS;
output  [3:0] m_axi_gmem_CHN_0_ARREGION;
output  [0:0] m_axi_gmem_CHN_0_ARUSER;
input   m_axi_gmem_CHN_0_RVALID;
output   m_axi_gmem_CHN_0_RREADY;
input  [63:0] m_axi_gmem_CHN_0_RDATA;
input   m_axi_gmem_CHN_0_RLAST;
input  [0:0] m_axi_gmem_CHN_0_RID;
input  [8:0] m_axi_gmem_CHN_0_RFIFONUM;
input  [0:0] m_axi_gmem_CHN_0_RUSER;
input  [1:0] m_axi_gmem_CHN_0_RRESP;
input   m_axi_gmem_CHN_0_BVALID;
output   m_axi_gmem_CHN_0_BREADY;
input  [1:0] m_axi_gmem_CHN_0_BRESP;
input  [0:0] m_axi_gmem_CHN_0_BID;
input  [0:0] m_axi_gmem_CHN_0_BUSER;
input  [63:0] mem;
input  [255:0] taskIn_TDATA;
input   taskIn_TVALID;
output   taskIn_TREADY;
output  [63:0] addresses_neighbours_0_din;
input  [4:0] addresses_neighbours_0_num_data_valid;
input  [4:0] addresses_neighbours_0_fifo_cap;
input   addresses_neighbours_0_full_n;
output   addresses_neighbours_0_write;
output  [63:0] addresses_neighbours_1_din;
input  [4:0] addresses_neighbours_1_num_data_valid;
input  [4:0] addresses_neighbours_1_fifo_cap;
input   addresses_neighbours_1_full_n;
output   addresses_neighbours_1_write;
output  [63:0] addresses_adj_lists_din;
input  [4:0] addresses_adj_lists_num_data_valid;
input  [4:0] addresses_adj_lists_fifo_cap;
input   addresses_adj_lists_full_n;
output   addresses_adj_lists_write;
output  [31:0] sizes_0_din;
input  [4:0] sizes_0_num_data_valid;
input  [4:0] sizes_0_fifo_cap;
input   sizes_0_full_n;
output   sizes_0_write;
output  [31:0] sizes_1_din;
input  [4:0] sizes_1_num_data_valid;
input  [4:0] sizes_1_fifo_cap;
input   sizes_1_full_n;
output   sizes_1_write;
output  [31:0] sizes_2_din;
input  [4:0] sizes_2_num_data_valid;
input  [4:0] sizes_2_fifo_cap;
input   sizes_2_full_n;
output   sizes_2_write;
output  [31:0] sizes_3_din;
input  [4:0] sizes_3_num_data_valid;
input  [4:0] sizes_3_fifo_cap;
input   sizes_3_full_n;
output   sizes_3_write;
output  [63:0] triangleCountEntries_din;
input  [4:0] triangleCountEntries_num_data_valid;
input  [4:0] triangleCountEntries_fifo_cap;
input   triangleCountEntries_full_n;
output   triangleCountEntries_write;
output  [63:0] return_address_queue_din;
input  [4:0] return_address_queue_num_data_valid;
input  [4:0] return_address_queue_fifo_cap;
input   return_address_queue_full_n;
output   return_address_queue_write;
output  [0:0] fastFinishDelievery_din;
input  [4:0] fastFinishDelievery_num_data_valid;
input  [4:0] fastFinishDelievery_fifo_cap;
input   fastFinishDelievery_full_n;
output   fastFinishDelievery_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_CHN_0_ARVALID;
reg m_axi_gmem_CHN_0_RREADY;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [74:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem_CHN_0_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    gmem_CHN_0_blk_n_R;
wire    ap_CS_fsm_state73;
wire    ap_CS_fsm_state74;
reg    taskIn_TDATA_blk_n;
reg    addresses_neighbours_0_blk_n;
wire    ap_CS_fsm_state75;
wire   [0:0] icmp_ln188_fu_276_p2;
reg    addresses_neighbours_1_blk_n;
reg    addresses_adj_lists_blk_n;
reg    sizes_0_blk_n;
reg    sizes_1_blk_n;
reg    sizes_2_blk_n;
reg    sizes_3_blk_n;
reg    triangleCountEntries_blk_n;
reg    return_address_queue_blk_n;
reg    fastFinishDelievery_blk_n;
wire   [63:0] task_adj_list_fu_197_p4;
reg   [63:0] task_adj_list_reg_281;
reg    ap_block_state1;
reg   [60:0] trunc_ln_reg_286;
reg   [63:0] v_neighbors_reg_297;
wire   [31:0] v_size_neighbors_fu_272_p1;
reg   [31:0] v_size_neighbors_reg_303;
wire  signed [63:0] sext_ln181_fu_262_p1;
reg    return_address_queue_write_local;
wire   [63:0] task_triangle_count_entry_fu_192_p1;
reg    triangleCountEntries_write_local;
reg    ap_block_state75;
reg    sizes_0_write_local;
reg    sizes_1_write_local;
reg    sizes_2_write_local;
reg    sizes_3_write_local;
reg    addresses_neighbours_0_write_local;
reg    addresses_neighbours_1_write_local;
reg    addresses_adj_lists_write_local;
reg   [0:0] fastFinishDelievery_din_local;
reg    fastFinishDelievery_write_local;
wire   [30:0] tmp3_fu_218_p4;
wire   [34:0] shl_ln181_1_fu_228_p3;
wire   [63:0] zext_ln181_fu_236_p1;
wire   [63:0] add_ln181_fu_240_p2;
wire   [63:0] add_ln181_1_fu_246_p2;
reg   [74:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
reg    ap_ST_fsm_state73_blk;
reg    ap_ST_fsm_state74_blk;
reg    ap_ST_fsm_state75_blk;
wire    regslice_both_taskIn_U_apdone_blk;
wire   [255:0] taskIn_TDATA_int_regslice;
wire    taskIn_TVALID_int_regslice;
reg    taskIn_TREADY_int_regslice;
wire    regslice_both_taskIn_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 75'd1;
end

vertex_map_regslice_both #(
    .DataWidth( 256 ))
regslice_both_taskIn_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(taskIn_TDATA),
    .vld_in(taskIn_TVALID),
    .ack_in(regslice_both_taskIn_U_ack_in),
    .data_out(taskIn_TDATA_int_regslice),
    .vld_out(taskIn_TVALID_int_regslice),
    .ack_out(taskIn_TREADY_int_regslice),
    .apdone_blk(regslice_both_taskIn_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state75) & (1'b1 == ap_CS_fsm_state75))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        task_adj_list_reg_281 <= {{taskIn_TDATA_int_regslice[127:64]}};
        trunc_ln_reg_286 <= {{add_ln181_1_fu_246_p2[63:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state73) & (m_axi_gmem_CHN_0_RVALID == 1'b1))) begin
        v_neighbors_reg_297 <= m_axi_gmem_CHN_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state74) & (m_axi_gmem_CHN_0_RVALID == 1'b1))) begin
        v_size_neighbors_reg_303 <= v_size_neighbors_fu_272_p1;
    end
end

always @ (*) begin
    if (((icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        addresses_adj_lists_blk_n = addresses_adj_lists_full_n;
    end else begin
        addresses_adj_lists_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state75) & (icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        addresses_adj_lists_write_local = 1'b1;
    end else begin
        addresses_adj_lists_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        addresses_neighbours_0_blk_n = addresses_neighbours_0_full_n;
    end else begin
        addresses_neighbours_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state75) & (icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        addresses_neighbours_0_write_local = 1'b1;
    end else begin
        addresses_neighbours_0_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        addresses_neighbours_1_blk_n = addresses_neighbours_1_full_n;
    end else begin
        addresses_neighbours_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state75) & (icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        addresses_neighbours_1_write_local = 1'b1;
    end else begin
        addresses_neighbours_1_write_local = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem_CHN_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem_CHN_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state73_blk = 1'b1;
    end else begin
        ap_ST_fsm_state73_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_CHN_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state74_blk = 1'b1;
    end else begin
        ap_ST_fsm_state74_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state75)) begin
        ap_ST_fsm_state75_blk = 1'b1;
    end else begin
        ap_ST_fsm_state75_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state75) & (1'b1 == ap_CS_fsm_state75))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state75) & (1'b1 == ap_CS_fsm_state75))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln188_fu_276_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state75)) | ((icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75)))) begin
        fastFinishDelievery_blk_n = fastFinishDelievery_full_n;
    end else begin
        fastFinishDelievery_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state75) & (1'b1 == ap_CS_fsm_state75))) begin
        if ((icmp_ln188_fu_276_p2 == 1'd1)) begin
            fastFinishDelievery_din_local = 1'd1;
        end else if ((icmp_ln188_fu_276_p2 == 1'd0)) begin
            fastFinishDelievery_din_local = 1'd0;
        end else begin
            fastFinishDelievery_din_local = 'bx;
        end
    end else begin
        fastFinishDelievery_din_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state75) & (icmp_ln188_fu_276_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state75)) | ((1'b0 == ap_block_state75) & (icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75)))) begin
        fastFinishDelievery_write_local = 1'b1;
    end else begin
        fastFinishDelievery_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem_CHN_0_blk_n_AR = m_axi_gmem_CHN_0_ARREADY;
    end else begin
        gmem_CHN_0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        gmem_CHN_0_blk_n_R = m_axi_gmem_CHN_0_RVALID;
    end else begin
        gmem_CHN_0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (m_axi_gmem_CHN_0_ARREADY == 1'b1))) begin
        m_axi_gmem_CHN_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_CHN_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state74) & (m_axi_gmem_CHN_0_RVALID == 1'b1)) | ((1'b1 == ap_CS_fsm_state73) & (m_axi_gmem_CHN_0_RVALID == 1'b1)))) begin
        m_axi_gmem_CHN_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_CHN_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        return_address_queue_blk_n = return_address_queue_full_n;
    end else begin
        return_address_queue_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        return_address_queue_write_local = 1'b1;
    end else begin
        return_address_queue_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        sizes_0_blk_n = sizes_0_full_n;
    end else begin
        sizes_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state75) & (icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        sizes_0_write_local = 1'b1;
    end else begin
        sizes_0_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        sizes_1_blk_n = sizes_1_full_n;
    end else begin
        sizes_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state75) & (icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        sizes_1_write_local = 1'b1;
    end else begin
        sizes_1_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        sizes_2_blk_n = sizes_2_full_n;
    end else begin
        sizes_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state75) & (icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        sizes_2_write_local = 1'b1;
    end else begin
        sizes_2_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        sizes_3_blk_n = sizes_3_full_n;
    end else begin
        sizes_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state75) & (icmp_ln188_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        sizes_3_write_local = 1'b1;
    end else begin
        sizes_3_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        taskIn_TDATA_blk_n = taskIn_TVALID_int_regslice;
    end else begin
        taskIn_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        taskIn_TREADY_int_regslice = 1'b1;
    end else begin
        taskIn_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        triangleCountEntries_blk_n = triangleCountEntries_full_n;
    end else begin
        triangleCountEntries_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        triangleCountEntries_write_local = 1'b1;
    end else begin
        triangleCountEntries_write_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (m_axi_gmem_CHN_0_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            if (((1'b1 == ap_CS_fsm_state73) & (m_axi_gmem_CHN_0_RVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state73;
            end
        end
        ap_ST_fsm_state74 : begin
            if (((1'b1 == ap_CS_fsm_state74) & (m_axi_gmem_CHN_0_RVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end
        end
        ap_ST_fsm_state75 : begin
            if (((1'b0 == ap_block_state75) & (1'b1 == ap_CS_fsm_state75))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln181_1_fu_246_p2 = (add_ln181_fu_240_p2 + task_adj_list_fu_197_p4);

assign add_ln181_fu_240_p2 = (zext_ln181_fu_236_p1 + mem);

assign addresses_adj_lists_din = task_adj_list_reg_281;

assign addresses_adj_lists_write = addresses_adj_lists_write_local;

assign addresses_neighbours_0_din = v_neighbors_reg_297;

assign addresses_neighbours_0_write = addresses_neighbours_0_write_local;

assign addresses_neighbours_1_din = v_neighbors_reg_297;

assign addresses_neighbours_1_write = addresses_neighbours_1_write_local;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

always @ (*) begin
    ap_block_state1 = ((taskIn_TVALID_int_regslice == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | (return_address_queue_full_n == 1'b0) | (triangleCountEntries_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state75 = (((1'b0 == addresses_adj_lists_full_n) & (icmp_ln188_fu_276_p2 == 1'd0)) | ((1'b0 == addresses_neighbours_1_full_n) & (icmp_ln188_fu_276_p2 == 1'd0)) | ((1'b0 == addresses_neighbours_0_full_n) & (icmp_ln188_fu_276_p2 == 1'd0)) | ((icmp_ln188_fu_276_p2 == 1'd1) & (fastFinishDelievery_full_n == 1'b0)) | ((icmp_ln188_fu_276_p2 == 1'd0) & (fastFinishDelievery_full_n == 1'b0)) | ((icmp_ln188_fu_276_p2 == 1'd0) & (sizes_3_full_n == 1'b0)) | ((icmp_ln188_fu_276_p2 == 1'd0) & (sizes_2_full_n == 1'b0)) | ((icmp_ln188_fu_276_p2 == 1'd0) & (sizes_1_full_n == 1'b0)) | ((icmp_ln188_fu_276_p2 == 1'd0) & (sizes_0_full_n == 1'b0)));
end

assign fastFinishDelievery_din = fastFinishDelievery_din_local;

assign fastFinishDelievery_write = fastFinishDelievery_write_local;

assign icmp_ln188_fu_276_p2 = ((v_size_neighbors_reg_303 == 32'd0) ? 1'b1 : 1'b0);

assign m_axi_gmem_CHN_0_ARADDR = sext_ln181_fu_262_p1;

assign m_axi_gmem_CHN_0_ARBURST = 2'd0;

assign m_axi_gmem_CHN_0_ARCACHE = 4'd0;

assign m_axi_gmem_CHN_0_ARID = 1'd0;

assign m_axi_gmem_CHN_0_ARLEN = 64'd2;

assign m_axi_gmem_CHN_0_ARLOCK = 2'd0;

assign m_axi_gmem_CHN_0_ARPROT = 3'd0;

assign m_axi_gmem_CHN_0_ARQOS = 4'd0;

assign m_axi_gmem_CHN_0_ARREGION = 4'd0;

assign m_axi_gmem_CHN_0_ARSIZE = 3'd0;

assign m_axi_gmem_CHN_0_ARUSER = 1'd0;

assign m_axi_gmem_CHN_0_AWADDR = 64'd0;

assign m_axi_gmem_CHN_0_AWBURST = 2'd0;

assign m_axi_gmem_CHN_0_AWCACHE = 4'd0;

assign m_axi_gmem_CHN_0_AWID = 1'd0;

assign m_axi_gmem_CHN_0_AWLEN = 32'd0;

assign m_axi_gmem_CHN_0_AWLOCK = 2'd0;

assign m_axi_gmem_CHN_0_AWPROT = 3'd0;

assign m_axi_gmem_CHN_0_AWQOS = 4'd0;

assign m_axi_gmem_CHN_0_AWREGION = 4'd0;

assign m_axi_gmem_CHN_0_AWSIZE = 3'd0;

assign m_axi_gmem_CHN_0_AWUSER = 1'd0;

assign m_axi_gmem_CHN_0_AWVALID = 1'b0;

assign m_axi_gmem_CHN_0_BREADY = 1'b0;

assign m_axi_gmem_CHN_0_WDATA = 64'd0;

assign m_axi_gmem_CHN_0_WID = 1'd0;

assign m_axi_gmem_CHN_0_WLAST = 1'b0;

assign m_axi_gmem_CHN_0_WSTRB = 8'd0;

assign m_axi_gmem_CHN_0_WUSER = 1'd0;

assign m_axi_gmem_CHN_0_WVALID = 1'b0;

assign return_address_queue_din = {{taskIn_TDATA_int_regslice[191:128]}};

assign return_address_queue_write = return_address_queue_write_local;

assign sext_ln181_fu_262_p1 = $signed(trunc_ln_reg_286);

assign shl_ln181_1_fu_228_p3 = {{tmp3_fu_218_p4}, {4'd0}};

assign sizes_0_din = v_size_neighbors_reg_303;

assign sizes_0_write = sizes_0_write_local;

assign sizes_1_din = v_size_neighbors_reg_303;

assign sizes_1_write = sizes_1_write_local;

assign sizes_2_din = v_size_neighbors_reg_303;

assign sizes_2_write = sizes_2_write_local;

assign sizes_3_din = v_size_neighbors_reg_303;

assign sizes_3_write = sizes_3_write_local;

assign taskIn_TREADY = regslice_both_taskIn_U_ack_in;

assign task_adj_list_fu_197_p4 = {{taskIn_TDATA_int_regslice[127:64]}};

assign task_triangle_count_entry_fu_192_p1 = taskIn_TDATA_int_regslice[63:0];

assign tmp3_fu_218_p4 = {{taskIn_TDATA_int_regslice[222:192]}};

assign triangleCountEntries_din = task_triangle_count_entry_fu_192_p1;

assign triangleCountEntries_write = triangleCountEntries_write_local;

assign v_size_neighbors_fu_272_p1 = m_axi_gmem_CHN_0_RDATA[31:0];

assign zext_ln181_fu_236_p1 = shl_ln181_1_fu_228_p3;

endmodule //vertex_map_readTask
