// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module vertex_map_writeArg (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        argDataOut_TDATA,
        argDataOut_TVALID,
        argDataOut_TREADY,
        argOut_TDATA,
        argOut_TVALID,
        argOut_TREADY,
        count_stream_dout,
        count_stream_num_data_valid,
        count_stream_fifo_cap,
        count_stream_empty_n,
        count_stream_read,
        triangleCountEntries_dout,
        triangleCountEntries_num_data_valid,
        triangleCountEntries_fifo_cap,
        triangleCountEntries_empty_n,
        triangleCountEntries_read,
        return_address_queue_dout,
        return_address_queue_num_data_valid,
        return_address_queue_fifo_cap,
        return_address_queue_empty_n,
        return_address_queue_read,
        fastFinishDelievery_dout,
        fastFinishDelievery_num_data_valid,
        fastFinishDelievery_fifo_cap,
        fastFinishDelievery_empty_n,
        fastFinishDelievery_read
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [255:0] argDataOut_TDATA;
output   argDataOut_TVALID;
input   argDataOut_TREADY;
output  [63:0] argOut_TDATA;
output   argOut_TVALID;
input   argOut_TREADY;
input  [31:0] count_stream_dout;
input  [4:0] count_stream_num_data_valid;
input  [4:0] count_stream_fifo_cap;
input   count_stream_empty_n;
output   count_stream_read;
input  [63:0] triangleCountEntries_dout;
input  [4:0] triangleCountEntries_num_data_valid;
input  [4:0] triangleCountEntries_fifo_cap;
input   triangleCountEntries_empty_n;
output   triangleCountEntries_read;
input  [63:0] return_address_queue_dout;
input  [4:0] return_address_queue_num_data_valid;
input  [4:0] return_address_queue_fifo_cap;
input   return_address_queue_empty_n;
output   return_address_queue_read;
input  [0:0] fastFinishDelievery_dout;
input  [4:0] fastFinishDelievery_num_data_valid;
input  [4:0] fastFinishDelievery_fifo_cap;
input   fastFinishDelievery_empty_n;
output   fastFinishDelievery_read;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    argDataOut_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    argOut_TDATA_blk_n;
reg    count_stream_blk_n;
reg   [0:0] fastFinish_reg_118;
reg    triangleCountEntries_blk_n;
reg    return_address_queue_blk_n;
reg    fastFinishDelievery_blk_n;
wire   [0:0] fastFinish_read_fu_44_p2;
reg    ap_block_state1;
reg   [63:0] entry_2_reg_122;
reg   [63:0] return_address_reg_127;
reg    ap_block_state2;
reg    ap_block_state2_io;
reg   [31:0] ap_phi_mux_count_local_2_phi_fu_86_p4;
reg   [31:0] count_local_2_reg_82;
reg    fastFinishDelievery_read_local;
reg    triangleCountEntries_read_local;
reg    return_address_queue_read_local;
reg    count_stream_read_local;
wire   [95:0] tmp_fu_94_p3;
wire   [96:0] zext_ln220_fu_101_p1;
wire   [128:0] zext_ln220_1_cast_fu_105_p3;
wire    regslice_both_argDataOut_U_apdone_blk;
wire    regslice_both_argOut_U_apdone_blk;
reg    ap_block_state3;
reg    ap_block_state3_io;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire   [255:0] argDataOut_TDATA_int_regslice;
reg    argDataOut_TVALID_int_regslice;
wire    argDataOut_TREADY_int_regslice;
wire    regslice_both_argDataOut_U_vld_out;
reg    argOut_TVALID_int_regslice;
wire    argOut_TREADY_int_regslice;
wire    regslice_both_argOut_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
end

vertex_map_regslice_both #(
    .DataWidth( 256 ))
regslice_both_argDataOut_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(argDataOut_TDATA_int_regslice),
    .vld_in(argDataOut_TVALID_int_regslice),
    .ack_in(argDataOut_TREADY_int_regslice),
    .data_out(argDataOut_TDATA),
    .vld_out(regslice_both_argDataOut_U_vld_out),
    .ack_out(argDataOut_TREADY),
    .apdone_blk(regslice_both_argDataOut_U_apdone_blk)
);

vertex_map_regslice_both #(
    .DataWidth( 64 ))
regslice_both_argOut_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(return_address_reg_127),
    .vld_in(argOut_TVALID_int_regslice),
    .ack_in(argOut_TREADY_int_regslice),
    .data_out(argOut_TDATA),
    .vld_out(regslice_both_argOut_U_vld_out),
    .ack_out(argOut_TREADY),
    .apdone_blk(regslice_both_argOut_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (fastFinish_read_fu_44_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        count_local_2_reg_82 <= 32'd0;
    end else if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2)) & (fastFinish_reg_118 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        count_local_2_reg_82 <= count_stream_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        entry_2_reg_122 <= triangleCountEntries_dout;
        fastFinish_reg_118 <= fastFinishDelievery_dout;
        return_address_reg_127 <= return_address_queue_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((fastFinish_reg_118 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_phi_mux_count_local_2_phi_fu_86_p4 = count_stream_dout;
    end else begin
        ap_phi_mux_count_local_2_phi_fu_86_p4 = count_local_2_reg_82;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        argDataOut_TDATA_blk_n = argDataOut_TREADY_int_regslice;
    end else begin
        argDataOut_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2)) & (1'b1 == ap_CS_fsm_state2))) begin
        argDataOut_TVALID_int_regslice = 1'b1;
    end else begin
        argDataOut_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        argOut_TDATA_blk_n = argOut_TREADY_int_regslice;
    end else begin
        argOut_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2)) & (1'b1 == ap_CS_fsm_state2))) begin
        argOut_TVALID_int_regslice = 1'b1;
    end else begin
        argOut_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((fastFinish_reg_118 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        count_stream_blk_n = count_stream_empty_n;
    end else begin
        count_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2)) & (fastFinish_reg_118 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        count_stream_read_local = 1'b1;
    end else begin
        count_stream_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        fastFinishDelievery_blk_n = fastFinishDelievery_empty_n;
    end else begin
        fastFinishDelievery_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        fastFinishDelievery_read_local = 1'b1;
    end else begin
        fastFinishDelievery_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        return_address_queue_blk_n = return_address_queue_empty_n;
    end else begin
        return_address_queue_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        return_address_queue_read_local = 1'b1;
    end else begin
        return_address_queue_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        triangleCountEntries_blk_n = triangleCountEntries_empty_n;
    end else begin
        triangleCountEntries_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        triangleCountEntries_read_local = 1'b1;
    end else begin
        triangleCountEntries_read_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (fastFinishDelievery_empty_n == 1'b0) | (return_address_queue_empty_n == 1'b0) | (triangleCountEntries_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((argOut_TREADY_int_regslice == 1'b0) | (argDataOut_TREADY_int_regslice == 1'b0) | ((fastFinish_reg_118 == 1'd0) & (count_stream_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_io = ((argOut_TREADY_int_regslice == 1'b0) | (argDataOut_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((argOut_TREADY_int_regslice == 1'b0) | (argDataOut_TREADY_int_regslice == 1'b0) | (regslice_both_argOut_U_apdone_blk == 1'b1) | (regslice_both_argDataOut_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_block_state3_io = ((argOut_TREADY_int_regslice == 1'b0) | (argDataOut_TREADY_int_regslice == 1'b0));
end

assign argDataOut_TDATA_int_regslice = zext_ln220_1_cast_fu_105_p3;

assign argDataOut_TVALID = regslice_both_argDataOut_U_vld_out;

assign argOut_TVALID = regslice_both_argOut_U_vld_out;

assign count_stream_read = count_stream_read_local;

assign fastFinishDelievery_read = fastFinishDelievery_read_local;

assign fastFinish_read_fu_44_p2 = fastFinishDelievery_dout;

assign return_address_queue_read = return_address_queue_read_local;

assign tmp_fu_94_p3 = {{ap_phi_mux_count_local_2_phi_fu_86_p4}, {entry_2_reg_122}};

assign triangleCountEntries_read = triangleCountEntries_read_local;

assign zext_ln220_1_cast_fu_105_p3 = {{32'd2147483649}, {zext_ln220_fu_101_p1}};

assign zext_ln220_fu_101_p1 = tmp_fu_94_p3;

endmodule //vertex_map_writeArg
